src/Keboola/StorageApi/Client.php, tests/Keboola/StorageApi/ComponentsTest.php, tests/Keboola/StorageApi/TokensTest.php
as per https://github.com/keboola/connection/issues/248
=> Token component access

src/Keboola/StorageApi/Client.php, tests/Keboola/StorageApi/BucketsTest.php
Support for force bucket delete (tests included)
=> Buckets delete

phpunit.xml.dist, tests/Backend/Workspaces/WorkspacesTest.php, tests/Backend/Workspaces/WorkspacesUnloadTest.php
Passing tests, but minimal coverage.
=> Redshift workspaces

phpunit.xml.dist, tests/Backend/Mixed/WorkspacesTest.php, tests/Backend/Workspaces/Backend/RedshiftWorkspaceBackend.php, tests/Backend/Workspaces/Backend/SnowflakeWorkspaceBackend.php, tests/Backend/Workspaces/Backend/WorkspaceBackend.php, tests/Backend/Workspaces/WorkspacesRedshiftTest.php, tests/Backend/Workspaces/WorkspacesTest.php
Updated tests for RS sort and dist and mixed loading test.
=> Workspaces iii

tests/Backend/Workspaces/Backend/RedshiftWorkspaceBackend.php, tests/Backend/Workspaces/Backend/SnowflakeWorkspaceBackend.php, tests/Backend/Workspaces/Backend/WorkspaceBackend.php, tests/Backend/Workspaces/WorkspacesLoadTest.php
So this is a simple test that the queries are being formed correctly and the datatypes are applied.  Ideally the describeTable methods would both do the "same thing" so as to avoid the  conditionals, so there's some "todo" remaining here.
=> Simple datatypes test

tests/Backend/Workspaces/WorkspacesTest.php, tests/Backend/Workspaces/WorkspacesTestCase.php
test for https://github.com/keboola/connection/issues/457
=> drop workspace test

tests/Backend/Mixed/WorkspacesTest.php, tests/Backend/Workspaces/WorkspacesRedshiftTest.php, tests/Backend/Workspaces/WorkspacesSnowflakeTest.php, tests/_data/transactions.csv
re: https://github.com/keboola/connection/pull/555
=> Workspace related

composer.json, src/Keboola/StorageApi/Client.php
This should allow components that are symfony 2 or 3 dependent to use the client without issue.
=> dependency to symphony 2 or 3

apiary.apib, tests/Common/ComponentsTest.php
Uprava souvisejici s metadatama ulozenyma pod `currentVersion` u KBC konfiguraci
- test
- apiary file
=> Current config meta

tests/Backend/CommonPart1/AlterTableTest.php
test for https://github.com/keboola/connection/pull/745
=> test for missing columns when adding PK

apiary.apib, src/Keboola/StorageApi/Workspaces.php, tests/Backend/Workspaces/WorkspacesTest.php
Support for resetting password of workspace
https://github.com/keboola/connection/issues/829
=> Workspace password reset

tests/Backend/CommonPart1/BucketsTest.php, tests/StorageApiTestCase.php
Test related to https://github.com/keboola/connection/issues/908
=> Bucket list test

tests/Common/ComponentsTest.php
TESTS https://github.com/keboola/connection/issues/977
=> fix: row attributes on copy/rollback

tests/Common/ComponentsTest.php
https://github.com/keboola/connection/issues/1039
=> test: string config description

tests/Common/ComponentsTest.php, tests/Common/ConfigurationRowTest.php
Tests for: https://github.com/keboola/connection/issues/1088 and https://github.com/keboola/connection/issues/1047
=> Add boolean parameter tests in components api

apiary.apib, tests/Backend/Mixed/SharingTest.php
Ref: https://github.com/keboola/connection/issues/1113
=> Linked bucket info

README.md, src/Keboola/StorageApi/Client.php, tests/Common/CommonTest.php
Unification with manage API client where default URL was also removed.
=> Url required

apiary.apib, src/Keboola/StorageApi/Client.php
https://github.com/keboola/storage-api-php-client/issues/177
=> Deprecate indexed columns

tests/Common/ComponentsTest.php
tests for https://github.com/keboola/connection/pull/1214
=> tests - empty configurations versioning

tests/Backend/CommonPart1/AlterTableTest.php, tests/Backend/CommonPart1/CreateTableTest.php, tests/Backend/CommonPart1/DeleteRowsTest.php, tests/Backend/CommonPart1/ExportParamsTest.php, tests/Backend/CommonPart2/SimpleAliasTest.php, tests/Backend/CommonPart2/SnapshottingTest.php, tests/Backend/Mixed/SharingTest.php, tests/Backend/Workspaces/LegacyWorkspacesLoadTest.php, tests/Backend/Workspaces/WorkspacesLoadTest.php
FIXES #178 
Tady zatím odebírám práci s indexovanými sloupci pro všechny aktuální backendy. Nechal jsem ji pro práci s MySQL backendem, který celkově půjde pryš v další PR.
=> Remove indexed columns

composer.json, src/Keboola/StorageApi/Client.php, src/Keboola/StorageApi/createSimpleJobPollDelay.php, tests/Backend/CommonPart2/JobPollDelayTest.php, tests/Backend/Snowflake/TimeTravelTest.php, tests/Common/JobPollDelayTest.php, tests/Common/SimpleJobPollDelayTest.php, tests/StorageApiTestCase.php
ref: https://github.com/keboola/storage-api-php-client/issues/171
=> override job polling delay method

tests/Common/TokensTest.php
Test občas failloval protože testoval response expirovaného tokenu `storage.tokenExpired`.
Tuhle odpověd to ale vrací jenom mezi okamžikem expirace tokenu a jeho uplným smazáním které dělá cron každou minutu. Potom začne už vracet 401.
=> tests - expired token stable #110

apiary.apib, tests/Common/MetadataTest.php
test for: https://github.com/keboola/connection/pull/1220
=> test for bucket metadata in table detail response

tests/Common/ComponentsTest.php
Tests https://github.com/keboola/connection/pull/1291
=> TEST: Set default change description when creating a configuration

tests/Backend/Workspaces/ComponentsWorkspacesTest.php
=> TEST: Remove excessive assertions

composer.json, phpstan.neon, src/Keboola/StorageApi/Client.php, src/Keboola/StorageApi/TableExporter.php, src/Keboola/StorageApi/createSimpleJobPollDelay.php, tests/Backend/CommonPart1/ImportExportCommonTest.php, tests/Backend/CommonPart1/TableExporterTest.php, tests/Backend/Redshift/OptimizeTest.php, tests/Backend/Workspaces/Backend/SnowflakeWorkspaceBackend.php, tests/Backend/Workspaces/Backend/WorkspaceBackendFactory.php, tests/Backend/Workspaces/WorkspacesLoadTest.php, tests/Backend/Workspaces/WorkspacesRenameLoadTest.php, tests/Backend/Workspaces/WorkspacesUnloadTest.php, tests/Common/CommonTest.php, tests/Common/ConfigurationRowStateTest.php, tests/Common/ConfigurationRowsSortOrderTest.php, tests/Common/TablesListingTest.php
=> Add phpstan

tests/Common/ConfigurationRowStateTest.php
there wasn't really assertion https://github.com/keboola/storage-api-php-client/commit/95f4c053c79459ee2e6fd705cf25c2ebae5ac0e6#diff-607a6f2530e0efc3d1f91e7d8e2b51f9L46
=> fixup after previous cleanup

tests/Common/ComponentsTest.php
Tests https://github.com/keboola/connection/pull/1313
Fixes https://github.com/keboola/connection/issues/1314
=> Add invalid include setting to test that it's dropped

src/Keboola/StorageApi/Options/Components/Configuration.php
=> fix - rows sort order default value

apiary.apib
Releated to https://github.com/keboola/connection/issues/1404#issuecomment-405547508
=> deprecate form uploads

apiary.apib, src/Keboola/StorageApi/Components.php, src/Keboola/StorageApi/Options/Components/ListConfigurationRowsOptions.php, tests/Common/ConfigurationRowTest.php
https://github.com/keboola/connection/pull/1444
=> Define new endpoint

apiary.apib, src/Keboola/StorageApi/Client.php, tests/Backend/CommonPart1/CreateTableTest.php, tests/Backend/CommonPart1/ImportExportCommonTest.php, tests/Backend/CommonPart1/TableExporterTest.php
Remove tests of URL imports https://github.com/keboola/connection/issues/1528
It can be merged before backend https://github.com/keboola/connection/pull/1528
=> URL import remove

tests/Common/ConfigurationRowTest.php
connection issue: https://github.com/keboola/connection/issues/1537
ui issue https://github.com/keboola/kbc-ui/issues/1992
=> Test isDisabled in create config row

tests/Common/ComponentsTest.php
Related https://github.com/keboola/connection/issues/1237
Required for https://github.com/keboola/connection/pull/1619
=> State is reset on copy

tests/Common/ConfigurationRowStateTest.php
=> tests - copy row resets state

tests/Common/JobsListTest.php
Found we didn't have tests for this when doing https://github.com/keboola/connection/pull/1648
@Halama I'm just not sure if I can assume that jobs exist during the Common tests.
=> Add test for jobs list limit and offset

src/Keboola/StorageApi/Client.php, tests/Common/LoggingTest.php
refactor: change logger to be always initialized
refactor: logger logs with debug level by default
fix: log multipart upload errors
=> logger changes

tests/Backend/Workspaces/WorkspacesTest.php
Tests: https://github.com/keboola/connection/pull/1701
=> Test that runId is added to events for sync actions

tests/Backend/CommonPart1/DataPreviewLimitsTest.php
=> Skip testJsonTruncationLimit test on Redshift backend

tests/Backend/Snowflake/CloneIntoWorkspaceTest.php, tests/Backend/Workspaces/LegacyWorkspacesLoadTest.php, tests/Backend/Workspaces/WorkspacesTest.php
Tests https://github.com/keboola/connection/pull/1696
=> Improve events for Workspace related tasks

apiary.apib
Dokumentace pro datapreview format=json. Možná to jde napsat v apiary nějak líp, ale nepřišel jsem na to.
=> Docs for datapreview param format

tests/Backend/Mixed/SharingTest.php, tests/Backend/Snowflake/CloneIntoWorkspaceTest.php
Úprava testů na velikost bunky VARCHAR na 16MB
=> New max VARCHAR value is 16MB

docker-compose.yml, docker/xdebug/Dockerfile
Instalace xdebug v tý nejmenší konfiguraci ;)
=> SAPI - instalace xdebug

tests/Backend/Mixed/SharingTest.php, tests/Backend/Snowflake/CloneIntoWorkspaceTest.php
Tests for https://github.com/keboola/connection/pull/1823
Where are wrong event parameters fixed #1731
=> Test clone load event parameters

tests/Backend/Snowflake/CloneIntoWorkspaceTest.php
Tests for https://github.com/keboola/connection/pull/1830
=> Tests - snowflake load clone overwrite with preserve

apiary.apib, tests/Common/MetadataTest.php
I felt like a couple of tests were missing from the metadata section so added them here.  They may be redundant, but I don't think so.
=> Additional metadata tests

apiary.apib, src/Keboola/StorageApi/Client.php, tests/Backend/Redshift/OrderByTest.php, tests/Backend/Snowflake/OrderByTest.php
Related to https://github.com/keboola/connection/pull/1819
=> Test: Export can be sorted

apiary.apib
sync export was deleted in https://github.com/keboola/connection/issues/1685#event-2155227505
=> Remove apiary docs for sync export

apiary.apib, src/Keboola/StorageApi/Client.php, tests/Backend/Redshift/FulltextSearchTest.php, tests/Backend/Snowflake/FulltextSearchTest.php
Tests for https://github.com/keboola/connection/pull/1829
By default to začně fungovat i na asyncExportu, ale na to jsem testy nedělal a ani jsem to nedával do dokumentace. Podle mě tam to je trochu zbytečný
=> Test for fulltext search

tests/Backend/CommonPart2/SimpleAliasTest.php, tests/Backend/Mixed/SharingTest.php, tests/Backend/Snowflake/CloneIntoWorkspaceTest.php, tests/Backend/Workspaces/WorkspacesLoadTest.php, tests/StorageApiTestCase.php
Tests for https://github.com/keboola/connection/pull/1886
=> Shared Aliases

apiary.apib, src/Keboola/StorageApi/Client.php, tests/Common/TriggersTest.php, tests/StorageApiTestCase.php
Testy a APIARY k zakládní/mazání triggeru https://github.com/keboola/connection/pull/1915
=> CRUD for event triggers tests + apib

apiary.apib, src/Keboola/StorageApi/Client.php, tests/Common/TriggersTest.php, tests/StorageApiTestCase.php
Reverts keboola/storage-api-php-client#294
=> Revert "Revert "CRUD for event triggers tests + apib""

apiary.apib, tests/Common/TriggersTest.php
Znova tam posílám přejmenování parametrů
=> Revert "Revert "Change coolDownPerio to coolDownPeriodMinutes""

src/Keboola/StorageApi/Client.php, tests/Backend/CommonPart1/DataPreviewLimitsTest.php, tests/Backend/CommonPart2/SimpleAliasTest.php, tests/Backend/Mixed/SharingTest.php, tests/Backend/Redshift/FulltextSearchTest.php, tests/Backend/Redshift/OrderByTest.php, tests/Backend/Redshift/WhereFilterTest.php, tests/Backend/Snowflake/CloneIntoWorkspaceTest.php, tests/Backend/Snowflake/FulltextSearchTest.php, tests/Backend/Snowflake/OrderByTest.php, tests/Backend/Snowflake/WhereFilterTest.php, tests/Common/ConfigurationRowTest.php, tests/Common/JobsListTest.php, tests/Common/MetadataTest.php, tests/Common/TriggersTest.php, tests/StorageApiTestCase.php
Odtranil jsem všechno, co mě napadlo, že by mohlo bránit kompatibilitě s PHP 5.6
=> Removing PHP7 features

tests/Common/TriggersTest.php
Test, že se provede správně update na 2 triggerech, co se týče tabulek.
=> Event-triggers - Tests for double table update

src/Keboola/StorageApi/Client.php, src/Keboola/StorageApi/Options/TokenAbstractOptions.php, src/Keboola/StorageApi/Options/TokenCreateOptions.php, src/Keboola/StorageApi/Options/TokenUpdateOptions.php, tests/Backend/CommonPart1/ExportParamsTest.php, tests/Backend/Mixed/SharingTest.php, tests/Backend/Snowflake/TimeTravelTest.php, tests/Backend/Workspaces/LegacyWorkspacesLoadTest.php, tests/Backend/Workspaces/WorkspacesLoadTest.php, tests/Common/ComponentsTest.php, tests/Common/FilesTest.php, tests/Common/TokensShareTest.php, tests/Common/TokensTest.php, tests/Common/TriggersTest.php
fixup https://github.com/keboola/storage-api-php-client/pull/293
=> fixup: client createToken + updateToken methods refactoring

.travis.yml, deploy-tag.sh
Fixes: #297 
Changes:
- new deploy section
- add script to deploy tags prefixed with `test-`
=> Add new deploy section to push image also on specific tags

tests/Common/TriggersTest.php
Test na založení triggeru s neexistujícím tokenem
=> Create trigger with invalid token

apiary.apib
ref https://keboolaglobal.slack.com/archives/CBX9MB2NT/p1557766010106700?thread_ts=1557762272.105100&cid=CBX9MB2NT
=> docs: minor clarification to apib

tests/Backend/Snowflake/OrderByTest.php, tests/Backend/Snowflake/WhereFilterTest.php
Testy k validaci datapreview https://github.com/keboola/connection/pull/2008
=> Tests for invalid orderBy and whereFilters

apiary.apib, src/Keboola/StorageApi/Options/TokenAbstractOptions.php, tests/Common/TokensTest.php
Testy pro PR https://github.com/keboola/connection/pull/1948
=> new token privilege canPurgeTrash 

apiary.apib, src/Keboola/StorageApi/Client.php, tests/Common/TokensTest.php, tests/StorageApiTestCase.php
Listovani event pro zadany token
=> Token events list

tests/Common/TokensTest.php
Related https://github.com/keboola/connection/pull/2078
rehresh vlastniho tokenu
=> tests: token self refresh

apiary.apib, tests/Common/TriggersTest.php
Opravil jsem v apiary response, aby odpovídala skutečnosti a přetypoval jsem všechno na string.
Upravil jsem testy, aby se testovaly i hodnoty craetorToken a creatorUser, které jsem měnil.
Testy patří k https://github.com/keboola/connection/pull/2116
=> Tests for better API trigger response + apiary fix

tests/Backend/Mixed/SharingTest.php, tests/Common/MetadataTest.php
Tests https://github.com/keboola/connection/pull/2144
=> Test metadata propagation through aliases

tests/File/CommonFileTest.php
Vylepšil jsem test na mazání, který kontroluje, že se soubor doopravdy smazal.
=> Test for azure delete

src/Keboola/StorageApi/Client.php, tests/Common/TokensTest.php
https://github.com/keboola/connection/issues/2245 (private)
=> remove getKeenReadCredentials

apiary.apib, src/Keboola/StorageApi/Client.php, tests/Backend/Mixed/SharingTest.php
Hlavny PR: https://github.com/keboola/connection/pull/2239
organization project + tests
=> Add method for separate endpoints for bucket share for organization and

tests/Common/SearchTablesTest.php
extend test case for condition when tables with same name are in two different buckets
=> FIX search api test

tests/Backend/Mixed/SharingToSpecificProjectsTest.php
Main: https://github.com/keboola/connection/pull/2278
=> Oprava bugu sharovania do projektov

apiary.apib, src/Keboola/StorageApi/Client.php, tests/Backend/Mixed/SharingTest.php
JIRA https://keboola.atlassian.net/browse/KBC-42
=> KBC-42 include parameter in Shared buckets list

tests/Backend/Workspaces/WorkspacesSnowflakeTest.php
https://github.com/keboola/connection/pull/2288
=> add test for CLIENT_SESSION_KEEP_ALIVE

tests/Common/ComponentsEventsTest.php
https://keboola.atlassian.net/browse/KBC-61
=> KBC-61 storage api events tests

tests/Common/ComponentsEventsTest.php
Fixed test for events in component configuratiosn
=> [fix] assert configuration name kbc-61

tests/Common/QueueJobsTest.php
https://keboola.atlassian.net/browse/KBC-102
=> KBC-102 Fix QueueJobsTest

tests/Common/ComponentsEventsTest.php
https://keboola.atlassian.net/browse/KBC-114
=> KBC-114 add case when configuration update is called but there is no change

apiary.apib, tests/Backend/Mixed/SharingTest.php
Main PR: https://github.com/keboola/connection/pull/2330
JIRA Issue: https://keboola.atlassian.net/browse/KBC-153
=> Add more info to shared bucket

.gitignore, phpunit.xml.dist, tests/Backend/Workspaces/MetadataFromRedshiftWorkspaceTest.php, tests/Backend/Workspaces/MetadataFromSnowflakeWorkspaceTest.php, tests/StorageApiTestCase.php, tests/_data/metadataBug.csv
Main PR: https://github.com/keboola/connection/pull/2316
=> Add test for testing bug in snowflake

tests/Backend/Snowflake/CloneIntoWorkspaceTest.php
Main PR: https://github.com/keboola/connection/pull/2372
=> Add testing `outBytes` when loading to snowflake workspace job

apiary.apib, tests/Backend/Mixed/SharingTest.php
https://keboola.atlassian.net/browse/KBC-151
Testing https://github.com/keboola/connection/pull/2362
=> KBC-151 Ensure that sharedBy appears in bucket responses

tests/Backend/Workspaces/WorkspacesRedshiftTest.php, tests/Backend/Workspaces/WorkspacesSnowflakeTest.php
Main PR: https://github.com/keboola/connection/pull/2374
=> Kbc 181 roman workspace load data size bytes from metadata

apiary.apib, src/Keboola/StorageApi/Client.php, tests/Backend/Mixed/SharingTest.php, tests/Backend/Mixed/SharingToSpecificProjectsTest.php, tests/Backend/Mixed/SharingToSpecificUsersTest.php, tests/Backend/Mixed/StorageApiSharingTestCase.php
Main PR: https://github.com/keboola/connection/pull/2339
JIRA Issue: https://keboola.atlassian.net/browse/KBC-154
Add testing for shared bucket return metadata for table and columns and their metadata
=> Edit response shared-buckets

apiary.apib, src/Keboola/StorageApi/Client.php, tests/Backend/Mixed/SharingTest.php, tests/Backend/Mixed/SharingToSpecificProjectsTest.php, tests/Backend/Mixed/SharingToSpecificUsersTest.php, tests/Backend/Mixed/StorageApiSharingTestCase.php
Reverts keboola/storage-api-php-client#366
=> Revert "Edit response shared-buckets"

src/Keboola/StorageApi/Client.php, tests/Common/IndexTest.php
Main PR: https://github.com/keboola/connection/pull/2403
JIRA story: https://keboola.atlassian.net/browse/KBC-248
=> KBC-248 add test for new webalize endpoint

apiary.apib, src/Keboola/StorageApi/Client.php, src/Keboola/StorageApi/Options/BucketUpdateOptions.php, tests/Backend/CommonPart1/BucketsTest.php
JIRA story: https://keboola.atlassian.net/browse/KBC-258
Main PR: https://github.com/keboola/connection/pull/2406
=> KBC-258 new endpoint for rename display name for buckets

tests/Backend/CommonPart1/BucketsTest.php, tests/Backend/Mixed/SharingTest.php
Fix spadnutych testov https://travis-ci.com/github/keboola/connection/jobs/299001463
=> KBC-258 Fix error messages in tests

apiary.apib, tests/Backend/CommonPart1/CreateTableTest.php, tests/Backend/Mixed/SharingTest.php, tests/Common/SearchTablesTest.php, tests/Common/TablesListingTest.php
Main PR: https://github.com/keboola/connection/pull/2412
=> KBC-254 Pridat parameter displayName pre vytvaranie tabulky a upravit response

apiary.apib, src/Keboola/StorageApi/Client.php, tests/Backend/CommonPart1/CreateTableTest.php
Main PR: https://github.com/keboola/connection/pull/2411
=> KBC-259 update display name for tables

tests/Common/ComponentsEventsTest.php
https://keboola.atlassian.net/browse/KBC-316
=> KBC-316 Improve robustness of listEvents function

tests/Backend/CommonPart1/BucketsTest.php, tests/Backend/CommonPart1/CreateTableTest.php
https://keboola.atlassian.net/browse/KBC-310
Is testing https://github.com/keboola/connection/pull/2426
=> KBC-310 tests: rename to same name

apiary.apib
Ako sme robili webalize endpoint tak sme ho zabudli pridat do dokumentacie
=> KBC-248 - Add webalize endpoint to apiary.apib

apiary.apib, tests/Backend/CommonPart1/BucketsTest.php
https://keboola.atlassian.net/browse/KBC-344
Tests for https://github.com/keboola/connection/pull/2435
=> KBC-344 add direct access fields to bucket

tests/Backend/CommonPart1/CreateTableTest.php, tests/Backend/Synapse/CreateTableTest.php
Jira Story https://keboola.atlassian.net/browse/KBC-374
main PR: https://github.com/keboola/connection/pull/2449
=> KBC-374 Add testing create new table with name of existing displayName

Dockerfile, composer.json, phpunit.xml.dist, tests/Backend/Synapse/WorkspacesTest.php, tests/Backend/Workspaces/Backend/SynapseWorkspaceBackend.php, tests/Backend/Workspaces/Backend/WorkspaceBackendFactory.php, tests/Backend/Workspaces/WorkspacesTest.php, tests/Backend/Workspaces/WorkspacesTestCase.php
JIRA: https://keboola.atlassian.net/browse/KBC-307
JIRA: https://keboola.atlassian.net/browse/KBC-308
KBC: https://github.com/keboola/connection/pull/2453
=> [Synapse] KBC-307 Workspace

src/Keboola/StorageApi/DirectAccess.php, tests/Backend/Redshift/DirectAccessTest.php, tests/Backend/Snowflake/DirectAccessTest.php
Main PR: https://github.com/keboola/connection/pull/2440
Jira Story: https://keboola.atlassian.net/browse/KBC-340
=> KBC-340 Add create credentials for direct access + tests

src/Keboola/StorageApi/DirectAccess.php, tests/Backend/Snowflake/DirectAccessTest.php
Jira story: https://keboola.atlassian.net/browse/KBC-342
Main PR: https://github.com/keboola/connection/pull/2443
=> KBC-342 reset pass for direct access

apiary.apib, tests/Common/TokensTest.php
JIRA story: https://keboola.atlassian.net/browse/KBC-377
Main PR: https://github.com/keboola/connection/pull/2461
=> KBC-377 Add new permission canUseDirectAccess

tests/Backend/Snowflake/DirectAccessTest.php
https://github.com/keboola/connection/pull/2483
=> KBC-377 change error code

phpunit.xml.dist
JIRA: https://keboola.atlassian.net/browse/KBC-296
KBC: https://github.com/keboola/connection/pull/2496
=> [Synapse] KBC-296 deleteTableRows

tests/Backend/CommonPart1/BucketsTest.php, tests/StorageApiTestCase.php
https://keboola.atlassian.net/browse/KBC-346
Tests for https://github.com/keboola/connection/pull/2495
=> KBC-346 refactor drop bucket

tests/Backend/CommonPart1/BucketsTest.php
https://keboola.atlassian.net/browse/KBC-370
Code: https://github.com/keboola/connection/pull/2514
=> KBC-370 check that proper error message is displayed

apiary.apib, src/Keboola/StorageApi/Client.php, tests/Backend/CommonPart1/BucketsTest.php
Main PR: https://github.com/keboola/connection/pull/2503
=> KBC-346 Add async parameter for delete bucket + tests

src/Keboola/StorageApi/Client.php, src/Keboola/StorageApi/DirectAccess.php, tests/Backend/Snowflake/DirectAccessTest.php
Jira Story: https://keboola.atlassian.net/browse/KBC-446
=> KBC-446 move api calls for da to class

tests/Backend/Snowflake/DirectAccessTest.php
Main PR:https://github.com/keboola/connection/pull/2520
Jira Story: https://keboola.atlassian.net/browse/KBC-444
=> KBC-444 set default namespace for da credentials

phpunit.xml.dist, src/Keboola/StorageApi/Client.php, tests/Backend/CommonPart2/SlicedImportsTest.php, tests/Backend/Export/ExportParamsTest.php, tests/Backend/Snowflake/TimestampTest.php
Nastavil jsem testsuite přesně jako tomá Snowflake + S3
Upravil jsem testy na pár místech aby místo přístupu k S3 používaly metody pro download/upload přimo z klienta.
Tam kde se testují nějaký chybový stavy (neexistující soubor, oprávnění pro přístup k S3) jsem samé dopsal pro ABS
=> testsuite for snowflake + abs backend combination

apiary.apib
https://keboola.atlassian.net/browse/KBC-456
=> KBC-456 Fix reported semantic violations where possible

src/Keboola/StorageApi/Client.php, src/Keboola/StorageApi/DirectAccess.php, tests/Backend/Snowflake/DirectAccessTest.php, tests/StorageApiTestCase.php
https://keboola.atlassian.net/browse/KBC-346
=> KBC-346 da enable

apiary.apib, src/Keboola/StorageApi/Options/BucketUpdateOptions.php, tests/Backend/CommonPart1/BucketsTest.php, tests/Backend/Snowflake/DirectAccessTest.php
Jira Story: https://github.com/keboola/connection/pull/2527
Main PR: https://github.com/keboola/connection/pull/2527
=> KBC-441 Test async bucket update

tests/Backend/Snowflake/DirectAccessTest.php
https://keboola.atlassian.net/browse/KBC-485
Code https://github.com/keboola/connection/pull/2532
=> KBC-485 Test create alias table and enable DA

tests/Backend/Snowflake/DirectAccessTest.php
Jira story: https://keboola.atlassian.net/browse/KBC-378
Main PR: https://github.com/keboola/connection/pull/2526
=> KBC-378 Test enable direct access for linked bucket

tests/Backend/Snowflake/DirectAccessTest.php
Main PR: https://github.com/keboola/connection/pull/2563
=> Change name of bucket and some fix

tests/Backend/Mixed/SharingToSpecificProjectsTest.php, tests/Backend/Mixed/SharingToSpecificUsersTest.php, tests/Backend/Mixed/StorageApiSharingTestCase.php
Main PR: https://keboola.atlassian.net/browse/KBC-516
=> KBC-516 Improve sharing test

apiary.apib, tests/Backend/Snowflake/DirectAccessTest.php
https://github.com/keboola/storage-api-php-client/pull/395
Connection PR: https://github.com/keboola/connection/pull/2565
=> KBC-340 documentation for direct access

src/Keboola/StorageApi/Client.php, tests/Backend/CommonPart1/CreateTableTest.php
Code: https://github.com/keboola/connection/pull/2560
https://keboola.atlassian.net/browse/KBC-523
=> KBC-523 synthetic primary key prep

composer.json
For new components allowed latest symfony packages
=> allow new symfony packages

src/Keboola/StorageApi/Client.php, tests/Backend/CommonPart2/SimpleAliasTest.php
KBC: https://github.com/keboola/connection/pull/2577
=> KBC-520 drop tableUnlink

apiary.apib, tests/Common/TokensTest.php
Reverts keboola/storage-api-php-client#436
=> Revert "test: project role of admin tokens"

apiary.apib, src/Keboola/StorageApi/Client.php, tests/Backend/Snowflake/DirectAccessTest.php
Main PR: https://github.com/keboola/connection/pull/2597
=> KBC-352 Update table (update displayName with DA enabled) 

tests/Backend/Mixed/SharingTest.php, tests/Backend/Snowflake/DirectAccessTest.php
Main PR: https://github.com/keboola/connection/pull/2590
=> KBC-593 - fix display name linked bucket

tests/Backend/Workspaces/MetadataFromRedshiftWorkspaceTest.php, tests/Backend/Workspaces/MetadataFromSnowflakeWorkspaceTest.php, tests/Backend/Workspaces/MetadataFromSynapseWorkspaceTest.php
Main PR: https://github.com/keboola/connection/pull/2608
=> KBC-547 Test automatic datatype updated length only upward

tests/Backend/Snowflake/DirectAccessTest.php
Main PR: https://github.com/keboola/connection/pull/2600
=> KBC-592 Test add column to table when DA is enabled

tests/Backend/Snowflake/DirectAccessTest.php
Main PR: https://github.com/keboola/connection/pull/2627
- test be not able to create new column using writeTable
=> Add test create new column using writeTableAsync

tests/Backend/Snowflake/DirectAccessTest.php
Main PR: https://github.com/keboola/connection/pull/2628
=> KBC-353 remove column when da is enabled

tests/Backend/Workspaces/MetadataFromRedshiftWorkspaceTest.php, tests/Backend/Workspaces/MetadataFromSnowflakeWorkspaceTest.php, tests/Backend/Workspaces/MetadataFromSynapseWorkspaceTest.php
Main PR: https://github.com/keboola/connection/pull/2629
=> KBC-641 automatic datatypes dont change base type

apiary.apib, src/Keboola/StorageApi/Client.php, tests/Backend/Mixed/SharingTest.php
https://keboola.atlassian.net/browse/KBC-599
Code: https://github.com/keboola/connection/pull/2614
=> KBC-599 Vytvořit sync forceUnlink api call

apiary.apib, src/Keboola/StorageApi/Client.php, tests/Backend/Mixed/SharingTest.php, tests/Backend/Snowflake/DirectAccessTest.php
Main PR: https://github.com/keboola/connection/pull/2643
=> KBC-600 async force unlink

apiary.apib, tests/Common/IndexTest.php
Main PR: https://keboola.atlassian.net/browse/KBC-652
=> KBC-652 add stack features to response

apiary.apib, tests/Common/IndexTest.php
Reverts keboola/storage-api-php-client#461
=> Revert "KBC-652 add stack features to response"

src/Keboola/StorageApi/Client.php, src/Keboola/StorageApi/ProcessPolyfill.php, src/Keboola/StorageApi/TableExporter.php, tests/Backend/CommonPart1/TableExporterTest.php, tests/Common/ComponentsTest.php, tests/Common/ConfigurationRowTest.php
Original issue: https://github.com/keboola/storage-api-php-client/pull/437#issuecomment-664359634
=> KBC-662 add ProcessPolyfill for PHP 7.2 compatibility

apiary.apib, src/Keboola/StorageApi/Options/ListFilesOptions.php
KBC: https://github.com/keboola/connection/pull/2001
JIRA: https://keboola.atlassian.net/browse/KBC-161
=> KBC-161 File expiration in ListFiles response

apiary.apib, tests/Common/IndexTest.php
Reverts keboola/storage-api-php-client#463
=> Revert "Revert "KBC-652 add stack features to response""

tests/Common/TokensTest.php
https://keboola.atlassian.net/browse/KBC-585
Code: https://github.com/keboola/connection/pull/2605
=> KBC-585 U master tokenu se v response (list, detail) nevrací token string

tests/Common/TokensTest.php
https://keboola.atlassian.net/browse/KBC-585
=> KBC-585 REVERT

tests/Common/ComponentsTest.php
Main PR: https://github.com/keboola/connection/pull/2660
=> KBC-670 Change testing validation

tests/Backend/CommonPart1/DataPreviewLimitsTest.php
JIRA: KBC-654
KBC: https://github.com/keboola/connection/pull/2699
=> KBC-654 add DataPreviewLimitsTest::testSimplePreview to check preview data

tests/Backend/CommonPart1/DataPreviewLimitsTest.php
https://travis-ci.com/github/keboola/connection/jobs/379802494#L5366
=> [FIX] skip rs backend for DataPreviewLimitsTest::testSimplePreview

tests/Common/TokensTest.php
KBC-639
Code: https://github.com/keboola/connection/pull/2701
=> KBC-639 Skrytí master tokenu v response

apiary.apib, docker-compose.yml, src/Keboola/StorageApi/DevBranches.php, tests/Common/DevBranchesTest.php, tests/Helpers/ClientsProvider.php, tests/StorageApiTestCase.php
https://keboola.atlassian.net/browse/KBC-666
Code: https://github.com/keboola/connection/pull/2677
=> KBC-666 Endpoint create dev branch

apiary.apib
=> KBC-825 Opravit dokumentaci pro create branch

apiary.apib, src/Keboola/StorageApi/DevBranches.php, tests/Common/DevBranchesTest.php
KBC-668
Code: https://github.com/keboola/connection/pull/2702
=> KBC-668 Endpoint delete dev branch

tests/Backend/CommonPart1/ImportExportCommonTest.php, tests/Backend/Workspaces/WorkspacesUnloadTest.php
Main PR: https://github.com/keboola/connection/pull/2727
=> KBC-372 Add testing column name case mismatch

apiary.apib, phpunit.xml.dist, src/Keboola/StorageApi/DevBranches.php, tests/Common/DevBranchesTest.php
Code: https://github.com/keboola/connection/pull/2724
KBC-669
=> KBC-669 Endpoint list dev branches

tests/ClientTestCase.php
PT: https://travis-ci.com/github/keboola/connection/jobs/390334905#L4298
=> fix case for invalid token

apiary.apib, tests/Common/DevBranchesTest.php
Main PR: https://github.com/keboola/connection/pull/2740
Jira story: https://keboola.atlassian.net/browse/KBC-852
Pridavam test na to ze som pridal do response `isDefault` a upravil som este par veci v dokumentacii
=> KBC-852 create main branch on project created

apiary.apib, tests/Backend/Snowflake/CloneIntoWorkspaceTest.php
KBC: https://github.com/keboola/connection/pull/2750
JIRA: https://keboola.atlassian.net/browse/KBC-858
=> KBC-858 Workspace load clone overwrite

apiary.apib, tests/Backend/Workspaces/WorkspacesLoadTest.php
JIRA: KBC-859
KBC: https://github.com/keboola/connection/pull/2751
=> KBC-859 Workspace load

phpunit.xml.dist
KBC: https://github.com/keboola/connection/pull/2738
JIRA: KBC-802
=> KBC-802 Managed identity

apiary.apib, tests/Common/DevBranchesTest.php
KBC-866
Code: https://github.com/keboola/connection/pull/2758
=> KBC-866 Add "creatorToken" to branches

tests/ClientTestCase.php, tests/Common/EventsTest.php
JIRA: KBC-678 
KBC: https://github.com/keboola/connection/pull/2775
=> KBC-678 test example not implemented storage branch route

tests/Common/DevBranchesTest.php
KBC: https://github.com/keboola/connection/pull/2773
JIRA: KBC-867
=> KBC-867 change delete branch test output

apiary.apib, tests/Common/TokensTest.php
Reverts keboola/storage-api-php-client#441
=> test: project role of admin tokens

phpunit.xml.dist, tests/Backend/Snowflake/FulltextSearchTest.php, tests/Backend/Snowflake/TableExportTest.php, tests/Backend/Snowflake/TimeTravelTest.php, tests/Backend/Snowflake/WhereFilterTest.php
Common Tests:
- S3Uploader
- Downloader
- AwsFileTest
Moved into parates suite.
Some of `tests/Backend/Snowflake` moved to paratest suite for Snowflake + S3 backend and Snowflake + ABS backend
=> paratest - Backend/Snowflake + Common tests

phpunit.xml.dist
Fixes : https://github.com/keboola/storage-api-php-client/pull/499
Bylo tam tipo v nazvu souboru v test suite
=> tests: common suite - fixup testcase filename

src/Keboola/StorageApi/BranchAwareClient.php, src/Keboola/StorageApi/Client.php, src/Keboola/StorageApi/Components.php, src/Keboola/StorageApi/DevBranches.php, src/Keboola/StorageApi/DirectAccess.php, src/Keboola/StorageApi/Metadata.php, src/Keboola/StorageApi/Workspaces.php, tests/Backend/CommonPart1/CreateTableTest.php, tests/Backend/CommonPart1/ImportExportCommonTest.php, tests/Backend/CommonPart1/LegacyIndexedColumnsTest.php, tests/Backend/CommonPart2/MetricsTest.php, tests/Backend/Redshift/DedupeTest.php, tests/Backend/Redshift/OptimizeTest.php, tests/Backend/Snowflake/TableExportTest.php, tests/Backend/Snowflake/TimestampTest.php, tests/Backend/Workspaces/SynapseWorkspacesUnloadTest.php, tests/Backend/Workspaces/WorkspacesUnloadTest.php, tests/ClientTestCase.php, tests/Common/ComponentsTest.php, tests/Common/GetToFileTest.php, tests/File/CommonFileTest.php
Jira Story: https://keboola.atlassian.net/browse/KBC-953
=> KBC-953 Add support for branches part 1

apiary.apib, tests/Common/BranchComponentTest.php
Main PR: https://github.com/keboola/connection/pull/2843
=> KBC-682 branch support for create configuration

apiary.apib, tests/Common/BranchComponentTest.php
Main PR: https://github.com/keboola/connection/pull/2845
=> KBC-688 branch support update configuratio

tests/Common/BranchComponentTest.php
KBC-1024
Code: https://github.com/keboola/connection/pull/2851
=> KBC-1024 Při vytvoření dev branch se vygenerují kopie konfigurací

tests/Common/BranchComponentTest.php
Main PR: https://github.com/keboola/connection/pull/2859
=> KBC-697 - Add test Component Row support development branches

apiary.apib, src/Keboola/StorageApi/Downloader/DownloaderFactory.php, tests/Backend/FileWorkspace/Backend/Abs.php, tests/Backend/FileWorkspace/WorkspacesTest.php, tests/Backend/Workspaces/WorkspacesTest.php
JIRA: KBC-1031
KBC: https://github.com/keboola/connection/pull/2863
přidal sem ještě RetryMiddlewareFactory k ABS
=> KBC-1031 file workspace password reset

tests/Common/DevBranchesTest.php
PR: https://github.com/keboola/connection/pull/2858
=> DevBranchesTest test restrictions

apiary.apib, tests/Common/BranchComponentTest.php
Main PR: https://github.com/keboola/connection/pull/2877
=> KBC-1070: Add testing list components for dev branch

apiary.apib, tests/Common/BranchComponentTest.php
Main PR: https://github.com/keboola/connection/pull/2869
=> KBC-1057 create config rows for dev branch part 2

apiary.apib, phpunit.xml.dist, tests/Backend/FileWorkspace/Backend/Abs.php, tests/Backend/FileWorkspace/FileWorkspaceTestCase.php, tests/Backend/FileWorkspace/WorkspacesLoadTest.php, tests/Backend/FileWorkspace/WorkspacesTest.php
JIRA: KBC-1032
KBC: https://github.com/keboola/connection/pull/2872
=> KBC-1032 File workspace load

src/Keboola/StorageApi/Client.php, src/Keboola/StorageApi/Options/IndexOptions.php, tests/Common/IndexTest.php
KBC-1084
Code: https://github.com/keboola/connection/pull/2883
=> KBC-1084 Add option to exclude components from stack info

src/Keboola/StorageApi/HandlerStack.php
Jira story: https://keboola.atlassian.net/browse/KBC-1096
=> KBC-1096: Client update - Don't do retry if server returns 501 not implemented

apiary.apib
=> KBC-1084 Add option to exclude components from stack info 

tests/Common/BranchComponentTest.php
Jira Story: https://keboola.atlassian.net/browse/KBC-1059
=> KBC-1059: Add test ConfigRow cannot be deleted in dev branch

apiary.apib, src/Keboola/StorageApi/Components.php, src/Keboola/StorageApi/Options/Components/ConfigurationState.php, tests/Common/BranchComponentTest.php, tests/Common/ComponentsTest.php
PR: https://github.com/keboola/connection/pull/2886
=> endpoint for configuration state update

apiary.apib, tests/Common/BranchComponentTest.php
Main PR: https://github.com/keboola/connection/pull/2881
=> KBC-1056: Add test for update configRow

src/Keboola/StorageApi/Client.php, src/Keboola/StorageApi/Downloader/BlobClientFactory.php, src/Keboola/StorageApi/Downloader/BlobStorageRetryMiddleware.php, src/Keboola/StorageApi/Downloader/DownloaderFactory.php, tests/Backend/CommonPart2/SlicedImportsTest.php, tests/Backend/Export/ExportParamsTest.php
přidaný RetryMiddleware všude kde vytváříme blob client
=> KBC-1058 ABS retry

tests/Backend/MixedSnowflakeSynapse/SharingTest.php
PR: https://github.com/keboola/connection/pull/2911
=> tests: MixedSnowflakeSynapse/SharingTest check workspace load type

apiary.apib, tests/Backend/FileWorkspace/Backend/Abs.php, tests/Backend/FileWorkspace/WorkspacesLoadTest.php
JIRA: KBC-1098
KBC: https://github.com/keboola/connection/pull/2897
=> KBC-1098 File IM workspace load

tests/Common/BranchComponentTest.php
Main PR: https://github.com/keboola/connection/pull/2912
=> KBC-1120: Version 0 for copy of config and config row

apiary.apib, src/Keboola/StorageApi/Components.php, src/Keboola/StorageApi/Options/Components/ConfigurationRowState.php, tests/Common/BranchComponentTest.php, tests/Common/ComponentsTest.php
PR: https://github.com/keboola/connection/pull/2906
=> endpoint for row state update

phpunit.xml.dist, tests/Backend/FileWorkspace/ComponentsWorkspacesTest.php
JIRA: KBC-1132
KBC: https://github.com/keboola/connection/pull/2922
=> KBC-1132 add FileWorkspace ComponentsWorkspacesTest

.github/PULL_REQUEST_TEMPLATE.md
Changes:
- Adding PR template
---
Kazdy novy PR potom bude mat checklist, co treba spravit
=> Init PR template

apiary.apib, src/Keboola/StorageApi/Components.php, tests/Common/ComponentsTest.php
Jira: https://keboola.atlassian.net/browse/KBC-1128
Before asking for review:
Changes:
- Add method to get component detail and test
---
Pridavam metodu na ziskanie detailu komponenty. Zatial bez konfiguracii, preto si tam explicitne kontrolujem, ze v response nie je `configurations` item.
=> Add method to get component detail and test

apiary.apib, tests/Common/BranchEventsTest.php
Main PR: https://github.com/keboola/connection/pull/2899
=> KBC-1083: Add test for branch aware list events

tests/Common/BranchComponentTest.php, tests/Common/ComponentsTest.php, tests/Common/ConfigurationRowTest.php
Main PR: https://github.com/keboola/connection/pull/2916
=> Test updating row changeDescription update changeDescription config

tests/Common/BranchComponentTest.php, tests/Common/ComponentsTest.php
Reverts keboola/storage-api-php-client#533
=> Revert "Test updating row changeDescription update changeDescription config"

apiary.apib, tests/Common/BranchEventsTest.php, tests/Common/EventsTest.php
Jira: KBC-1181
Main PR: https://github.com/keboola/connection/pull/2920
---
=> KBC-1108 branch aware event detail

tests/Common/BranchComponentTest.php
Jira: KBC-1143
Main PR: https://github.com/keboola/connection/pull/2941
---
=> Test change description behavior in branch

phpunit.xml.dist
=> Synapse part3 suite

phpunit.xml.dist
Ještě to není úplně optimální (ani nebude, ale toto sa može vrátit)
=> Synapse suite move ExportParamsTest back to part2

tests/Common/BranchComponentTest.php
=> KBC-1025 Assert that configuration cannot be deleteed in branch

phpunit.xml.dist
Jira: KBC-1102
Potrebujem aby sa este eventy testovali na azure kde je ES v7
Main PR: https://github.com/keboola/connection/pull/2964
---
=> Add new test suite azure-common

tests/ClientTestCase.php
=> KBC-1124 Switch project and token ID

phpunit.xml.dist, tests/Backend/CommonPart2/MetricsTest.php, tests/Backend/CommonPart2/SimpleAliasTest.php, tests/Backend/CommonPart2/SlicedImportsTest.php, tests/Backend/CommonPart2/SlicedImportsWithSlicedUploadsTest.php, tests/Backend/CommonPart2/SnapshottingTest.php, tests/Backend/CommonPart2/SystemColumnsTest.php
Jira: KBC-1181
Main PR: https://github.com/keboola/connection/pull/2985
---
Otagoval som to a nechal ostestovat https://travis-ci.com/github/keboola/connection/jobs/469266677, popadali tam nejake synapse testy ale `paratest-backend-snowflake-part-1` suita presla 
Zabudol som to povodne pridat este do `paratest-backend-snowflake-abs-part-1` suity ale to predpokladam ze je v pohode
=> Run ComminPart2 paralel

tests/Backend/CommonPart2/SimpleAliasTest.php, tests/StorageApiTestCase.php
=> fix paratest safe export file path

apiary.apib, src/Keboola/StorageApi/DevBranches.php, tests/Common/DevBranchesTest.php
Jira: KBC-1194
Code: https://github.com/keboola/connection/pull/2990
---
=> KBC-1194 Add description to branch create API call

tests/Backend/Snowflake/CloneIntoWorkspaceTest.php, tests/Backend/Workspaces/WorkspacesSnowflakeTest.php
=> KBC-1208 update expected snflk table sizes after changes on snfkl side

apiary.apib, src/Keboola/StorageApi/DevBranches.php, tests/Common/DevBranchesTest.php
Jira: KBC-1195
Depends on #557
Code: https://github.com/keboola/connection/pull/3003
---
=> KBC-1195 add update branch api call

tests/Backend/Snowflake/CloneIntoWorkspaceTest.php
Jira: KBC-1072
Main PR: https://github.com/keboola/connection/pull/2961
---
=> Improve test `testTableAlreadyExistsAndOverwrite` try third load  with linked bucket

docker-compose.yml, phpstan.neon, tests/Common/BranchComponentTest.php, tests/bootstrap.php
Jira: KBC-1197
Main PR: https://github.com/keboola/connection/pull/2997
---
=> Test creating new version for config

tests/Common/BranchComponentTest.php
Jira: KBC-1199
Jira story: https://keboola.atlassian.net/browse/KBC-1199
Main PR: https://github.com/keboola/connection/pull/2998
---
=> Kbc 1199 update config create new version in new table

phpunit.xml.dist, tests/Backend/FileWorkspace/WorkspacesLoadTest.php
Jira: KBC-1173
KBC: https://github.com/keboola/connection/pull/3010
---
=> KBC-1173 Load multiple file uploads into same destination

tests/Backend/FileWorkspace/WorkspacesLoadTest.php
Jira: KBC-1172
KBC: https://github.com/keboola/connection/pull/3012
---
=> KBC-1172 add file workspace load test for invalid destinations

apiary.apib, src/Keboola/StorageApi/Components.php, tests/Common/BranchComponentTest.php
Jira: KBC-1192 
Code: https://github.com/keboola/connection/pull/3011
---
=> KBC-1192 replace configuration in branch

apiary.apib
=> KBC-1192 Replace configuration in branch with version from main

phpunit.xml.dist, tests/Backend/Mixed/SharingTest.php, tests/Backend/Mixed/StorageApiSharingTestCase.php, tests/Backend/MixedSnowflakeSynapse/SharingTest.php, tests/Backend/Snowflake/TimestampTest.php, tests/Backend/WorkspaceConnectionTrait.php, tests/Backend/Workspaces/Backend/RedshiftWorkspaceBackend.php, tests/Backend/Workspaces/Backend/SnowflakeWorkspaceBackend.php, tests/Backend/Workspaces/Backend/SynapseWorkspaceBackend.php, tests/Backend/Workspaces/LegacyWorkspacesLoadTest.php, tests/Backend/Workspaces/MetadataFromRedshiftWorkspaceTest.php, tests/Backend/Workspaces/MetadataFromSnowflakeWorkspaceTest.php, tests/Backend/Workspaces/MetadataFromSynapseWorkspaceTest.php, tests/Backend/Workspaces/ParallelWorkspacesTestCase.php, tests/Backend/Workspaces/SynapseWorkspacesUnloadTest.php, tests/Backend/Workspaces/WorkspacesLoadTest.php, tests/Backend/Workspaces/WorkspacesRedshiftTest.php, tests/Backend/Workspaces/WorkspacesSnowflakeTest.php, tests/Backend/Workspaces/WorkspacesTest.php, tests/Backend/Workspaces/WorkspacesTestCase.php, tests/Backend/Workspaces/WorkspacesUnloadTest.php
KBC https://github.com/keboola/connection/pull/3001
---
V API se nic nemění, je jen paralelizovaná část testů pro Workspaces
=> paratest: Workspaces part1

phpunit.xml.dist, tests/Backend/Snowflake/TimestampTest.php, tests/Backend/Workspaces/LegacyWorkspacesLoadTest.php, tests/Backend/Workspaces/LegacyWorkspacesRedshiftTest.php, tests/Backend/Workspaces/LegacyWorkspacesSnowflakeTest.php, tests/Backend/Workspaces/LegacyWorkspacesSynapseTest.php, tests/Backend/Workspaces/MetadataFromRedshiftWorkspaceTest.php, tests/Backend/Workspaces/MetadataFromSynapseWorkspaceTest.php, tests/Backend/Workspaces/ParallelWorkspacesTestCase.php, tests/Backend/Workspaces/ReadOnlyUserTest.php, tests/Backend/Workspaces/SynapseWorkspacesUnloadTest.php, tests/Backend/Workspaces/WorkspacesLoadTest.php, tests/Backend/Workspaces/WorkspacesRedshiftTest.php, tests/Backend/Workspaces/WorkspacesRenameLoadTest.php, tests/Backend/Workspaces/WorkspacesSynapseTest.php, tests/Backend/Workspaces/WorkspacesTest.php, tests/Backend/Workspaces/WorkspacesUnloadTest.php
PR: https://github.com/keboola/connection/pull/3014
---
V api se nic nemeni, jen jsou pralelizovane test pro wokrspaces
=> paratest: Workspaces part2

apiary.apib, composer.json, src/Keboola/StorageApi/Client.php, tests/Backend/Synapse/CreateTableTest.php, tests/Backend/Workspaces/Backend/SynapseWorkspaceBackend.php, tests/Backend/Workspaces/WorkspacesSynapseTest.php
Jira: KBC-1254
KBC: https://github.com/keboola/connection/pull/3035
---
- No BC
- New option in craete table async, distributionKey
=> KBC-1254 Synapse distributionKey

apiary.apib, tests/Common/ComponentsTest.php
PR: https://github.com/keboola/connection/pull/3037
---
BC break by to být neměl
=> tests: list components

apiary.apib
Jira: KBC-1243
Main PR: https://github.com/keboola/connection/pull/3052
Fixing API docs on data-preview endpoint
=> KBC-1243 update apiary data preview

apiary.apib
Jira: KBC-921
just found some small issues on the endpoint.
=> KBC-921 Fix list of dataTypes for data-preview

tests/Common/BranchAwareClientTest.php
Jira: https://keboola.atlassian.net/browse/KBC-1274
Uprave v KBC neni
---
=> tests: branch aware client with default branch

tests/Backend/Synapse/CreateTableTest.php, tests/_data/languages.crlf.csv
Jira: KBC-1005
KBC: https://github.com/keboola/connection/pull/3091
---
=> KBC-1005 - add synapse CreateTableWithCrlfLineEndings test

apiary.apib, tests/Common/BranchComponentTest.php
Jira: KBC-1337
KBC: https://github.com/keboola/connection/pull/3095
---
=> KBC-1337 add configuration row version rollback tests

tests/Backend/CommonPart2/SimpleAliasTest.php, tests/Backend/Mixed/SharingTest.php, tests/Backend/Snowflake/DirectAccessTest.php
KBC PR: https://github.com/keboola/connection/pull/3088
---
=> tests: restricted actions for dev/branch buckets/tables

tests/Backend/MixedSnowflakeSynapse/SharingTest.php
Jira: KBC-1364
KBC: https://github.com/keboola/connection/pull/3106
---
=> KBC-1364 Update SharingTest for synapse table distribution and distributionKey

apiary.apib, tests/Common/BranchComponentTest.php
Jira: KBC-1336 
KBC: https://github.com/keboola/connection/pull/3102
---
=> KBC-1336 Configuration rollback in dev branch

apiary.apib, phpunit.xml.dist, src/Keboola/StorageApi/Metadata.php, tests/Backend/CommonPart2/SimpleAliasTest.php, tests/Backend/Mixed/SharingTest.php, tests/Backend/Mixed/StorageApiSharingTestCase.php, tests/Backend/Snowflake/DirectAccessTest.php, tests/Common/BranchBucketsTest.php, tests/StorageApiTestCase.php
=> KBC-1341 delete dev bucket when delete dev branch

src/Keboola/StorageApi/Client.php, tests/Common/GetServiceUrlTest.php
Jira: https://keboola.atlassian.net/browse/PS-1510
No BC break
=> PS-1510 Add Client::getServiceUrl method

tests/Common/BranchComponentTest.php
Jira: KBC-1375
Test `idBranch` in event after rollback
=> KBC-1375 Check that idBranch is present in event after rollback

tests/Common/TokensTest.php
Jira: KBC-1368
Add tests for token type validation
=> KBC-1368 Add tests for token type validation

tests/Common/TokensTest.php
Jira: https://keboola.atlassian.net/browse/KBC-1353
---
Wait before token refresh to prevent test failures
=> tests fixup: wait before token refresh

README.md, docker-compose.yml, phpstan.neon, set-env.redshift.template.sh, tests/Backend/Redshift/CommonTest.php, tests/Backend/Workspaces/WorkspacesRedshiftTest.php, tests/StorageApiTestCase.php, tests/bootstrap.php
=> KBC-1380 Redshift nodes

apiary.apib, composer.json, tests/Backend/MixedSnowflakeSynapse/SharingTest.php, tests/Backend/Workspaces/Backend/SynapseWorkspaceBackend.php, tests/Backend/Workspaces/WorkspacesSynapseTest.php
Jira: KBC-1372
KBC:  https://github.com/keboola/connection/pull/3121
---
=> KBC-1372 add WorkspacesSynapseTest::testTableLoadAsView

tests/Backend/Snowflake/CloneIntoWorkspaceTest.php, tests/Backend/Workspaces/WorkspacesLoadTest.php
Jira: KBC-1464
Connection : https://github.com/keboola/connection/pull/3166
=> KBC-1464 Add tests for wrong input when loading to workspaces

tests/Backend/Snowflake/CloneIntoWorkspaceTest.php, tests/Backend/Workspaces/WorkspacesLoadTest.php
Fix for broken build in SAPI
Jira: https://keboola.atlassian.net/browse/KBC-1464
Connection: https://github.com/keboola/connection/pull/3191
=> KBC-1464 Add assert for stringcode when testing workspace load

composer.json, tests/Backend/WorkspaceConnectionTrait.php, tests/Backend/WorkspaceCredentialsAssertTrait.php, tests/Backend/Workspaces/WorkspacesTest.php, tests/Common/DevBranchesTest.php
Jira: KBC-1455
Connection: https://github.com/keboola/connection/pull/3185
A test which creates branch, then a workspace and then it deletes the branch. The workspace should be also deleted but it cannot be tested/validated
=> KBC-1455 Delete branch workspaces when deleting branch

apiary.apib, phpunit.xml.dist, src/Keboola/StorageApi/BranchAwareClient.php, tests/Backend/Workspaces/BranchComponentsWorkspacesTest.php, tests/Backend/Workspaces/ParallelWorkspacesTestCase.php, tests/Backend/Workspaces/WorkspacesTest.php, tests/Common/BranchComponentTest.php, tests/Common/BranchWorkspacesTest.php, tests/Common/DevBranchesTest.php
Jira: https://keboola.atlassian.net/browse/KBC-1478
KBC: https://github.com/keboola/connection/pull/3188
---
=> Allow branch workspace

src/Keboola/StorageApi/ABSUploader.php, src/Keboola/StorageApi/ABSUploader/PromiseHelper.php, src/Keboola/StorageApi/Client.php, tests/File/AzureFileTest.php
=> KBC-1509 Storage API PHP client - ABS sliced files - use parallel upload

src/Keboola/StorageApi/BranchAwareClient.php, tests/Common/BranchAwareClientTest.php
Jira: KBC-non-existent
https://keboola.slack.com/archives/CFVRE56UA/p1620832824289600
Not a bc-break, because it doesn't work anyway, just ends with a weird message.
---
=> don't allow empty branch in ctor

tests/Backend/FileWorkspace/WorkspacesLoadTest.php, tests/_data/languages.more-rows-no-duplicates.csv
Jira: https://keboola.atlassian.net/browse/KBC-1510
Main PR: https://github.com/keboola/connection/pull/3206
Spustal som vsetky testy pre `\Keboola\Test\Backend\FileWorkspace\WorkspacesLoadTest`
---
=> testLoadWorkspaceWithOverwrite

src/Keboola/StorageApi/Metadata.php, tests/Backend/Workspaces/MetadataFromRedshiftWorkspaceTest.php, tests/Backend/Workspaces/MetadataFromSnowflakeWorkspaceTest.php, tests/Backend/Workspaces/MetadataFromSynapseWorkspaceTest.php
=> tests: restrict edit/delete metadata with storage provider

tests/Common/BranchWorkspacesTest.php
Jira: KBC-1517
MainPR: https://github.com/keboola/connection/pull/3212
---
=> KBC-1517: Test branch aware events for workspaces

tests/Common/ComponentsTest.php
Jira: KBC-1493
Connection : https://github.com/keboola/connection/pull/3209
=> KBC-1493 Change test to check if configuration exists in include param

src/Keboola/StorageApi/Client.php, tests/Backend/Synapse/CreateTableTest.php
Jira: KBC-1513
Connection : https://github.com/keboola/connection/pull/3201
**READ FIRST** https://keboola.atlassian.net/browse/KBC-1513?focusedCommentId=30088 
---
=> KBC-1513 create typed table

src/Keboola/StorageApi/ABSUploader.php
=> when uploading slices don't upload all slices at once

src/Keboola/StorageApi/Client.php, tests/Backend/Synapse/CreateTableTest.php
Jira: https://keboola.atlassian.net/browse/KBC-1519
---
=> create table from definition tests

apiary.apib
=> Jirka kbc 1513 create typed table doc

apiary.apib, tests/Backend/Synapse/TableDefinitionOperationsTest.php
Jira: KBC-1515
Connection https://github.com/keboola/connection/pull/3220
add tests on operations of add/drop column; add/drop primary keys; snapshots for typed tables in Synapse
=> KBC-1515 Tests operations on typed table

tests/Backend/Synapse/ImportTypedTableTest.php, tests/_data/tw_accounts.empty.csv
Jira: KBC-1544
KBC: https://github.com/keboola/connection/pull/3221
Based on: #619 
---
=> KBC-1544 typed imports from workspace test

tests/Common/MetadataTest.php
Jira: KBC-1525
Connection: https://github.com/keboola/connection/pull/3224
Add missing tests on Metadata manipulation in tables, columns and buckets
=> KBC-1525 add tests for metadatainput

tests/Backend/Synapse/ImportTypedTableTest.php
Jira: KBC-1546
KBC: https://github.com/keboola/connection/pull/3231
---
=> KBC-1545 test synapse type conversion errors

tests/Backend/Synapse/CreateTableTest.php
Jira: KBC-1541
Connection https://github.com/keboola/connection/pull/3240
test that column definitions are stored in column metadata
=> KBC-1541 Test presence of column metadata for typed columns in synapse

tests/Backend/Synapse/CreateTableTest.php
=> KBC-1570 add CreateTableTest::testCreateTableDefinitionNoPrimaryKey

tests/Backend/Workspaces/WorkspacesTest.php
Jira: https://keboola.atlassian.net/browse/KBC-1576
Uprava testu na veci, ktere historicky chybely. Z pohledu api se nemeni nic.
---
=> WorkspacesTest::testWorkspaceCreate fixup

tests/StorageApiTestCase.php
=> KBC-1607 generateDescriptionForTestObject contains now name of suite

composer.json, tests/Backend/WorkspaceCredentialsAssertTrait.php, tests/Backend/Workspaces/WorkspacesTest.php
=> KBC-1611 retry password reset

Dockerfile
=> Add fallback keyserver to dockerfile

apiary.apib, phpunit.xml.dist, set-env.snowflaeDynamicBackends.template.sh, tests/Backend/Workspaces/ParallelWorkspacesTestCase.php, tests/Backend/Workspaces/SnowflakeDynamicBackendsTest.php, tests/Backend/Workspaces/WorkspacesTest.php, tests/Common/BranchWorkspacesTest.php, tests/StorageApiTestCase.php
Jira: https://keboola.atlassian.net/browse/KBC-1589
---
=> backendSize for workspaces

tests/Common/ConfigurationRowTest.php
=> KBC-1652 Fix brotli error

tests/Common/BranchComponentTest.php
=> KBC-1656 Zistit pricinu padania testov na testingu

tests/Backend/CommonPart2/SnapshottingTest.php
Jira: https://keboola.atlassian.net/browse/KBC-1676
---
=> tests: table and column metadata restore

tests/Backend/CommonPart2/SnapshottingTest.php, tests/Backend/Synapse/SnapshottingTest.php
Jira: https://keboola.atlassian.net/browse/KBC-1676
---
=> tests: restore table having distribution key

phpunit.xml.dist, tests/Backend/Snowflake/CopyIntoWorkspaceTest.php
Jira: KBC-1689
---
Obdobná věc se testuje v `CloneIntoWorkspaceTest::testTableAlreadyExistsAndOverwrite`
=> test: snowflake copy load linked table with overwrite flag

tests/Common/ConfigurationRowTest.php
Jira: https://keboola.atlassian.net/browse/KBC-1749
Main PR: https://github.com/keboola/connection/pull/3345
---
=> Add second config to test if there two rows with the same rowId

tests/Backend/Workspaces/WorkspacesUnloadTest.php
=> KBC-1665 fix workspace unload table error

apiary.apib, tests/Common/BranchComponentTest.php
=> KBC-1721 delete devBranch configuration

apiary.apib, tests/Common/BranchComponentTest.php
=> KBC-1720 delete devBranch configuration row

apiary.apib
=> KBC-1324 apiary docs: add missing limit and offset params

phpunit.xml.dist, tests/Backend/Exasol/BucketsTest.php, tests/StorageApiTestCase.php
KBC: https://github.com/keboola/connection/pull/3332
---
=> Exasol BucketsTest

apiary.apib, tests/Backend/Exasol/CreateTableTest.php, tests/Backend/Exasol/TableDefinitionOperationsTest.php
KBC: https://github.com/keboola/connection/pull/3334
---
=> Exasol table definition

Dockerfile, composer.json, phpunit.xml.dist, tests/Backend/WorkspaceConnectionTrait.php, tests/Backend/WorkspaceCredentialsAssertTrait.php, tests/Backend/Workspaces/Backend/ExasolWorkspaceBackend.php, tests/Backend/Workspaces/Backend/SynapseWorkspaceBackend.php, tests/Backend/Workspaces/Backend/WorkspaceBackendFactory.php, tests/StorageApiTestCase.php
KBC: https://github.com/keboola/connection/pull/3340
---
=> Exasol ws init

phpunit.xml.dist, set-env.exasol.template.sh, tests/Backend/Exasol/Workspace/LegacyWorkspaceLoadTest.php, tests/Backend/Exasol/Workspace/WorkspaceLoadTest.php, tests/Backend/Exasol/Workspace/WorkspacesRenameLoadTest.php, tests/Backend/Exasol/Workspace/WorkspacesUnloadTest.php, tests/Backend/WorkspaceConnectionTrait.php, tests/Backend/Workspaces/Backend/InputMappingConverter.php, tests/Backend/Workspaces/Backend/LegacyInputMappingConverter.php, tests/Backend/Workspaces/Backend/RedshiftWorkspaceBackend.php, tests/Backend/Workspaces/Backend/SnowflakeWorkspaceBackend.php, tests/Backend/Workspaces/Backend/WorkspaceBackend.php, tests/Backend/Workspaces/ExasolWorkspacesUnloadTest.php, tests/Backend/Workspaces/LegacyWorkspacesExasolTest.php, tests/Backend/Workspaces/MetadataFromExasolWorkspaceTest.php, tests/Backend/Workspaces/WorkspacesExasolTest.php, tests/Backend/Workspaces/WorkspacesUnloadTest.php
KBC: https://github.com/keboola/connection/pull/3359
---
=> Exasol ws load

apiary.apib, tests/Backend/Exasol/OrderByTest.php, tests/Backend/Exasol/WhereFilterTest.php
KBC https://github.com/keboola/connection/pull/3362
---
=> Exasol fixes 1

tests/Backend/CommonPart1/AlterTableTest.php
Reverts keboola/storage-api-php-client#660
=> Revert "fix expected columns names after webalize"

tests/Backend/CommonPart1/AlterTableTest.php, tests/Backend/CommonPart1/CreateTableTest.php, tests/_data/languages.column-names-with-underscores.csv
Reverts keboola/storage-api-php-client#658
=> Revert "Tests: column names with underscores"

apiary.apib, tests/Common/BranchComponentTest.php
=> KBC-1723 copy devBranch configuration row

tests/Backend/Workspaces/WorkspacesUnloadTest.php
Jira: KBC-34
KBC: https://github.com/keboola/connection/pull/3377
---
=> KBC-34 testImportFromWorkspaceWithInvalidTableNames tests also tableCreate

apiary.apib, tests/Backend/Workspaces/Backend/InputMappingConverter.php, tests/Backend/Workspaces/WorkspacesLoadTest.php
Jira: KBC-1572
KBC: https://github.com/keboola/connection/pull/3370
---
=> KBC-1572 default type on new IM

tests/Backend/Workspaces/WorkspacesLoadTest.php
=> remove policy name from assert

tests/Backend/Exasol/TableDefinitionOperationsTest.php, tests/Backend/Synapse/CreateTableTest.php
Jira: https://keboola.atlassian.net/browse/KBC-1825
Main PR: https://github.com/keboola/connection/pull/3380
---
=> KBC-1825 fix data preview with numeric column type

apiary.apib, tests/Backend/Exasol/TableDefinitionOperationsTest.php, tests/Backend/Synapse/TableDefinitionOperationsTest.php
Jira: https://keboola.atlassian.net/browse/KBC-1822
MainPR: https://github.com/keboola/connection/pull/3383
---
=> KBC-1822 drop column for typed table

apiary.apib, composer.json, tests/Backend/Synapse/CreateTableTest.php
Jira: KBC-1820
KBC: https://github.com/keboola/connection/pull/3378
---
=> KBC-1820 Synapse index on typed tables

apiary.apib, tests/Common/BranchComponentTest.php
Reverts keboola/storage-api-php-client#672
=> Revert "Revert "KBC-1723 copy devBranch configuration row""

apiary.apib, tests/Common/BranchComponentTest.php
=> KBC-1725 copy devBranch configuration

apiary.apib, tests/Common/BranchEventsTest.php, tests/Common/EventsTest.php
=> KBC-1746 create event for devBranch

apiary.apib, tests/Backend/Exasol/TableDefinitionOperationsTest.php, tests/Backend/Synapse/TableDefinitionOperationsTest.php
Jira: KBC-1824
KBC: https://github.com/keboola/connection/pull/3395
---
=> KBC-1824 Snapshot on typed tables

src/Keboola/StorageApi/TableExporter.php, tests/Backend/CommonPart1/TableExporterTest.php
Jira: https://keboola.atlassian.net/browse/PS-2611
No BC Break: https://keboola.slack.com/archives/CFVRE56UA/p1632139953107400
To be released as `12.5`
=> feat: return jobResults from TableExporter

tests/Common/ConfigurationMetadataTest.php, tests/StorageApiTestCase.php
=> Separete methods

tests/Backend/Workspaces/LegacyWorkspacesRedshiftTest.php, tests/Backend/Workspaces/WorkspacesRedshiftTest.php
Jira: KBC-1971
KBC: https://github.com/keboola/connection/pull/3445
---
https://keboola.slack.com/archives/CFVRE56UA/p1635511152079300?thread_ts=1635509669.075900&cid=CFVRE56UA
=> expect to PK on RS backend to have length 65535

tests/Common/ConfigurationRowTest.php
Jira: KBC-1991
curl call removed and replaced by guzzle
=> KBC-1991 remove curl call and replace it with guzzle

phpstan-baseline.neon, tests/Backend/Synapse/ImportTypedTableTest.php, tests/StorageApiTestCase.php, tests/_data/tw_accounts.expectation.full.csv, tests/_data/tw_accounts.expectation.increment.csv
=> KBC-1973 Synapse typed load behavior changes

phpstan-baseline.neon, src/Keboola/StorageApi/Client.php, tests/Backend/MixedSnowflakeSynapse/SharingTest.php, tests/Backend/Workspaces/Backend/WorkspaceBackend.php
Jira: KBC-1485
KBC: https://github.com/keboola/connection/pull/3455
---
=> KBC-1485 test view load on Synapse

phpstan-baseline.neon, tests/Common/ComponentsEventsTest.php, tests/Common/ComponentsTest.php, tests/Common/ConfigurationRowStateTest.php, tests/Common/ConfigurationRowTest.php
Jira: KBC-1738
MainPr: https://github.com/keboola/connection/pull/3449
---
=> Use update state endpoint instead of updateConf or updateConfRow

tests/Common/ComponentsTest.php, tests/Common/ConfigurationRowsSortOrderTest.php
Jira: KBC-1889
MainPR: https://github.com/keboola/connection/pull/3451
---
=> remove markTestIncomplete for more tests

tests/Common/ComponentsTest.php
v https://github.com/keboola/storage-api-php-client/pull/709 som si nevsimol este Zajcove komentare ked tam bol approve
https://github.com/keboola/storage-api-php-client/pull/709#discussion_r743680812
https://github.com/keboola/storage-api-php-client/pull/709#discussion_r743681017
---
=> delete duplicate setName

apiary.apib
=> Fix incorrectly encoded equal sign

tests/Common/ComponentsEventsTest.php, tests/Common/ConfigurationMetadataTest.php, tests/StorageApiTestCase.php
=> Kbc 1937 use lib for retry

tests/Common/ConfigurationMetadataTest.php, tests/StorageApiTestCase.php
MainPr: https://github.com/keboola/connection/pull/3438
---
=> Roman fix urlcoded parameters

src/Keboola/StorageApi/Downloader/BlobClientFactory.php
=> add timeouts to ABS client

tests/Backend/Workspaces/WorkspacesSnowflakeTest.php
=> update expected metrics.outBytes due to SNFLK change

apiary.apib, src/Keboola/StorageApi/Components.php, src/Keboola/StorageApi/Options/Components/Configuration.php, tests/Common/BranchComponentTest.php, tests/Common/ComponentsTest.php
=> KBC-2180 config isDisabled test

tests/Common/ComponentsTest.php
=> KBC-2212 read only components test - add client provider

apiary.apib
Jira: KBC-2180
Zapomenuty endpoint _Update Development Branch Configuration_ v Apiary dokumentaci.
---
=> KBC-2180 config isDisabled - apiary doc - update configuration

phpstan-baseline.neon, tests/Backend/Workspaces/WorkspacesSynapseTest.php
Jira: KBC-2191
KBC: https://github.com/keboola/connection/pull/3467
---
=> KBC-2191 test view lod with preserve overwrite

tests/Backend/Workspaces/Backend/SnowflakeWorkspaceBackend.php, tests/Backend/Workspaces/WorkspacesLoadTest.php, tests/Backend/Workspaces/WorkspacesSnowflakeTest.php
Jira: KBC-2232
Code: https://github.com/keboola/connection/pull/3492
---
=> KBC-2232 Implement read only storage for project

phpstan-baseline.neon, src/Keboola/StorageApi/Client.php, tests/Backend/Mixed/SharingTest.php, tests/Backend/Mixed/SharingToSpecificProjectsTest.php, tests/Backend/Mixed/SharingToSpecificUsersTest.php, tests/Backend/Mixed/StorageApiSharingTestCase.php
Jira: KBC-2237
Main PR: https://github.com/keboola/connection/pull/3494
---
Testy davam na review, mali by prechadzat potreboval by som ale pomoct s vygenerovanim baseline mne to nejak nefunguje, tak by som to potom otagoval, plus este dopisem dokumentaciu
Testy presli tu https://app.travis-ci.com/github/keboola/connection/jobs/550419805 spadol len exasol
=> Test async share unshare bucket

phpstan-baseline.neon, src/Keboola/StorageApi/Client.php, tests/Backend/Mixed/SharingTest.php, tests/Backend/Mixed/SharingToSpecificProjectsTest.php, tests/Backend/Mixed/SharingToSpecificUsersTest.php, tests/Backend/Mixed/StorageApiSharingTestCase.php
Jira: KBC-$devBranchId
---
apiary https://github.com/keboola/storage-api-php-client/pull/737
=> Kbc 2235 async link bucket

apiary.apib
=> Doc kbc 2237 kbc 2235 async share and link

src/Keboola/StorageApi/Downloader/DownloaderFactory.php
https://keboola.slack.com/archives/CL11GKH6H/p1638954620050200
=> update s3 client timeout

phpstan-baseline.neon, src/Keboola/StorageApi/Client.php, tests/Backend/Workspaces/WorkspacesLoadTest.php
=> KBC-2233 Test accessing shared bucket

phpunit.xml.dist, tests/Common/ComponentsTest.php, tests/Common/EventsTest.php, tests/StorageApiTestCase.php
=> KBC-2249 add test suite temp-devbranch-only

apiary.apib, phpstan-baseline.neon, src/Keboola/StorageApi/Client.php, tests/Backend/Mixed/SharingTest.php, tests/Backend/Workspaces/WorkspacesLoadTest.php, tests/StorageApiTestCase.php
Jira: KBC-2233
Code: https://github.com/keboola/connection/pull/3532
---
=> KBC-2233 fix different sharing types

phpunit.xml.dist, tests/Backend/CommonPart1/BucketsTest.php, tests/Common/BranchEventsTest.php
=> KBC-1884 improve tests for list events

tests/Backend/Workspaces/WorkspacesLoadTest.php
Jira: KBC-2233
Connection: https://github.com/keboola/connection/pull/3536
---
Add test which tests edgecases for RO - unlink/unshare/force unshare
=> KBC-2233 add tests for unlink unshare

tests/Common/BranchComponentTest.php
=> Test if rows has config key

composer.json, tests/Common/BranchComponentTest.php
tests for https://github.com/keboola/connection/pull/3556
=> Roman fix rows version not created

tests/Common/TokensTest.php
Jira: KBC-2342
Connection: https://github.com/keboola/connection/pull/3565
---
=> KBC-2342 return credits as float

apiary.apib, tests/Common/ComponentsTest.php, tests/Common/TokensTest.php
Jira: KBC-2306
Connection: https://github.com/keboola/connection/pull/3570
---
=> Kbc 2306 enable branch endpoints

composer.json, phpstan-baseline.neon, phpstan.neon, tests/Backend/CommonPart1/AlterTableTest.php, tests/Backend/CommonPart1/CreateTableTest.php, tests/Backend/CommonPart1/DataPreviewLimitsTest.php, tests/Backend/CommonPart1/ImportExportCommonTest.php, tests/Backend/CommonPart1/TableExporterTest.php, tests/Backend/CommonPart2/SlicedImportsTest.php, tests/Backend/Exasol/TableDefinitionOperationsTest.php, tests/Backend/Snowflake/DirectAccessTest.php, tests/Backend/Synapse/CreateTableTest.php, tests/Backend/Synapse/TableDefinitionOperationsTest.php, tests/Common/DevBranchesTest.php, tests/Common/FilesLegacyFormUploadsTest.php, tests/Common/IndexTest.php, tests/Common/TokensTest.php
=> add phpstan/phpstan-phpunit

apiary.apib, phpstan-baseline.neon, tests/Common/BranchAwareClientTest.php
Jira: KBC-2307
Connection: https://github.com/keboola/connection/pull/3572
---
=> KBC-2307 test placeholder for default branch

apiary.apib, phpstan-baseline.neon, src/Keboola/StorageApi/Client.php, src/Keboola/StorageApi/Metadata.php, src/Keboola/StorageApi/Options/Metadata/TableMetadataUpdateOptions.php, tests/Common/MetadataTest.php
Jira: KBC-1445
Connection: https://github.com/keboola/connection/pull/3575
---
=> KBC-1445 test bulk create table metadata

apiary.apib, phpstan-baseline.neon, src/Keboola/StorageApi/DevBranchesMetadata.php, tests/Common/BranchMetadataTest.php, tests/Common/ConfigurationMetadataTest.php, tests/Common/SearchComponentsConfigurationsTest.php, tests/Utils/ComponentsConfigurationUtils.php, tests/Utils/MetadataUtils.php
=> KBC-2383 branch metadata create

apiary.apib, src/Keboola/StorageApi/DevBranchesMetadata.php, tests/Common/BranchMetadataTest.php
Jira: KBC-2384
Connection: https://github.com/keboola/connection/pull/3596
---
=> Kbc 2384 branch metadata delete

apiary.apib, phpstan-baseline.neon, src/Keboola/StorageApi/BranchAwareClient.php, tests/Common/BranchAwareClientTest.php, tests/Common/BranchMetadataTest.php, tests/StorageApiTestCase.php
Jira: KBC-2410
Connection: https://github.com/keboola/connection/pull/3601
---
=> KBC-2410 branch metadata final

phpstan-baseline.neon, src/Keboola/StorageApi/Client.php, tests/Common/BranchMetadataTest.php, tests/Common/ComponentsEventsTest.php, tests/Common/ConfigurationMetadataTest.php, tests/Common/RunIdTest.php, tests/Common/SearchComponentsConfigurationsTest.php, tests/Common/TokensShareTest.php, tests/StorageApiTestCase.php, tests/Utils/EventTesterUtils.php
=> Fix init events

README.md
=> Update readme add note about tests retry

phpunit.xml.dist, tests/Backend/CommonPart1/BucketsTest.php, tests/StorageApiTestCase.php
=> init teradata suite

tests/Backend/CommonPart1/BucketsTest.php
=> improve testBucketEvents

tests/Backend/Workspaces/LegacyWorkspacesLoadTest.php, tests/Backend/Workspaces/WorkspacesLoadTest.php
Jira: KBC-XXX
---
Toto by mali byt vsetky testy ktore pouziva redshift a este nereusovali workspaces tag presiel tu https://app.travis-ci.com/github/keboola/connection/builds/248324614
=> Suites using for RS reusing workspaces

phpunit.xml.dist
=> remove temporary suite `temp-devbranch-only`

tests/Backend/Synapse/ImportTypedTableTest.php
=> Roman fix failing tests change synapse err msg

apiary.apib
Issue [332](https://github.com/keboola/storage-api-php-client/issues/332)
=> Add admin and org to token verify response

composer.json, phpunit.xml.dist, src/Keboola/StorageApi/Client.php, src/Keboola/StorageApi/Client/RequestTimeoutMiddleware.php, src/Keboola/StorageApi/Workspaces.php, tests-unit/Client/RequestTimeoutMiddlewareTest.php
=> KBC-2540 snizit timeout v SAPI clientovi

phpstan-baseline.neon, src/Keboola/StorageApi/Client.php, tests/Backend/CommonPart1/CreateTableTest.php, tests/Common/GetToFileTest.php
=> KBC-2591 V13 Fix

apiary.apib, tests/Common/TriggersTest.php
Jira: KBC-2570
Main PR: https://github.com/keboola/connection/pull/3689
---
=> KBC-2570 Edit test for new behavior of delete trigger

tests/Common/TriggersTest.php
Jira: KBC-2570
main pr: https://github.com/keboola/connection/pull/3690
---
=> Kbc 2570 update trigger with non admin token

composer.json
=> KBC-2545 remove vcs and use keboola/phpunit-retry-annotations

phpunit.xml.dist, tests/Backend/CommonPart1/CreateTableTest.php, tests/ClientTestCase.php
=> KBC-2437 teradata add CreateTableTest

apiary.apib, tests/Common/TriggersTest.php
Jira: KBC-2539
Code: https://github.com/keboola/connection/pull/3703
---
=> KBC-2539 Set minimal cooldown period to 1

apiary.apib, tests/Common/TriggersTest.php
Jira: KBC-2586
MainPR: https://github.com/keboola/connection/pull/3700
---
=> KBC-2586 trigger can be manipulated by token with access to component

phpunit.xml.dist, tests/Backend/Synapse/SynapseImportExportCommonTest.php, tests/_data/pk.multiple_synapse.increment.loaded.csv
=> KBC-2595 Synapse PK changes

phpunit.xml.dist
=> fix managed identity suite, use Synapse specific test

.github/workflows/branch.yml, .github/workflows/master.yml, .github/workflows/tag.yml, Dockerfile, README.md, apiary.apib, docker-compose.yml, docker/teradata/odbc.ini, docker/teradata/odbcinst.ini, phpunit.xml.dist, tests/Backend/WorkspaceConnectionTrait.php, tests/Backend/WorkspaceCredentialsAssertTrait.php, tests/Backend/Workspaces/Backend/TeradataWorkspaceBackend.php, tests/Backend/Workspaces/Backend/WorkspaceBackendFactory.php, tests/Backend/Workspaces/ParallelWorkspacesTestCase.php, tests/Backend/Workspaces/WorkspacesTest.php
Jira: KBC-2435
Connection: https://github.com/keboola/connection/pull/3672
---
=> KBC-2435 TD workspace tests

composer.json
=> KBC-237 Sort composer.json

tests/Backend/WorkspaceCredentialsAssertTrait.php
=> fix TD pass assert

phpstan-baseline.neon, phpunit.xml.dist, tests/Backend/Workspaces/TeradataWorkspacesUnloadTest.php, tests/StorageApiTestCase.php
Jira: KBC-2688
KBC: https://github.com/keboola/connection/pull/3766
---
=> KBC-2688 add TeradataWorkspacesUnloadTest

.github/PULL_REQUEST_TEMPLATE.md
=> KBC-2699 Make it obvious what should be released

phpstan-baseline.neon, src/Keboola/StorageApi/Client.php, src/Keboola/StorageApi/DevBranchesMetadata.php
Jira: KBC-2523
Connection: https://github.com/keboola/connection/pull/3694
---
=> KBC-2523 Endpoints with Request Objects enforce content type and based on it create from form data or json body

apiary.apib
Jira: KBC-1745
---
Takhle to ve vysledku vypada:
=> KBC-1745 remove short config calls from api docs

src/Keboola/StorageApi/Client.php, src/Keboola/StorageApi/S3Uploader.php
Jira: https://keboola.atlassian.net/browse/KBC-2651 & https://keboola.atlassian.net/browse/SRE-3638?focusedCommentId=42901
Pro dořešení timeoutů na uploadu do S3 a eliminování zbytečných retries potřebujeme vědět jak často a kde se dějou. Not a BC break. Nevím jak by se pro tohle měli napsat testy, takže jsem je nenapsal.
https://keboola.slack.com/archives/CFVRE56UA/p1654495909456429
---
=> add logging of AWS S3 retries

composer.json, phpstan-baseline.neon, src/Keboola/StorageApi/Client.php, tests/Backend/Export/SnapshotSimpleTest.php, tests/Backend/Workspaces/TeradataWorkspacesUnloadTest.php
=> KBC-2647 add simple test to create table from snapshot

tests/Backend/Workspaces/TeradataWorkspacesUnloadTest.php
Jira: KBC-2647
Jeden test sem opomněl upravit.
=> fix teradata expectation

src/Keboola/StorageApi/BranchAwareGuzzleClient.php, src/Keboola/StorageApi/Components.php, tests/Common/ComponentsTest.php, tests/Common/ConfigurationRowTest.php
=> KBC-2711 Do not use deprecated calls in SAPI client

.dockerignore
=> Add dockerignore (otherwise the context is ~ 200MB locally)

Dockerfile, phpunit.xml.dist, tests/Backend/WorkspaceCredentialsAssertTrait.php
=> Fix exasol tests

apiary.apib, phpstan-baseline.neon, src/Keboola/StorageApi/Workspaces.php, tests/Backend/Workspaces/ParallelWorkspacesTestCase.php, tests/Backend/Workspaces/WorkspacesTest.php, tests/Common/BranchWorkspacesTest.php
use ParallelWorkspacesTestCase async create workspace by default
Jira: KBC-2554
KBC: https://github.com/keboola/connection/pull/3805
=> CreateWorkspace async

src/Keboola/StorageApi/Workspaces.php, tests/Backend/Exasol/Workspace/WorkspaceLoadTest.php, tests/Backend/FileWorkspace/FileWorkspaceTestCase.php, tests/Backend/FileWorkspace/WorkspacesTest.php, tests/Backend/Mixed/LegacyWorkspacesTest.php, tests/Backend/Mixed/SharingTest.php, tests/Backend/Mixed/StorageApiSharingTestCase.php, tests/Backend/Mixed/Workspaces/BaseWorkSpacesTestCase.php, tests/Backend/Mixed/Workspaces/S3WorkspacesTest.php, tests/Backend/Mixed/WorkspacesRenameTest.php, tests/Backend/MixedSnowflakeExasol/SharingTest.php, tests/Backend/MixedSnowflakeSynapse/SharingTest.php, tests/Backend/Snowflake/CloneIntoWorkspaceTest.php, tests/Backend/Snowflake/CopyIntoWorkspaceTest.php, tests/Backend/Workspaces/ParallelWorkspacesTestCase.php, tests/Backend/Workspaces/ReadOnlyUserTest.php, tests/Backend/Workspaces/SnowflakeDynamicBackendsTest.php, tests/Backend/Workspaces/WorkspacesExasolTest.php, tests/Backend/Workspaces/WorkspacesSnowflakeTest.php, tests/Backend/Workspaces/WorkspacesSynapseTest.php, tests/Backend/Workspaces/WorkspacesTest.php, tests/Backend/Workspaces/WorkspacesTestCase.php
=> Make workspace drop/create sync by default

tests/Common/EventsTest.php
Jira: KBC-2691
Code: https://github.com/keboola/connection/pull/3807
=> KBC-2691 Validate event JSON schema in Create Event endpoint

apiary.apib, tests/Common/DevBranchesTest.php
Jira: KBC-2714
Main PR: https://github.com/keboola/connection/pull/3794
=> testCannotUpdateMainBranch

apiary.apib, tests/Common/DevBranchesTest.php
Reverts keboola/storage-api-php-client#818
=> Revert "testCannotUpdateMainBranch"

apiary.apib
Jira: KBC-2627
Connection: https://github.com/keboola/connection/pull/3812
=> KBC-2627 api doc: add correct request for bucket update

tests/Backend/CommonPart1/BucketsTest.php
=> fix testBucketCreateWithoutDescription

src/Keboola/StorageApi/Client.php, src/Keboola/StorageApi/Components.php
Reverts keboola/storage-api-php-client#830
=> Revert "KBC-2726 add support for JSON requests"

apiary.apib, phpstan-baseline.neon, tests/Backend/Exasol/TableDefinitionOperationsTest.php, tests/Backend/Synapse/TableDefinitionOperationsTest.php
=> KBC-2751 tables definition endpoint identifies typed table

tests/Backend/CommonPart1/RegisterBucketTest.php
Jira: KBC-2781
KBC: https://github.com/keboola/connection/pull/3844
=> KBC-2781 RegisterBucketTest tests events

apiary.apib, composer.json, phpunit.xml.dist, src/Keboola/StorageApi/Client.php, src/Keboola/StorageApi/GCSUploader.php, tests/File/GcsFileTest.php
Jira: KBC-2788
MainPR: https://github.com/keboola/connection/pull/3854
=> Kbc 2735 work with gcs file storage

phpunit.xml.dist, src/Keboola/StorageApi/Client.php, src/Keboola/StorageApi/GCSUploader.php
=> Roman gsc 2735 sliced

apiary.apib, phpunit.xml.dist, tests/Backend/CommonPart1/AlterTableTest.php, tests/Backend/Exasol/TableDefinitionOperationsTest.php, tests/Backend/Snowflake/TableDefinitionOperationsTest.php, tests/Backend/Snowflake/TypedTableInWorkspaceTest.php, tests/Backend/Workspaces/LegacyWorkspacesLoadTest.php
Jira: KBC-2752
Connection: https://github.com/keboola/connection/pull/3842
=> KBC-2752 table definition enpoint supports snowflake

apiary.apib, phpstan-baseline.neon, src/Keboola/StorageApi/DevBranches.php, tests/Common/DevBranchesTest.php
Jira: KBC-2714
Connection: https://github.com/keboola/connection/pull/3863
=> KBC-2714 it should not be possible to rename the main branch

tests/Backend/CommonPart1/CreateTableTest.php
=> Test for CSV with columns-data missmatch

tests/Backend/CommonPart1/CreateTableTest.php
Jira: KBC-2827
connection: https://github.com/keboola/connection/pull/3894
=> skip synapse only

src/Keboola/StorageApi/Client.php, src/Keboola/StorageApi/Downloader/DownloaderFactory.php, src/Keboola/StorageApi/Downloader/GcsClientFactory.php, src/Keboola/StorageApi/Downloader/GcsDownloader.php
Jira: KBC-XXX
Este som si vsimol pri spustani testov lokalne ze chyba jeden downloader
=> Add GcsDownloader

apiary.apib, phpunit.xml.dist, src/Keboola/StorageApi/GCSUploader.php, tests/Backend/CommonPart2/SlicedImportsTest.php, tests/Backend/Export/ExportParamsTest.php, tests/Backend/Export/ExportSimpleTest.php, tests/StorageApiTestCase.php
Jira: KBC-XXX
Connection https://github.com/keboola/connection/pull/3895
- Pridavam par chybajucich veci do testov tag presiel tu https://dev.azure.com/keboola-dev/Connection%20build/_build/results?buildId=24123&view=results
- odoberam nastavovanie storage class pretoze to google zacal podporovat na zlozky
- pridavam nove suity na testovanie GCS
=> Add backend snowflake gcs test

tests/Backend/CommonPart1/CreateTableTest.php
reseno https://keboola.slack.com/archives/CFVRE56UA/p1659103881847889?thread_ts=1659000953.284999&cid=CFVRE56UA
=> Generate bucket ID correctly from testID

tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Jira: KBC-2792
Connection: https://github.com/keboola/connection/pull/3881
=> KBC-2792 enable create snapshot on typed table test

src/Keboola/StorageApi/GCSUploader.php
Zjednodušení posílání manifestu do GCS
=> GCSUploader - simplify sliced file manifest upload

apiary.apib, phpstan-baseline.neon, src/Keboola/StorageApi/Client.php, tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Jira: KBC-2828
KBC: https://github.com/keboola/connection/pull/3914
=> KBC-2828 add snowflake add column on typed tables

tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Jira: KBC-2850
KBC: https://github.com/keboola/connection/pull/3923
=> KBC-2850 add testCreateTableWithPrimaryKeyBasetype

tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Jira: KBC-2830
KBC: https://github.com/keboola/connection/pull/3924
=> KBC-2830 testCreateTableWithPrimaryKeyBasetype -> testPrimaryKeys

src/Keboola/StorageApi/Client.php, src/Keboola/StorageApi/GCSUploader.php, src/Keboola/StorageApi/GCSUploader/PromiseHandler.php, tests/GCSUploader/PromiseHandlerTest.php
=> Roman fix slicing uploads handle promise and retry

phpstan-baseline.neon, tests/Common/ComponentsTest.php, tests/Utils/ComponentsConfigurationUtils.php
Jira: KBC-2841
Connection: https://github.com/keboola/connection/pull/3918
=> KBC-2841 storage api client configuration row strict types

tests/Backend/Snowflake/ImportTypedTableTest.php
Jira: KBC-2862
Connection: https://github.com/keboola/connection/pull/3933
=> Kbc 2862 user error when load fails to native types

apiary.apib, tests/Backend/CommonPart1/CreateTableTest.php, tests/Backend/Snowflake/TimeTravelTest.php, tests/Common/QueueJobsTest.php
Jira: KBC-2790
Connection: https://github.com/keboola/connection/pull/3898
---
=> KBC-2790 fix ro on endpoints storage buckets controller

tests/Backend/Snowflake/ImportTypedTableTest.php
Jira: KBC-2862
https://keboola.slack.com/archives/C01DQ9VRQK0/p1661168773280509
=> ImportTypedTableTest ignore when feature is not set

tests/Backend/CommonPart1/RegisterBucketTest.php
=> fix async call of dropBucketIfExists

tests/Backend/Snowflake/TypedTableInWorkspaceTest.php
Jira: KBC-2794
KBC: https://github.com/keboola/connection/pull/3943
=> KBC-2794 test failing OM on type mismatch

tests/Backend/Snowflake/TableDefinitionOperationsTest.php, tests/Backend/Workspaces/MetadataFromSnowflakeWorkspaceTest.php
Jira: KBC-2791 KBC-2893 KBC-2870
KBC: https://github.com/keboola/connection/pull/3961
=> KBC-2791 KBC-2893 KBC-2870 update expected Snowflake metadata

tests/Common/TokensTest.php
Jira: KBC-2814
Connection: https://github.com/keboola/connection/pull/3939
=> KBC-2814 add CreateTokenRequest and CreateLimitedTokenRequest

apiary.apib
=> KBC-2815 update apiary documentation - add get trigger

tests/Common/TriggersTest.php
Jira: KBC-2815
Connection: https://github.com/keboola/connection/pull/3962
=> KBC-2815 replace CreateTriggerRequest

apiary.apib
Jira: KBC-2909
Connection: https://github.com/keboola/connection/pull/3982
=> KBC-2909 createLimitedToken: expiresIn as optional

tests/Common/TokensTest.php
=> KBC-2909 createLimitedToken: expiresIn as optional - fix tests

phpstan-baseline.neon, src/Keboola/StorageApi/Client.php, src/Keboola/StorageApi/Components.php
=> KBC-2761 improve base methods that sends requests

phpstan-baseline.neon, src/Keboola/StorageApi/Client.php, tests/Common/ComponentsEventsTest.php
=> KBC-2761 migrate Tickets to JSON

phpstan-baseline.neon, src/Keboola/StorageApi/Client.php
=> KBC-2761 migrate Triggers to JSON

src/Keboola/StorageApi/Client.php, tests/Common/ComponentsEventsTest.php
=> KBC-2761 migrate Tickets to JSON - fix type hint

phpstan-baseline.neon, src/Keboola/StorageApi/Client.php, src/Keboola/StorageApi/Options/TokenAbstractOptions.php, src/Keboola/StorageApi/Options/TokenCreateOptions.php, src/Keboola/StorageApi/Tokens.php, tests/Common/TokensTest.php
=> KBC-2761 tokens use json

phpstan-baseline.neon, src/Keboola/StorageApi/Client.php, src/Keboola/StorageApi/Event.php, tests/Common/BranchEventsTest.php, tests/Common/EventsTest.php, tests/StorageApiTestCase.php
=> KBC-2761 migrate Events to JSON

phpstan-baseline.neon, src/Keboola/StorageApi/Client.php
=> KBC-2761 migrate Tables to JSON

phpstan-baseline.neon, src/Keboola/StorageApi/Components.php, tests/Common/ComponentsTest.php, tests/Common/ConfigurationRowTest.php
=> KBC-2761 migrate Components to JSON

phpstan-baseline.neon, src/Keboola/StorageApi/DevBranches.php
=> KBC-2761 migrate DevBranches to JSON

tests/Common/IndexTest.php
=> Test stack ID existence in storage index

tests/StorageApiTestCase.php, tests/Utils/EventTesterUtils.php, tests/Utils/EventTesterUtilsImpl.php, tests/Utils/EventTesterUtilsTest.php
=> Fix event checks in tests

apiary.apib, src/Keboola/StorageApi/Client.php, src/Keboola/StorageApi/Options/TableWithConfigurationOptions.php, tests/Backend/CommonPart1/CreateTableWithConfigurationTest.php, tests/Utils/EventTesterUtils.php
Jira: KBC-2921
Connection: https://github.com/keboola/connection/pull/3994 ~https://github.com/keboola/connection/pull/4001~
=> KBC-2921 add buckets/tables-with-configuration

tests/Backend/CommonPart1/CreateTableWithConfigurationTest.php, tests/Backend/CommonPart1/MigrateTableWithConfigurationTest.php, tests/Backend/TableWithConfigurationUtils.php, tests/StorageApiTestCase.php
=> KBC-2933 Refactoring tests

phpunit.xml.dist, tests/Backend/CommonPart1/BucketsTest.php, tests/StorageApiTestCase.php
Jira: KBC-3004
MainPR: https://github.com/keboola/connection/pull/4035
=> add new bq test suite

tests/Common/MetadataTest.php, tests/File/CommonFileTest.php
https://keboola.slack.com/archives/C04813S29UJ/p1666763637937079
=> add assert to metadata test

apiary.apib, tests/Common/IndexTest.php, tests/File/CommonFileTest.php
Jira: https://keboola.atlassian.net/browse/KBCP-1666
- no new methods
---
Len doplneny test a mensi update docs
=> Update test and docs (128px icon)

composer.json
Jira: KBC-XXX
Asi pri implenetacii sa to. tam zabudlo a nieje to potreba
=> remove Google ApiClient

apiary.apib, tests/Backend/CommonPart1/CreateTableWithConfigurationTest.php, tests/Backend/CommonPart1/MigrateTableWithConfigurationTest.php
Jira: KBC-3000
KBC: https://github.com/keboola/connection/pull/4044
=> KBC-3000 test table with configuration response

tests/Backend/CommonPart1/TableWithConfigurationLoadTest.php
Jira: KBC-2933
Connection: https://github.com/keboola/connection/pull/4034
=> KBC-2933 Load queries

tests/Backend/CommonPart1/MigrateTableWithConfigurationTest.php, tests/Backend/CommonPart1/TableWithConfigurationLoadTest.php, tests/Backend/TableWithConfigurationUtils.php
Jira: KBC-3009
KBC: https://github.com/keboola/connection/pull/4043
=> KBC-3009 tables with configuration onError,cleanup

phpstan-baseline.neon, tests/Backend/CommonPart1/TableWithConfigurationLoadTest.php, tests/Backend/Workspaces/Backend/RedshiftWorkspaceBackend.php
Jira: KBC-3010
Connection: https://github.com/keboola/connection/pull/4049
=> KBC-3010 test incremental load from file with TwC

tests/Backend/CommonPart1/MigrateTableWithConfigurationTest.php, tests/Backend/CommonPart1/TableWithConfigurationLoadFromWorkspaceTest.php, tests/Backend/CommonPart1/TableWithConfigurationLoadTest.php, tests/Backend/TableWithConfigurationUtils.php
Jira: KBC-3011
Connection: https://github.com/keboola/connection/pull/4050
=> KBC-3011 twc workspaceload
