keboola/storage-api-php-client

tests/Keboola/StorageApi/FilesTest.php
tests/Keboola/StorageApi/Tables/SlicedImportsTest.php

Also, there were problem with `testEncryptionMustBeSetWhenEnabled` in `eu-central-1` region.
Setting another signature version should fix it:
```
AWS.config(
region: 'eu-central-1',
s3_signature_version: :v4
)
```

Fixes remaining usage of hardcoded region

---

apiary.apib
src/Keboola/StorageApi/Components.php
src/Keboola/StorageApi/Options/Components/ListComponentConfigurationsOptions.php
src/Keboola/StorageApi/Options/Components/ListComponentsOptions.php
src/Keboola/StorageApi/Workspaces.php
tests/Common/ComponentsTest.php

Allows list and restore deleted configs
BC breaks:
- `ListConfigOptions` class renamed to `ListComponentsOptions`
- `Components::getComponentConfigurations` method renamed to `Components::getComponentConfigurations` and accept only one param (object of `ListComponentConfigurationsOptions`)

Configuration restore

---

.travis.yml
README.md
docker-compose.yml
set-env.mixed.template.sh
set-env.mysql.template.sh
set-env.redshift.template.sh
set-env.sharing.template.sh
set-env.snowflake.template.sh

For local development KBC is needed to run. It runs in `connection_default`. By linking storage API to this network it can connect to KBC using internal docker DNS as `apache` instead of fallback to host systems IP address, that may change unexpectedly.

Allow the tests to connect to local KBC instance network

---

tests/Common/ComponentsTest.php

FIXES:
```
common                   -	1) Keboola\Test\Common\ComponentsTest::testConfigurationRollback
common                   -	Failed asserting that '2018-04-13T09:34:52+0200' is not equal to <string:2018-04-13T09:34:52+0200>.
common                   -	
common                   -	/code/tests/StorageApiTestCase.php:45
common                   -	/code/tests/Common/ComponentsTest.php:894
```

fix - unstable test

---

apiary.apib

Updated doc due: https://github.com/keboola/connection/issues/1226#issuecomment-380484066

fix(apiary) removed state from include options in version list

---

src/Keboola/StorageApi/Client.php
tests/Backend/CommonPart2/SlicedImportsWithSlicedUploadsTest.php
tests/Backend/CommonPart2/UploadSlicedFileTest.php

Fixes #234, required for https://github.com/keboola/output-mapping/issues/20
V metodě `uploadSlicedFile` se počítá souhrnná velikost souborů (součet sliců). Chybně se to počítalo před tím, než se soubory komprimovaly. Přesunul jsem počítání velilkosti až po kompresi.
Kompresi teď AFAIK nic nepoužívá, takže impact by to nemělo mít žádný.
Přidal jsem k tomu tři testy
- `SlicedImportsWithSlicedUploadsTest::testSlicedImportCompress` testuje, zda se tabulka naimportuje správně, když se uploadu nastaví, že se má komprimovat
- `UploadSlicedFileTest::testCompress` testuje, zda komprese opravdu proběhla (velikost souboru lokálně a po uploadu), upload se neimportuje do tabulky
- `UploadSlicedFileTest::testNoCompress` ověřuje, že se uploadovaný soubor nekomprimuje (velikost souborů je stejná), …

fix: count file size after files are compressed

---

src/Keboola/StorageApi/Client.php
src/Keboola/StorageApi/TableExporter.php
tests/Backend/CommonPart1/TableExporterTest.php
tests/Common/QueueJobsTest.php

FIXES #236 
- nová fce `Client::queueTableExport`, která založí exportní job (tabulka -> s3) a vrátí `jobId`
- přeházený kód v `TableExporter` a nová metoda `TableExporter::exportTables`, která přijímá pole asociativích polí argumentů (dřívější) metody `TableExporter::exportTable`
- `TableExporter::exportTable` nyní zabalí argumenty do pole a zavolá `TableExporter::exportTables` (takže se existujícími testy pokryje nová funkcionalita)
- v testech se navíc testuje, že se provedou exporty dvou souborů (`testExportTables`)

feat: queue table export

---

tests/Backend/CommonPart1/DataPreviewLimitsTest.php

Test na pro json data preview. Vytvoří se csv, které má jeden řádek větší jak 20000 znaků a ten se má ořezat na 16K.
Test for https://github.com/keboola/connection/pull/1647

Test for truncation json data preview

---

tests/Backend/CommonPart1/DataPreviewLimitsTest.php

Dávám zpátky podmínku na omezení pro RS.

Remove condition for skipping RS on testJsonTruncationLimit

---

src/Keboola/StorageApi/Client.php
src/Keboola/StorageApi/TableExporter.php
tests/Backend/CommonPart1/TableExporterTest.php
tests/_data/escaping.backslash.redshift.out.csv
tests/_data/escaping.raw.redshift.out.csv

Testy se mi nějak nepodařily lokálně spustit. Rozeběhlo se to a nic nedělalo. V logu apache je jenom:
```
[08/Jan/2019:12:12:34 +0000] "GET /v2/storage/jobs/8 HTTP/1.1" 200 2370 "-" "Keboola Storage API PHP Client/10.4.0" "-"
```
Pořád dokola.

Removes raw&escaped format from tests and client

---

tests/Common/TokensTest.php

Drobny fix pro predchozi PR:
https://github.com/keboola/storage-api-php-client/pull/290
Na testingu test padal, protoze v testovacim projektu je zrejme vic uzivatelu s master tokenem.
Udelal jsem teda test nezavislej na poctu tokenu.

fixup tests: tokens list and get

---

tests/Common/TriggersTest.php

Přidal jsem test, že last run není `null` a je menší než `NOW()`. Nemáme bohužel žádný čas, kterýho bych se chytil a porovnal to jako equal něco ...

Testing last run is not null

---

tests/Common/TriggersTest.php

V https://github.com/keboola/storage-api-php-client/pull/307/ jsem se nějak zamotal v rebase a tak jsem radši udělal novou branch a překopíroval těch pár řádek.
Udělal jsem test na:
-  mazání tokenu, který má na sobě triggery
- že nelze přiřadit token s expirací k triggeru

Test for token with expiration and droping token with trigger

---

composer.json

PSR logger je v `require-dev`, ale pak je použitý v `src/Client.php` -> https://github.com/keboola/storage-api-php-client/blob/19f8f2e4a19eee249918d140f152f1eac2ec79c1/src/Keboola/StorageApi/Client.php#L126
Teďka ho používám v MAPI klientovi a PSR NullLogger mi tam chybí, protože `require-dev` se nedistribuuje.

PSR logger should not be inside dev dependecies

---

src/Keboola/StorageApi/Client.php
tests/Common/FilesTest.php

Když je $fileId = null, tak se vlastně místo GET /storage/files/123/ pošle GET /storage/files/, což je metoda pro listování a vrátí se všechny soubory. 
Zkusil jsem jestli to funguje na `null`, `'karel'`, `'-5'` , `-5` a taky jestli projde `123` a `'123'`.

File id must a positive integer

---

apiary.apib

Změnil jsem defaultní hodnotu `isEncrypted` u souborů na false, protože to tak ve skutečnosti je.

Apib - Files are not encrypted by default

---

tests/Common/FilesTest.php

Doplnil jsem do testu kontrolu, že pokud není nastavený federationToken, tak se v `getFile` nevrací credentials.
To, že se `credentials` a `s3Path` vrací při federationToken se už testuje tady:
https://github.com/keboola/storage-api-php-client/blob/59561ca7ff3b7ac1047b5a823a35ae094546aaf4/tests/Common/FilesTest.php#L612-L613

Tests - federation token required for credentials

---

apiary.apib
src/Keboola/StorageApi/Client.php
src/Keboola/StorageApi/Options/SearchTablesOptions.php
tests/Common/SearchTablesTest.php
tests/Options/SearchTablesOptionsTest.php

implementation of https://github.com/keboola/connection/issues/2184 (private)
I kept the test simple only with count of returned tables. It's for discussion if return full table output like `/storage/tables` with `include` or simple like only id,name.

/search/tables endpoint

---

tests/Backend/Workspaces/LegacyWorkspacesLoadTest.php
tests/Backend/Workspaces/WorkspacesLoadTest.php
tests/Backend/Workspaces/WorkspacesRedshiftTest.php
tests/Backend/Workspaces/WorkspacesRenameLoadTest.php

Redshift changed default compression for integer types which cause this tests to fail.
After discussion we decided that is safe to remove this check https://keboola.slack.com/archives/CL11GKH6H/p1580133035012800

Remove lzo compression from failing tests

---

tests/Backend/Snowflake/TimestampTest.php
tests/Backend/Workspaces/WorkspacesUnloadTest.php

testuje se jestli není _timestamp null
**TimestampTest**
- testy importů přes db-import lib typ importy `csv` `manifest/sliced` `copy`
- joby: 
`TableImport `
`TableCreate`
- endpointy: 
`Storage_BucketsController::postTablesAction`
`Storage_TablesController::postImportAction`
nad kbc-50 failne test `testTimestampCopyImport` protože chybí timestamp
TODO:

Test if _timestamps are not null after copy

---

tests/Backend/Snowflake/TimestampTest.php

extends: https://github.com/keboola/storage-api-php-client/pull/370
jira: https://keboola.atlassian.net/browse/KBC-203
Test sem refaktoroval, timestamp sa checkuje ne na null, ale na formát a přidal sem check importovaných řádků.

KBC-203 - harden timestamp test, check timestamp format a number of imported rows

---

src/Keboola/StorageApi/Client.php

Add options class for table update, fix put in client

---

phpunit.xml.dist
tests/Backend/Workspaces/Backend/InputMappingConverter.php
tests/Backend/Workspaces/Backend/LegacyInputMappingConverter.php
tests/Backend/Workspaces/LegacyWorkspacesLoadTest.php
tests/Backend/Workspaces/LegacyWorkspacesSynapseTest.php
tests/Backend/Workspaces/WorkspacesLoadTest.php
tests/Backend/Workspaces/WorkspacesSynapseTest.php

JIRA:
https://keboola.atlassian.net/browse/KBC-292
https://keboola.atlassian.net/browse/KBC-306
https://keboola.atlassian.net/browse/KBC-305
KBC:
https://github.com/keboola/connection/pull/2454
Původní PR:
closes https://github.com/keboola/storage-api-php-client/pull/398
Synapse nezná typ `integer` a `character` takže bylo potřeba zkonvertovat stávající input mapping tak aby fungoval pro synapse, proto existuje třída InputMappingConverter, LegacyInputMappingConverter 
tady je k tomu konverzace https://keboola.slack.com/archives/CFVRE56UA/p1585221785016200

[Synapse] KBC-292 Workspace load

---

tests/Backend/Synapse/AlterTableTest.php

Alter table - enable tests for primary key drop for Synapse storage backend

tests: synapse backend - table primary key drop

---

tests/Backend/Snowflake/DirectAccessTest.php

V predchadzajucom mergi som pridal este jeden update toho displayName, a ten build ktory presiel nebol rebasnuty

Fix view name after merge second renaming `updatedDisplayName`

---

src/Keboola/StorageApi/TableExporter.php
tests/Backend/CommonPart1/TableExporterTest.php

Automatically run table export with current list of table columns, if optional `columns` parameter in `exportOptions` is not set.
Fixes https://keboola.atlassian.net/browse/KBC-535

TableExporter: auto columns add to export params

---

apiary.apib

V dokumentaci je chybka 
https://github.com/keboola/storage-api-php-client/blob/f4205718f0f61751ffe29615ad3d196009c1646e/src/Keboola/StorageApi/Client.php#L1012-L1018

Fix Create Table Column endpoint in documentation

---

tests/Backend/CommonPart1/TableExporterTest.php

Predtim test spolehal na to ze se data vyexportuji ve stejnem poradi jako byly naimportovany. Coz u Synapse backendu tak nefunguje. Tak jsem pridal where filter a ten limit vyhodil.

TableExporterTest: tests fixup for synapse backend

---

apiary.apib
tests/Common/TokensTest.php

Pay As You Go info in owner details if the project is configured as paygo
```json
{
"payAsYouGo": {
"purchasedCredits": 123
}
}
```

tests: paygo info in token details

---

tests/Backend/Workspaces/MetadataFromRedshiftWorkspaceTest.php
tests/Backend/Workspaces/MetadataFromSynapseWorkspaceTest.php

Zabudol som pri vypinani automatic datypes odobrat este nejake veci v testoch.
Spustal som vsetky testy v `MetadataFromSynapseWorkspaceTest` a `MetadataFromRedshiftWorkspaceTest` lokalne to bolo zelene.
Na testingu spadol len `testCopyImport`

KBC-646 remove test for automatic datatypes redshift synapse

---

composer.json
phpunit.xml.dist
tests/Backend/Snowflake/OrderByTest.php
tests/Backend/Workspaces/WorkspacesTestCase.php
tests/Downloader/AbsUrlParserTest.php
tests/StorageApiTestCase.php

Update PHPunitu + pridani paratestu
Kazda testsuite ma svoji kopii s prefixem `paratest` kam se presunuly testy co jsou poustet paralelne.
Vyzkouset se da pomoci
```
docker-compose run --rm -e STORAGE_API_URL=$STORAGE_API_URL -e STORAGE_API_TOKEN=$STORAGE_API_TOKEN dev php ./vendor/bin/paratest --verbose=1 --processes=3 --colors -f --testsuite=paratest-common
```
```
docker-compose run --rm -e STORAGE_API_URL=$STORAGE_API_URL -e STORAGE_API_TOKEN=$STORAGE_API_TOKEN dev php ./vendor/bin/paratest --verbose=1 --processes=3 --colors -f --testsuite=paratest-backend-snowflake-part-2
```

Paratest part1

---

tests/StorageApiTestCase.php

SLACK: https://keboola.slack.com/archives/CFVRE56UA/p1600948517029700?thread_ts=1600944572.025800&cid=CFVRE56UA
Stane se že mazání resource vrátí 500 kvůli nečekané chybě, jenže to vezme backoff takže se pustí request znova, ten pak vrátí 404 protože tam už resource není, ale to skončí failem protože 404 je exception a pokusí se to založit nový bucket ikdyž ten starý tam pořád je.
Druhá možnost je zrušit backoff, ale třeba tady by to zbytečně failnulo https://my.papertrailapp.com/groups/4231582/events?focus=1245745233677926403&q=WorkspacesSnowflakeTest%3A%3AtestLoadedPrimaryKeys%20backend-snowflake-part-2

dont throw exception if initEmptyBucket deleting resource receive 404

---

tests/Common/BranchComponentTest.php

Main PR: https://github.com/keboola/connection/pull/2842
Tie testy som pridal zatial len tak ako su v ComponentsTest.php a neriesil som nejaku paralelizovatelnost imho je potreba to potom supnut do jedneho filu spolu s ComponentsTest.php aby sa testovali vsetky veci jak pre dev branch tak pre main a to pojde az ked to bude cele hotove.

KBC-680 branch support for list configuration

---

apiary.apib
phpunit.xml.dist
tests/Backend/FileWorkspace/Backend/Abs.php
tests/Backend/FileWorkspace/WorkspacesTest.php

JIRA: KBC-1029 přidal sem ještě drop KBC-1030 bez toho je to docela na nic.
KBC: https://github.com/keboola/connection/pull/2854
- podobně jako normální workspacy sem přihodil ABS class, která dělá abstrakci nad tím file workspacem https://github.com/keboola/storage-api-php-client/commit/26ae23c0c1ca68b71e232cbacb3f1e3cd8088efa
- přidal sem to do {synapse,snowflake-abs}-part-1 test suite, měl  by fičat load z obou asi https://github.com/keboola/storage-api-php-client/commit/c3ac6f40ece07e4da3bd69d768626cb8c4829489
- update api doc https://github.com/keboola/storage-api-php-client/commit/9eafd5ea7b7eb5e9776fc8c1906d33ddb202052f

KBC-1029 file workspace create/drop

---

tests/Common/TokensTest.php

PR: https://github.com/keboola/connection/pull/2857

tests: readOnly user cannot create token with limited scope

---

tests/Common/EventsTest.php

Simulace issue https://keboola.atlassian.net/browse/KBC-873
Testuje limity velikosti event. 
Oproti stacku s AWS frontami prochází:
Oproti stacku s Azure frontami už také prochází po přepnutí na Service Bus.

Test large events

---

apiary.apib

Main PR: https://github.com/keboola/connection/pull/2878

KBC-1070: Fix apiary include parameter allowed value for list conponents

---

apiary.apib
tests/Common/IndexTest.php

Jira: https://keboola.atlassian.net/browse/KBC-1127
Before asking for review:
Changes:
- Tests for `exclude=componentDetails`
---
V tych novych castiach som uplne vyhodil testy na tie `keys` co sa uz testuju, nech je tam len to podstatne.
Testujem 2 nove pripady:
- `?exclude=componentDetails`
- `?exclude=components,componentDetails` -> ma odignorovat `componentDetails`, pretoze tam ziadne nebudu

Tests for exclude=componentDetails

---

tests/Common/BranchComponentTest.php
tests/Common/ComponentsTest.php

Je to revert k https://github.com/keboola/storage-api-php-client/pull/543 ale neslo to spravit uz automaticky.
Main PR: https://github.com/keboola/connection/pull/2944
---

Revert 2940 revert 2916 roman fix saving configuration when updating row

---

tests/Common/BranchComponentTest.php

Jira: KBC-1138
Main PR: https://github.com/keboola/connection/pull/2934
---

KBC-1138: Add test for increments versions of config and config rows

---

tests/Backend/Workspaces/WorkspacesRedshiftTest.php

Jira: KBC-1188
---
Test nebyl stabilní selectoval všechny tabulky `languages` v databázi. Teď je omezený na schéma.
Zkusil sem pustit testy proti testingu aj vlastní db.

Fix WorkspacesRedshiftTest::testLoadedDist

---

apiary.apib
docker-compose.yml
phpstan.neon
tests/Common/BranchComponentTest.php
tests/bootstrap.php

**no BC break**
---
Kopirujem testy, ktore riesia `listConfigurationRowVersions`. Je to tam spravene tak, ze na zaciatku kazdeho testu mazem suvisiace branches.

Copy "row versions" related tests

---

apiary.apib
tests/Common/BranchComponentTest.php

Jira: KBC-1273
Code: https://github.com/keboola/connection/pull/3057
---
There is a "bc break" of sorts - that it does not return 404 for configuration deleted in branch, but 204 instead. But the API is still in private beta, so I wouldn't sweat it.

KBC-1273 Delete configuration when resetting to deleted configuration

---

tests/Common/BranchComponentTest.php
tests/Common/ConfigurationRowsSortOrderTest.php

Jira: KBC-1295
New test for https://github.com/keboola/connection/pull/3076 . Checking that if you update a Configuration with the same data (no change) it wont increase version.

KBC-1295 Add configuration test for keeping version when no update

---

src/Keboola/StorageApi/Client.php
src/Keboola/StorageApi/Tokens.php
tests/Backend/CommonPart1/ExportParamsTest.php
tests/Backend/FileWorkspace/WorkspacesLoadTest.php
tests/Backend/Mixed/SharingTest.php
tests/Backend/Mixed/StorageApiSharingTestCase.php
tests/Backend/Snowflake/DirectAccessTest.php
tests/Backend/Snowflake/TimeTravelTest.php
tests/Backend/Workspaces/LegacyWorkspacesLoadTest.php
tests/Backend/Workspaces/ParallelWorkspacesTestCase.php
tests/Backend/Workspaces/WorkspacesLoadTest.php
tests/Common/ComponentsTest.php
tests/Common/DevBranchesTest.php
tests/Common/MetadataTest.php
tests/Common/TokensShareTest.php
tests/Common/TokensTest.php
tests/Common/TriggersTest.php
tests/File/CommonFileTest.php
tests/StorageApiTestCase.php

Jira: https://keboola.atlassian.net/browse/KBC-1353
---
- Přesunul jsem token metody do `Keboola\StorageApi\Tokens`
- Deprekoval jsem metody v `Keboola\StorageApi\Client`
- Zrefactoroval jsem testy aby používaly metody z nové třídy
- Přidal jsem `testDeprecatedMethods` abych otetoval metody z `Keboola\StorageApi\Client`
- Upravil jsem deprecated metody aby volaly `Keboola\StorageApi\Tokens`

Keboola\StorageApi\Tokens for tokens manipulation

---

phpunit.xml.dist
tests/Backend/Snowflake/TimestampTest.php
tests/Backend/Workspaces/Backend/RedshiftWorkspaceBackend.php
tests/Backend/Workspaces/Backend/SnowflakeWorkspaceBackend.php
tests/Backend/Workspaces/Backend/SynapseWorkspaceBackend.php
tests/Backend/Workspaces/Backend/WorkspaceBackend.php
tests/Backend/Workspaces/LegacyWorkspacesLoadTest.php
tests/Backend/Workspaces/LegacyWorkspacesRedshiftTest.php
tests/Backend/Workspaces/LegacyWorkspacesSnowflakeTest.php
tests/Backend/Workspaces/LegacyWorkspacesSynapseTest.php
tests/Backend/Workspaces/MetadataFromRedshiftWorkspaceTest.php
tests/Backend/Workspaces/MetadataFromSnowflakeWorkspaceTest.php
tests/Backend/Workspaces/MetadataFromSynapseWorkspaceTest.php
tests/Backend/Workspaces/ParallelWorkspacesTestCase.php
tests/Backend/Workspaces/ReadOnlyUserTest.php
tests/Backend/Workspaces/SynapseWorkspacesUnloadTest.php
tests/Backend/Workspaces/WorkspacesLoadTest.php
tests/Backend/Workspaces/WorkspacesRedshiftTest.php
tests/Backend/Workspaces/WorkspacesRenameLoadTest.php
tests/Backend/Workspaces/WorkspacesSnowflakeTest.php
tests/Backend/Workspaces/WorkspacesSynapseTest.php
tests/Backend/Workspaces/WorkspacesTest.php
tests/Backend/Workspaces/WorkspacesUnloadTest.php
tests/Common/BranchBucketsTest.php
tests/StorageApiTestCase.php

KBC: https://github.com/keboola/connection/pull/3138
---
V paralelních testech se nevytvářejí při každém testu nové workspacy, ale používají se již vytvořené _(případně se vytvoří nové pokud neexistujou a nebo nesedí požadovaný backend)_.
Zrychluje to build, zejména na RS _(viz PR v KBC)_
Review asi ideálně jako celek. Snažil jsem se to tlačit po commitech ale několikrát jsem to refactoroval. Výsledná úprava nakonec neni tak moc velká.

Reuse workspaces in tests

---

src/Keboola/StorageApi/Workspaces.php
tests/Backend/Mixed/SharingTest.php
tests/Backend/Snowflake/CloneIntoWorkspaceTest.php

Jira: KBC-1464
Connection: https://github.com/keboola/connection/pull/3165
removed `name` parameter from `POST workspaces` . Theoretical BC but parameter `name` wan't documented nor used. But instead of silent accepting this useless parameter it will throw an exception that it was not expected

KBC-1464 Remove name parameter from creating requests

---

docker/xdebug/Dockerfile

Nejnovejsi verze xDebug je 3, ale ta podporuje jen PHP 7.2 a vyssi. Takze je potreba pouzit posledni verzi z 2.x.

Use xDebug 2 for PHP 7.1

---

src/Keboola/StorageApi/Exception.php

Nema to zadne issue. Vsiml jsem si toho, kdyz mi PHPStan zacal rvat, ze `$message` muze byt jen `null`.

Fix Exception constructor parameters types (in phpDoc)

---

src/Keboola/StorageApi/Client.php
src/Keboola/StorageApi/TableExporter.php
tests/Backend/FileWorkspace/Backend/Abs.php

The subfolder causes a problem when two non-root users run the SAPI client on the same machine. Temp folder is by default writeable by all users, but if userA creates the client, the subfolder sapi-php-client is created with userA being its owner. UserB can't then use the client, because the sapi-php-client subfolder is not writeable.
Related issues:
https://keboola.atlassian.net/browse/PS-2231
https://keboola.atlassian.net/browse/PS-2307
Imho not a BC break.

Remove common subfolder in temp folder

---

tests/Common/BranchComponentTest.php

Jira: KBC-1724
---
Main PR: https://github.com/keboola/connection/pull/3337

Configuration rows for deleted configuration should not be listed test

---

src/Keboola/StorageApi/TableExporter.php
tests/Backend/CommonPart1/TableExporterTest.php

Jira: https://keboola.atlassian.net/browse/PS-2638
BC break by to být neměl - parametr gzip nyní kontroluje pouze to v jakým formátu uživatel dostane data (což je stejně). To, že se interně přenáší komprimovaně mu může být putna.
Release as 12.x.0

feat: always gzip transfer

---

.gitignore
composer.json
phpstan-baseline.neon
phpstan.neon
src/Keboola/StorageApi/Client.php
tests/Backend/Mixed/StorageApiSharingTestCase.php
tests/StorageApiTestCase.php

Jira: KBC-1931
---
There are no "low hanging fruits" here unfortunately. We need to start fixing the typehints as we go and get phpstan failures in new tests. Most of the methods are historically set to "mixed" even though they return array or string or int. That needs to slowly be fixed first.

KBC-1931 add phpstan to sapi client

---

apiary.apib

Endpoint import-async does not support import from snapshot.
Slack: https://keboola.slack.com/archives/CFVRE56UA/p1636118198133100
---

remove snapshotId from import-async, endpoint is not supporting this

---

tests/Backend/CommonPart1/ImportExportCommonTest.php

skip testTableAsyncImportMissingFile on Exa because of deprecated Fomm upload. Then we can enable paratest-exasol suite on build

skip testTableAsyncImportMissingFile on EXA

---

composer.json

`composer.lock` neni verzovany, ale stale se generuje a rychle zastarava. Proto ho prestaneme generovat.
ℹ️  Kazdy si ho musi lokalne smazat, pokud chce mit aktualni balicky.
---

do not generate composer.lock

---

phpstan-baseline.neon
tests/Common/BranchEventsTest.php

Jira: KBC-1726
Class BranchEventTest was a good candidate to be consolidated. But all tested usecases are branch-related so the tests stay in there.
It contained one test method with three different usecases -> I have split the cases to independent methods

KBC-1726 consolidate branch event test

---

tests/Common/TokensShareTest.php

```
18:35:48-UTC - common                             -	There was 1 risky test:
18:35:48-UTC - common                             -	
18:35:48-UTC - common                             -	1) Keboola\Test\Common\TokensShareTest::testTokenShare
18:35:48-UTC - common                             -	This test did not perform any assertions
18:35:48-UTC - common                             -	
18:35:48-UTC - common                             -	/code/tests/Common/TokensShareTest.php:22
```
---

fix risky test by adding some assert

---

src/Keboola/StorageApi/Client.php

No BC break, just an optimization of Client->getServiceUrl() that needs only 'services' part of the index result.

Optimize Client->getServiceUrl()

---

phpstan-baseline.neon
tests/Common/MetadataTest.php

Jira: KBC-XXX
---
Na mastru tento test neprejde, pretoze sa updatnu vestky metadata aj tie pre providera pre ktoreho sa nemaju updatovat.
Este ma napadlo to doplnit cisto o situaciu ze to nastavujem pre bucket/tabulku ale neviem je to ten isty kod tak ci by to nebola zbytocne duplicita

add testColumnMetadataOverwrite

---

tests/Common/BranchComponentTest.php

fix test: be sure that create time of copied row is different

---

src/Keboola/StorageApi/S3Uploader.php

Jira: PS-3095
Explicitly call PHP garbage collection between uploads of parts of file in multi part upload in S3Uploader.
See https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/s3-multipart-upload.html
in part **Manual Garbage Collection Between Part Uploads**
Not sure if this can be tested somehow :)

PS-3095: manually call GC in S3 multipart file upload

---

composer.json
tests/ClientTestCase.php

Jira: KBC-2177
---
Forkol som libku ktora to mala implementovane a len som zmenil https://github.com/keboola/phpunit-retry-annotations/commit/7e0422f073073d06848166396448810a509664ce aby to robilo defaultne retry 2x. Pridal som som sem este commit kde to sa to da otestovat ze to robi retry to potom zmazem https://github.com/keboola/storage-api-php-client/pull/760/commits/a74d68b67a4b984ceea408e2cd998506d6837ee9
1. `docker-compose run --rm dev composer install`
2. `source ./set-env.sh &&  docker-compose run --rm dev vendor/bin/phpunit --testsuite common`  - spusti len jeden test ktory nahodne failuje v logu je vidiet ze to urobi retry a test prejde ked sa to podari v dvoch retryoch
3. `source ./set-env.sh &&  docker-compose run --rm dev …

Try retry lib

---

src/Keboola/StorageApi/Client.php

https://keboola.slack.com/archives/CQB468K63/p1645717611035819
https://keboola.zendesk.com/agent/tickets/21409
Stejne reseni se delalo tu: https://github.com/keboola/storage-api-php-client/pull/739
Snazi se stahnout 12GB soubor pres IM z S3, pada na timeoutu po necelych 6GB. Timeout chyti retry a vysledek je job, ktery failne po ~90 minutach s errorem, ze request timeout 120sec :) 
Zaroven jsem upravil i timeout pro upload, aby to bylo v obou smerech totozne.

Increase S3 download/upload timeout

---

.gitignore
phpunit-retry.xml.dist

Jira: KBC-XXX
---
Urobim composer update na mastru
1. Ak si checkoutnem tuto branch testy musia stale robit retry 3x 
2. vytvorim si novy file z `phpunit-retry.xml.dist` a pomenujem ho `phpunit-retry.xml` ked spustim teraz testy neurobi to retry ani jeden krat. 
3. mozem si lubovolne upravit pocet retry pre lokal.
Rad by som potom ten fork nejak prisposobil k obrazu nasmu akoze pridat phpcs nase a podobne veci. Ale chcel som teraz sprijemnit tu pracu s tim zalozil by som si na to task do buduceho sprintu.

add phpunit-retry.xml.dist as teplate to local dev

---

composer.json

Jira: https://keboola.atlassian.net/browse/PS-3279
Related to https://github.com/keboola/kbc-manage-api-php-client/pull/185
Allow using with Guzzle 7 & Symfony 6 components.
There should be no BC in Symfony components. Guzzle has some breaking changes (https://github.com/guzzle/guzzle/blob/7.0.0/UPGRADING.md#60-to-70) but everything seems to work for me so far.

PS-3279 Support Guzzle 7, Symfony 6

---

phpstan-baseline.neon
tests/Common/StatsTest.php

Jira: KBC-2538
MainPR: https://github.com/keboola/connection/pull/3704
---

test runId with the same parent runId do not return parent stats

---

tests/Backend/CommonPart1/CreateTableTest.php

Inc 6455
test for snflk only. There is no change in connection for other backends. Problem is that we run this test against other backends even they are not optimized for it yet.

Test for snflk only.

---

src/Keboola/StorageApi/Client.php
src/Keboola/StorageApi/HandlerStack.php
tests/Common/ExceptionsTest.php

Jira: https://keboola.atlassian.net/browse/PS-3719
Replaces: https://github.com/keboola/storage-api-php-client/pull/863
Puvodne navrhovanou variantu s tim posilat to do logu jsme nakonec zavrhli, protoze by se tam pak objevovaly i requesty, kde se ocekava, ze muze failnout (zkus neco fetchnout z API a pokud to nexistuje, zalozi se to apod.). Truncatovani nejde uplne vypnout, ale nastavil jsem tam odhadem max. delku 1MiB, to by mohlo byt dost pro jakoukoliv rozumnou reponse.
Soucasti je rozsireni configu klienta o `handler` parametr, kterym jde procpat vlastni Guzzle handler, aby slo v testech mockovat response.

PS-3719 Do not truncate error response inside thrown exception

---

tests/Backend/Mixed/SharingTest.php
tests/Backend/Mixed/StorageApiSharingTestCase.php

Jira: KBC-2718
Connection https://github.com/keboola/connection/pull/3910

Kbc 2718 app err when linked bucket already exist

---

tests/Common/MaintenanceTest.php

Jira: KBC-2866
maintenance page test will be skipped because maintenance URL won't be defined for new e2e yet -> https://keboola.atlassian.net/browse/KBC-2953

KBC-2866 skip maintenance url page

---

tests/Common/ComponentsTest.php

Jira: KBC-3024
Connection: https://github.com/keboola/connection/pull/4053

KBC-3024 empty string configuration is considered as null

---

tests/Backend/Workspaces/Backend/RedshiftWorkspaceBackend.php

Po [posledni uprave](https://github.com/keboola/storage-api-php-client/pull/916/commits/e1e6629db495e3b69d9696653d7b28be303537d1) spadly testy pro Redshift:
```
13:16:10-UTC - paratest-backend-redshift-part-1   -	There were 2 errors:
13:16:10-UTC - paratest-backend-redshift-part-1   -	
13:16:10-UTC - paratest-backend-redshift-part-1   -	1) Keboola\Test\Backend\Workspaces\LegacyWorkspacesRedshiftTest::testLoadedPrimaryKeys
13:16:10-UTC - paratest-backend-redshift-part-1   -	assert(): assert($row[$default_***] !== null) failed
13:16:10-UTC - paratest-backend-redshift-part-1   -	
13:16:10-UTC - paratest-backend-redshift-part-1   -	/code/tests/Backend/Workspaces/Backend/RedshiftWorkspaceBackend.php:184
13:16:10-UTC - paratest-backend-redshift-part-1   - …
```

fix new phpstan: instead of assert force correct type

---

tests/Backend/CommonPart1/CreateTableWithConfigurationTest.php
tests/Backend/CommonPart1/TableWithConfigurationLoadFromWorkspaceTest.php
tests/Backend/CommonPart1/TableWithConfigurationLoadTest.php

Jira: KBC-3052
Connection: https://github.com/keboola/connection/pull/4091
App: https://github.com/keboola/app-custom-query-manager/pull/5
Client: https://github.com/keboola/storage-api-php-client/pull/946

KBC-3052 timestamp missing from generated queries

---

tests/Backend/WorkspaceCredentialsAssertTrait.php

Jira: KBC-XXX
Pridavam fix na BQ WS pretoze to zacalo failovat s inym kodom na testingu, obvinujem trochu ze testing je na to moc rychly ked zoberiem token a pustim to z lokalu voci testingu tak to preslo. Tak som to upravil ze to mozu byt dva error kodu.
Preslo to tu https://dev.azure.com/keboola-dev/Connection%20build/_build/results?buildId=28730&view=results

fix failing tests

---

phpstan-baseline.neon
tests/Backend/CommonPart1/AlterTableTest.php

Jira: TER-59
table utils: https://github.com/keboola/php-table-backend-utils/pull/91
Connection: https://github.com/keboola/connection/pull/4136
SAPI tests: https://github.com/keboola/storage-api-php-client/pull/964
TD Driver: https://github.com/keboola/php-storage-driver-teradata/pull/51
Common driver: https://github.com/keboola/php-storage-driver-common/pull/24
[TER-59]: https://keboola.atlassian.net/browse/TER-59?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Enable PK tests for TD and BQ

---

phpstan-baseline.neon
tests/Backend/CommonPart1/BucketsTest.php
tests/Backend/CommonPart1/CreateTableWithConfigurationTest.php
tests/Backend/CommonPart1/MigrateTableWithConfigurationTest.php
tests/Backend/CommonPart1/RegisterBucketTest.php
tests/Backend/CommonPart1/TableWithConfigurationLoadFromWorkspaceTest.php
tests/Backend/CommonPart1/TableWithConfigurationLoadTest.php
tests/Backend/FileWorkspace/WorkspacesTest.php
tests/Backend/Mixed/SharingTest.php
tests/Backend/MixedSnowflakeExasol/SharingTest.php
tests/Backend/MixedSnowflakeSynapse/SharingTest.php
tests/Backend/Snowflake/CloneIntoWorkspaceTest.php
tests/Backend/Synapse/CreateTableTest.php
tests/Backend/Workspaces/LegacyWorkspacesLoadTest.php
tests/Backend/Workspaces/MetadataFromSnowflakeWorkspaceTest.php
tests/Backend/Workspaces/WorkspacesTest.php
tests/Common/BranchEventsTest.php
tests/Common/BranchMetadataTest.php
tests/Common/BranchWorkspacesTest.php
tests/Common/ComponentsEventsTest.php
tests/Common/ComponentsTest.php
tests/Common/ConfigurationMetadataTest.php
tests/Common/DevBranchesTest.php
tests/Common/EventsAttachmentTest.php
tests/Common/EventsTest.php
tests/Common/SearchComponentsConfigurationsTest.php
tests/Common/TokensShareTest.php
tests/Utils/EventTesterUtils.php
tests/Utils/EventsQueryBuilder.php
tests/Utils/EventsQueryBuilderTest.php

Jira: CT-791
Pridavam novu metodu ktora robi retry pokial sa nesplni assert v anonymnej metode ktoru posielam do tejto metody (je tam obmedzeny pocet retries). Dalej tuto metodu pouzivam na miestach kde testujeme eventy co by malo pomoct tomu aby testy padali na tom ze eventu nenajde alebo najde na miesto pozadovanej dummy eventu.  
Tu presiel tag kde nepadli ziadne testy na eventach https://dev.azure.com/keboola-dev/Connection%20build/_build/results?buildId=29885&view=logs&j=ae13dfb3-00c3-5552-9b00-63e26024fcba&t=b561c83b-ef20-59aa-7385-caea4d938bd8

Make event assertions robust

---

tests/Backend/Workspaces/Backend/BigQueryClientHandler.php
tests/Backend/Workspaces/Backend/BigqueryWorkspaceBackend.php

Jira: CT-894
KBC: XXX
V sapi klientovy v testoch sa pouziva tiez bq client a stane sa v testoch obcas ze BQ trva okial sa prejavia nejake permission tak pridavam vlastny retry handler. Skusi to 3x a potom vypise pripadne tu chybu

Add retry when bq request fails

---

apiary.apib
tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php

Jira: CT-910
- Check that you can register a bucket including external table. 
- Add `tableKind` to api doc
Storage backend: https://github.com/keboola/storage-backend/pull/70 
Connection: https://github.com/keboola/connection/pull/4401
SAPI: https://github.com/keboola/storage-api-php-client/pull/1060

CT-910 register external table

---

tests/Backend/CommonPart1/BucketsTest.php
tests/ClientProvider/TestSetupHelper.php

Jira: CT-1138
KBC: XXX
Tag presiel [tu](https://dev.azure.com/keboola-dev/Connection%20build/_build/results?buildId=39296&view=results)  komplet zeleny.
Changes:
- typo
- zacal som reusovat branche
- unikatne nazvy bucketov pre paratesty

Ct 1138 dont create new brach every run

---

src/Keboola/StorageApi/GCSUploader.php
tests/ClientTestCase.php

Jira: GCP-408
KBC: XXX
---
Testoval sem to tak, že sem na GCSUploader L143 (hned za upload všech slices)
Vložil tento kód aby podělal některý slice.
```php
$blobToCorrupt = $preparedSlices[array_rand($preparedSlices)];
$this->logger->warning(sprintf('Corrupting blob %s', $blobToCorrupt));
$this->gcsClient->bucket($bucket)->upload(
fopen('data://text/plain;base64,' . base64_encode('test'), 'rb'),
[
'name' => $blobToCorrupt,
]
);
```

GCP-408 GCS reupload

---

tests/Backend/Synapse/ImportTypedTableTest.php

Jira: CT-XXX
KBC: XXX
Synapse zmenil chybovu hlasku, lokalne mi to nepada pretoze je to iny server ako na testingu

change err msg

---

apiary.apib
tests/Backend/Bigquery/TableDefinitionOperationsTest.php
tests/Backend/Exasol/TableDefinitionOperationsTest.php
tests/Backend/Snowflake/ImportTypedTableTest.php
tests/Backend/Synapse/CreateTableTest.php
tests/Backend/Teradata/TableDefinitionOperationsTest.php

Jira: CT-1332
KBC:  https://github.com/keboola/connection/pull/4912
V par testoch som zmazal to posielanie prazdneho pola, nech sa to testuje ;)

CT-1332 PK is not required anymore

---

tests/Backend/CommonPart1/BucketsTest.php
tests/Backend/CommonPart1/CreateTableTest.php
tests/Common/MetadataTest.php

Jira: CT-1326
KBC: https://github.com/keboola/connection/pull/4913

[CT-1326] Get table stringId with explode with limit=3

---

apiary.apib
src/Keboola/StorageApi/Client.php
tests/Backend/CommonPart1/ImportExportCommonTest.php

Jira: CT-1118
Connection PR: https://github.com/keboola/connection/pull/4902
SAPI PR: https://github.com/keboola/storage-api-php-client/pull/1296
StorageBackend PR: https://github.com/keboola/storage-backend/pull/136
Driver PR: https://github.com/keboola/php-storage-driver-bigquery/pull/123

CT-1118 Add and test import with importAsNull

---

tests/Backend/Bigquery/TableDefinitionOperationsTest.php
tests/Backend/Snowflake/TableDefinitionOperationsTest.php

Jira: CT-1348
KBC: https://github.com/keboola/connection/pull/4931

CT-1348 test dataSizeBytes, rowsCount on empty table

---

tests/Backend/Bigquery/TableDefinitionOperationsTest.php
tests/Backend/Bigquery/TableExporterTest.php
tests/Backend/Bigquery/TestExportDataProvidersTrait.php

Jira : [CT-1331](https://keboola.atlassian.net/browse/CT-1331)
KBC: https://github.com/keboola/connection/pull/4919
BQ driver: https://github.com/keboola/php-storage-driver-bigquery/pull/126 ✅
SAPI: https://github.com/keboola/storage-api-php-client/pull/1308
jen fixuju testy a testuju ten usecase
[CT-1331]: https://keboola.atlassian.net/browse/CT-1331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CT-1331 do not expect error when having no datatype anymore

---

tests/Backend/CommonPart1/BranchStorageTest.php
tests/Common/DevBranchesTest.php

Jira: CT-1238
KBC: https://github.com/keboola/connection/pull/4834

CT-1238 fix expected order of keys

---

phpstan-baseline.neon
src/Keboola/StorageApi/Client.php
src/Keboola/StorageApi/HandlerStack.php
tests-unit/Client/MaintenanceTest.php

https://keboola.atlassian.net/browse/PST-1006
Pridani nove config option `retryOnMaintenance`, default `true` pro zachvani BC. Pokud je nastavene na `false`, nedela se pri `503` response retry.
Pokud je projekt disablovany, nechceme se v `job-queue-daemon` zdrzovat retries. Takovy projekt nam staci proste skipnout a vratime se k nemu v dalsi iteraci.

PST-1006 Allow disabling retries on 503 Maintenance response

---

tests/Backend/SOX/PullTableTest.php

php-datatypes starts return INTEGER instead of INT64

---

apiary.apib
tests/Common/IndexTest.php

Jira: [CT-1671](https://keboola.atlassian.net/browse/CT-1671)
KBC: https://github.com/keboola/connection/pull/5185
[CT-1671]: https://keboola.atlassian.net/browse/CT-1671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CT-1671 webalize/column-names now do not validate column names

---

apiary.apib
tests/Backend/Snowflake/TypedTableWorkspacesLoadTest.php

Jira: CT-1688
KBC:  https://github.com/keboola/connection/pull/5204

test changeSince/until ws load

---

apiary.apib

- changedSince and until support only unix timestamp  in case of table export and load data to ws
- add changed options to branch endpoint
Jira: CT-XXX
KBC: XXX

fix doc changed

---

apiary.apib

Jira: CT-1867
KBC: XXX
---
just note that bucket description as field is deprecated

Deprecate bucket description

---

apiary.apib
tests/Backend/CommonPart1/BucketsTest.php
tests/Backend/MixedSnowflakeBigquery/SharingTest.php

Jira: [CT-1849](https://keboola.atlassian.net/browse/CT-1849)
KBC: https://github.com/keboola/connection/pull/5363
[CT-1849]: https://keboola.atlassian.net/browse/CT-1849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CT-1849 - bucket lastShareChangeDate update test

---

apiary.apib

Jira: [CT-1362](https://keboola.atlassian.net/browse/CT-1362)
KBC: XXX
[CT-1362]: https://keboola.atlassian.net/browse/CT-1362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Description of treatValuesAsNull

---

tests/Backend/ExternalBuckets/SnowflakeBucketsRefreshTablesInformationTest.php
tests/Backend/ExternalBuckets/SnowflakeRegisterExternalBucketInSecureDataShareTest.php

Jira: [DMD-33](https://keboola.atlassian.net/browse/DMD-33)
KBC: https://github.com/keboola/connection/pull/5415
[DMD-33]: https://keboola.atlassian.net/browse/DMD-33?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DMD-33 - SDS bucket refresh test update

---

src/Keboola/StorageApi/Client.php
src/Keboola/StorageApi/Components.php
src/Keboola/StorageApi/Downloader/GcsClientFactory.php
src/Keboola/StorageApi/GCSUploader.php
src/Keboola/StorageApi/HandlerStack.php
src/Keboola/StorageApi/S3Uploader.php
tests/Backend/Workspaces/ParallelWorkspacesTestCase.php
tests/StorageApiTestCase.php
tests/Utils/EventTesterUtils.php

Vzdalene related k https://keboola.atlassian.net/browse/PST-883
Explicitni nullable oznaceni vsech argumentu, kde je default `null`. V PHP 8.4 je tohle povazovany za deprecated.
```
Deprecated: {closure:Keboola\StorageApi\HandlerStack::createDefaultDecider():55}(): Implicitly marking parameter $response as nullable is deprecated, the explicit nullable type must be used instead in /code/apps/service-container/vendor/keboola/storage-api-client/src/Keboola/StorageApi/HandlerStack.php on line 62
Call Stack:
0.0002     527552   1. {main}() /code/apps/service-container/vendor/bin/phpunit:0
0.0004     540136   2. include('/code/apps/service-container/vendor/phpunit/phpunit/phpunit') /code/apps/service-container/vendor/bin/phpunit:122
0.0081    2965216   3. PHPUnit\TextUI\Command::main($exit = …
```

fix: Make arguments with default `null` nullable explicitly

---

apiary.apib
src/Keboola/StorageApi/Workspaces.php
tests/Backend/Bigquery/WorkspacesQueryTest.php
tests/Backend/Snowflake/WorkspacesQueryTest.php

- Calls endpoint "workspaces/{$id}/query" with custom Snowflake query.
Jira: CT-2016
KBC: keboola/connection#5559

CT-2016 New Workspaces::executeQuery

---

apiary.apib
tests/Backend/CommonPart1/DeleteRowsTest.php

Jira: CT-1974
KBC:  https://github.com/keboola/connection/pull/5598

CT-1974 Remove support for `valuesByTableInStorage` option.

---

Dockerfile
composer.json
docker-compose.yml
src/Keboola/StorageApi/Components.php
src/Keboola/StorageApi/WorkspaceLoginType.php
src/Keboola/StorageApi/Workspaces.php
src/Keboola/StorageApi/Workspaces/ResetCredentialsRequest.php
tests/Backend/Snowflake/WorkspacesLoginTypesTest.php
tests/Backend/Workspaces/WorkspacesTest.php
tests/WorkspaceLoginTypeTest.php

https://keboola.atlassian.net/browse/PAT-258
Based on https://github.com/keboola/storage-api-php-client/pull/1495
Od generovani key-pair primo v SAPI clientovi jsem nakonec upustil. V nekterych situacich (staging workspace) by se to hodilo, jindy (SQL sandbox) zas ne a nechtel jsem to delat tak polomagicky nekdy.
Nechal jsem ale vytazeni te `decorateWorkspaceCreateWithCredentials` metody a pouziti v `Components::createConfigurationWorkspace()` i `Workspaces::createWorkspace()`, aby byly jednotny pravidla ohledne generovani password.
Jelikoz jsem neintegroval generovani key-pair, nebylo potreba zaviset na `keboola/key-generator` a tim padem ani zvedat min. podporovanou verzi PHP a neni tedy potreba delat major release :tada: 
Testy si @zajca rikal, ze bys poresil?

[workspaces] Unify loghinType conditions, resetCredentials method

---

tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
tests/Backend/Workspaces/WorkspacesSnowflakeTest.php

Jira: −
KBC: −
**Fixed PHPStan:**
- BigqueryRegisterBucketTest
- Broke by google/protobuf v4.30.2 → v4.31.0 update
- WorkspacesSnowflakeTest
- Broke by keboola/php-csv-db-import 6.0.0 → 6.1.0 update
```
Error: Cannot access an offset on Google\Protobuf\Internal\RepeatedField.
Error: Parameter #1 $value of method Keboola\Db\Import\Snowflake\AbstractConnection::quoteIdentifier() expects string, int|string|null given.
------ -------------------------------------------------------------------- 
Line   tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php        
------ -------------------------------------------------------------------- 
1483   Cannot access an offset on Google\Protobuf\Internal\RepeatedField.  
------ -------------------------------------------------------------------- …
```

Fix: New versions of libs broke PHPStan

---

Dockerfile

Jira: −
KBC: −
---
Because `apt update` stopped working. 
Because Buster repositories were moved to archive - https://lists.debian.org/debian-devel-announce/2025/06/msg00001.html.
And PHP image for Buster is no longed updated (last push 2 years ago) - https://hub.docker.com/layers/library/php/8.1-cli-buster/images/sha256-f1d4b7f30ea4a06fd9dedb26c43ab18a698bccde5c3476293afeed2dbc81a290.
Which means that `/etc/apt/sources.list` in PHP image contains wrong URLs to repositories. They start with `deb.` but should already start `archive.`.
So the easiest way how to solve it was to upgrade to Bullseye which use in other PHP app and libs.
**What …

chore(debian): Upgrade to Debian 11 (Bullseye)

---

src/Keboola/StorageApi/Options/BackendConfiguration.php

https://keboola.atlassian.net/browse/PAT-402
Change `BackendConfiguration` properties to `public readonly`. There is `public getBackendConfiguration()` method on the `Client`, but no way to get to properties values once the object is created (except exporting it as a JSON string).

feat: Make BackendConfiguration properties accessible from outside
