- tests/Backend/CommonPart1/TableWithConfigurationLoadFromWorkspaceTest.php
Jira: KBC-3012
Connection: https://github.com/keboola/connection/pull/4050 (full load)
> KBC-3012 support incremental load from workspace

- src/Keboola/StorageApi/Client.php
- src/Keboola/StorageApi/Options/BackendConfiguration.php
Jira: KBC-2988
KBC: https://github.com/keboola/connection/pull/4054
> KBC-2988 add BackendConfiguration

- tests/Common/ConfigurationRowTest.php
Jira: KBC-3028
Connection: https://github.com/keboola/connection/pull/4056
> KBC-3028 test empty string as configuration id

- tests/Backend/CommonPart1/TableWithConfigurationLoadFromWorkspaceTest.php
- tests/Backend/CommonPart1/TableWithConfigurationLoadTest.php
Jira: KBC-3025
Connection: https://github.com/keboola/connection/pull/4058
> Tables with Configuration - rename variables, refresh queries

- phpunit.xml.dist
- tests/Backend/Mixed/StorageApiSharingTestCase.php
- tests/Backend/MixedSnowflakeExasol/SharingTest.php
- tests/Backend/MixedSnowflakeSynapse/SharingTest.php
- tests/Backend/MixedSnowflakeTeradata/SharingTest.php
- tests/Backend/MixedTeradata/SharingTest.php
- tests/Backend/WorkspaceConnectionTrait.php
Jira: https://keboola.atlassian.net/browse/TER-56
connection: https://github.com/keboola/connection/pull/4062
> TER-56 Init TD sharing tests

- tests/Backend/CommonPart1/CreateTableTest.php
Fixujem jeden test co failuje na BQ
> Bigquery does not fail on invalid data

- tests/Backend/CommonPart1/CreateTableTest.php
Jira: [BIG-14](https://keboola.atlassian.net/browse/BIG-14)
MainPR: https://github.com/keboola/connection/pull/4076
> test  datapreview

- phpunit.xml.dist
- tests/Backend/Bigquery/TableDefinitionOperationsTest.php
- tests/StorageApiTestCase.php
MainPR:: https://github.com/keboola/connection/pull/4074
https://keboola.atlassian.net/browse/BIG-28
> Roman create typed table

- phpunit.xml.dist
Jira: BIG-33
KBC: https://github.com/keboola/connection/pull/4077
> BIG-33 BQ add ExportSimpleTest

- apiary.apib
- phpstan-baseline.neon
- phpunit.xml.dist
- tests/Backend/WorkspaceConnectionTrait.php
- tests/Backend/WorkspaceCredentialsAssertTrait.php
- tests/Backend/Workspaces/Backend/BigqueryWorkspaceBackend.php
- tests/Backend/Workspaces/Backend/WorkspaceBackend.php
- tests/Backend/Workspaces/Backend/WorkspaceBackendFactory.php
- tests/Backend/Workspaces/ParallelWorkspacesTestCase.php
- tests/Backend/Workspaces/WorkspacesTest.php
Jira: BIG-45
MainPr: https://github.com/keboola/connection/pull/4083
> Test create/drop WS for bigquery

- apiary.apib
- tests/Backend/WorkspaceCredentialsAssertTrait.php
- tests/Backend/Workspaces/WorkspacesTest.php
Jira: https://keboola.atlassian.net/browse/BIG-47
MainPr: https://github.com/keboola/connection/pull/4084
> Roman reset ws pass

- apiary.apib
- phpunit.xml.dist
- tests/Backend/Snowflake/ImportTypedTableTest.php
- tests/Backend/Synapse/ImportTypedTableTest.php
- tests/Backend/Teradata/ImportTypedTableTest.php
- tests/Backend/Teradata/TableDefinitionOperationsTest.php
Jira: TER-60
Connection: https://github.com/keboola/connection/pull/4080
> TER-60 tests for typed table in Teradata

- tests/Backend/Workspaces/MetadataFromSnowflakeWorkspaceTest.php
Jira: KBC-3043
KBC: https://github.com/keboola/connection/pull/4085
> KBC-3043 fix expected metadata for snowflake storage-types

- tests/Backend/Snowflake/TableDefinitionOperationsTest.php
- tests/Backend/Workspaces/MetadataFromSnowflakeWorkspaceTest.php
Reverts: #939 #937 
viz. `prod_24_7____inc_8064`
> Kbc 3043 revert

- Dockerfile
> Use new source for ODBC driver for Exasol

- tests/Backend/CommonPart1/BucketsTest.php
- tests/Backend/CommonPart1/CreateTableTest.php
- tests/Backend/CommonPart1/ExportParamsTest.php
> fail on exception not thrown

- tests/Backend/CommonPart1/ExportParamsTest.php
Jira: -
tu signoff
https://keboola.slack.com/archives/C01DQ9VRQK0/p1669731443337089
tady resime, ze ten test tam nema byt
https://keboola.slack.com/archives/C02EJLG5421/p1669731115416109
a tady je to v team-connection
https://keboola.slack.com/archives/CFVRE56UA/p1669720380134239
> Remove export test for removed feature

- phpunit.xml.dist
- tests/Backend/Workspaces/BigqueryWorkspacesUnloadTest.php
> Add test BQ unload from WS

- apiary.apib
Doplnam nejake veci do dokumentacie ohladne Bigquery
> add bq to typed tables

- phpstan-baseline.neon
- tests/Backend/Snowflake/TableDefinitionOperationsTest.php
- tests/Backend/Workspaces/Backend/BigqueryWorkspaceBackend.php
- tests/Backend/Workspaces/Backend/ExasolWorkspaceBackend.php
- tests/Backend/Workspaces/Backend/RedshiftWorkspaceBackend.php
- tests/Backend/Workspaces/Backend/SnowflakeWorkspaceBackend.php
- tests/Backend/Workspaces/Backend/SynapseWorkspaceBackend.php
- tests/Backend/Workspaces/Backend/TeradataWorkspaceBackend.php
- tests/Backend/Workspaces/Backend/WorkspaceBackend.php
- tests/Backend/Workspaces/MetadataFromSnowflakeWorkspaceTest.php
- tests/Backend/Workspaces/WorkspacesUnloadTest.php
Reverts keboola/storage-api-php-client#940
KBC: https://github.com/keboola/connection/pull/4092
> Revert "Kbc 3043 revert"

- phpstan-baseline.neon
- phpunit.xml.dist
- tests/Backend/CommonPart1/ExportParamsTest.php
- tests/Backend/CommonPart1/ImportExportCommonTest.php
- tests/Backend/CommonPart1/TableExporterTest.php
- tests/Backend/CommonPart2/MetricsTest.php
- tests/Backend/CommonPart2/SlicedImportsTest.php
- tests/Backend/CommonPart2/SlicedImportsWithSlicedUploadsTest.php
- tests/Backend/CommonPart2/SystemColumnsTest.php
- tests/Backend/Exasol/ExasolImportExportCommonTest.php
Jira: TER-71
Connection https://github.com/keboola/connection/pull/4089 
Add Common1 and Common2 parts to TD suite
> TER-71 allow inc load in sapi

- apiary.apib
- phpunit.xml.dist
- tests/Backend/CommonPart1/DataPreviewLimitsTest.php
- tests/Backend/CommonPart1/ExportParamsTest.php
Jira: KBC-18
driver-teradata: https://github.com/keboola/php-storage-driver-teradata/pull/44
backend-utils: https://github.com/keboola/php-table-backend-utils/pull/86
---
> TER-18 table preview

- tests/Backend/WorkspaceConnectionTrait.php
- tests/Backend/Workspaces/Backend/BigqueryWorkspaceBackend.php
MainPR: https://github.com/keboola/connection/pull/4106
> Roman fix ws credentials as obj

- phpunit.xml.dist
- tests/Backend/MixedSnowflakeBigquery/SharingTest.php
Jira: [BIG-38](https://keboola.atlassian.net/browse/BIG-38), [BIG-39](https://keboola.atlassian.net/browse/BIG-39)
MainPr: https://github.com/keboola/connection/pull/4098
> Add snflk/bq mixed suite

- tests/File/AwsFileTest.php
- tests/File/AzureFileTest.php
- tests/File/CommonFileTest.php
- tests/File/GcsFileTest.php
Jira: KBC-3069
Main PR: https://github.com/keboola/connection/pull/4105
> test deleting empty sliced file

- apiary.apib
- tests/Backend/Workspaces/ParallelWorkspacesTestCase.php
- tests/Backend/Workspaces/WorkspacesLoadTestReadOnly.php
Jira: KBC-3054
Code: https://github.com/keboola/connection/pull/4109
Feature disabled:
(fucking tooltip - je pod tím failed)
Feature enabled:
> KBC-3054 add param ro enabled create read ws default based on existence of feature

- apiary.apib
- phpunit.xml.dist
- tests/Backend/CommonPart1/AlterTableTest.php
Jira: BIG-36
Main PR: https://github.com/keboola/connection/pull/4127
> BQ test alter table

- apiary.apib
- phpunit.xml.dist
- tests/Backend/CommonPart1/AlterTableTest.php
Jira: TER-58 
Table utils: https://github.com/keboola/php-table-backend-utils/pull/88
Common: https://github.com/keboola/php-storage-driver-common/pull/21
TD Driver: https://github.com/keboola/php-storage-driver-teradata/pull/49
BQ Driver: https://github.com/keboola/php-storage-driver-bigquery/pull/27 
Connection: https://github.com/keboola/connection/pull/4120
SAPI: https://github.com/keboola/storage-api-php-client/pull/960
> TER-58 Enable Alter test but skip PKs

- phpunit.xml.dist
- tests/Backend/Bigquery/TableDefinitionOperationsTest.php
- tests/Backend/CommonPart1/DataPreviewLimitsTest.php
- add new column
main pr: https://github.com/keboola/connection/pull/4134
> enable more typed table tests for BQ

- apiary.apib
- src/Keboola/StorageApi/Components.php
- tests/Backend/Workspaces/BranchComponentsWorkspacesTest.php
- tests/Backend/Workspaces/ComponentsWorkspacesTest.php
Jira: KBC-3081
MainPr: https://github.com/keboola/connection/pull/4140
> Kbc 3081 async ws configuration create

- apiary.apib
- tests/Backend/Workspaces/BigqueryWorkspacesUnloadTest.php
- tests/Backend/Workspaces/TeradataWorkspacesUnloadTest.php
Jira: TER-53 
Pridal jsem test, co checkne, ze do BQ/TD fakt nejde loadovat a vyhodi to spravnou chybu. Pak jsem nasel opustenou tridu TeradataWorkspacesUnloadTest tak jsem ji privedl k zivotu. Vic testu -> vic toho muze spadnout 🎉 
> TER-53 skip ws load and enable tests

- tests/Backend/Bigquery/FulltextSearchTest.php
> Fix BQ testFindDataByFulltext

- apiary.apib
- src/Keboola/StorageApi/Client.php
- tests/Backend/CommonPart1/DeleteRowsTest.php
Jira: TER-87
Connection: https://github.com/keboola/connection/pull/4141
> TER-87 delete rows - supports whereFilters

- phpunit.xml.dist
- tests/Backend/CommonPart2/SlicedImportsTest.php
- tests/Backend/CommonPart2/SlicedImportsWithSlicedUploadsTest.php
> BIG-105 delete rows

- apiary.apib
Predchadzal som este docku a nasiel par miest kde chybali veci ohladne BQ
BIG-106
> doc - add supported datatypes for export and data preview

- phpstan-baseline.neon
- phpunit.xml.dist
- tests/Backend/CommonPart1/DeleteRowsTest.php
- tests/Backend/CommonPart2/SlicedImportsTest.php
- tests/Backend/CommonPart2/SlicedImportsWithSlicedUploadsTest.php
Jira: TER-87
Connection: https://github.com/keboola/connection/pull/4148
Dependency - BQ testy: https://github.com/keboola/storage-api-php-client/pull/970
> TER-87 delete rows - multiple whereFilters

- apiary.apib
- phpstan-baseline.neon
- src/Keboola/StorageApi/Client.php
- tests/Backend/CommonPart1/DeleteRowsTest.php
Jira: TER-87
Connection: https://github.com/keboola/connection/pull/4158
> Fix: Table rows delete: split call with query and form-data

- tests/File/GcsFileTest.php
Jira: KBC-3100
MainPR: https://github.com/keboola/connection/pull/4153
> Test delete not sliced prepared file

- tests/Backend/Workspaces/BranchComponentsWorkspacesTest.php
- tests/Backend/Workspaces/ComponentsWorkspacesTest.php
Jira: CT-781
Code: https://github.com/keboola/connection/pull/4156
> CT-781 Fix booleanish validator usage for RO role

- tests/Backend/Workspaces/ComponentsWorkspacesTest.php
> CT-781 only test RO storage access on snowflake backends

- .github/PULL_REQUEST_TEMPLATE.md
> Update PR template CT and link to KBC

- apiary.apib
> CT-774 add HTTP headers to Apiary

- tests/Backend/Synapse/CreateTableTest.php
- tests/Backend/Workspaces/SnowflakeDynamicBackendsTest.php
- tests/Common/ComponentsTest.php
- tests/Common/SearchTablesTest.php
Jira: CT-786
KBC: https://github.com/keboola/connection/pull/4145
> CT-786 update assertions for Invalid request message

- src/Keboola/StorageApi/Client.php
To be able to tell it from legacy client on Qv1
Jira: N/A
KBC: N/A
https://keboola.slack.com/archives/CFVRE56UA/p1674723303008549?thread_ts=1674661088.142849&cid=CFVRE56UA
> Update version in Client

- apiary.apib
- phpunit.xml.dist
- tests/Backend/CommonPart1/RegisterBucketTest.php
- tests/Backend/ExternalBuckets/BaseExternalBuckets.php
- tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
- tests/Backend/ExternalBuckets/TeradataRegisterBucketTest.php
- tests/StorageApiTestCase.php
Jira: TER-99
Common: https://github.com/keboola/php-storage-driver-common/pull/32
TD driver: https://github.com/keboola/php-storage-driver-teradata/pull/55
Connection: https://github.com/keboola/connection/pull/4160
SAPI https://github.com/keboola/storage-api-php-client/pull/981
> TER-99 external buckets for TD

- tests/Backend/CommonPart1/CreateTableTest.php
- tests/Backend/CommonPart2/SnapshottingTest.php
- tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
> Fix events for snflk ext buckets

- src/Keboola/StorageApi/Client.php
- tests/File/CommonFileTest.php
Jira: https://keboola.atlassian.net/browse/PST-410
> Download files - handle not found errors from cloud providers

- tests/Backend/CommonPart1/MigrateTableWithConfigurationTest.php
- tests/Backend/CommonPart1/TableWithConfigurationLoadTest.php
- tests/Backend/TableWithConfigurationUtils.php
Jira: CT-789
KBC: https://github.com/keboola/connection/pull/4179
> CT-789 move config under parameters

- tests/Backend/CommonPart1/CreateTableWithConfigurationTest.php
> CT-789 nest config under parameters

- phpunit.xml.dist
- tests/Backend/CommonPart1/CreateTableTest.php
- tests/Backend/CommonPart2/SimpleAliasTest.php
Jira: TER-94
connection: https://github.com/keboola/connection/pull/4174
> Split TD suites

- tests/Common/StatsTest.php
> CT-832 fix test expectation

- tests/Backend/CommonPart1/TableWithConfigurationLoadFromWorkspaceTest.php
Jira: CT-XXX
KBC: XXX
Myslel som si ze tento sposob testov ktory tam bol bude stacit, ale testy na tom teraz presli tak som to upravil aj tu.
> Use new event tests

- apiary.apib
- src/Keboola/StorageApi/Options/Metadata/TableMetadataUpdateOptions.php
- tests/Common/MetadataTest.php
This reverts commit 8d6f12ecc82b1aca52089c1dab3f335a478278c9.
Jira: CT-784
KBC: https://github.com/keboola/connection/pull/4205
> CT-784 test numeric column names

- tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
- tests/Backend/ExternalBuckets/TeradataRegisterBucketTest.php
Jira: TER-103
Connection: https://github.com/keboola/connection/pull/4193/files
---
> Ter 103 external bucket drop role

- phpstan-baseline.neon
- phpunit.xml.dist
- tests/Backend/CommonPart1/AlterTableTest.php
- tests/Backend/CommonPart1/CreateTableTest.php
- tests/Backend/CommonPart2/TablesDefinitionCommonTest.php
Jira: TER-89
Connection: https://github.com/keboola/connection/pull/4199
> TER-89 columns limit

- phpstan-baseline.neon
- src/Keboola/StorageApi/Client.php
- tests/Backend/CommonPart1/CreateTableTest.php
- tests/Backend/Mixed/SharingTest.php
- tests/Backend/Mixed/StorageApiSharingTestCase.php
Jira: KBC-2941
Connection: https://github.com/keboola/connection/pull/4112
> KBC-2941 update table uses JSON

- phpstan-baseline.neon
- src/Keboola/StorageApi/Client.php
- tests/Backend/CommonPart2/SimpleAliasTest.php
- tests/Common/SearchComponentsConfigurationsTest.php
Jira: CT-856
Connection: https://github.com/keboola/connection/pull/4115
> CT-856 update table filter use JSON

- src/Keboola/StorageApi/Client.php
Jira: CT-863
KBC: https://github.com/keboola/connection/pull/4215
> CT-863 create snapshot uses JSON

- src/Keboola/StorageApi/Client.php
- tests/Backend/CommonPart1/DeleteRowsTest.php
Jira: CT-858
Connection: https://github.com/keboola/connection/pull/4210
> CT-858 udpate table delete rows use JSON

- apiary.apib
- phpstan-baseline.neon
- src/Keboola/StorageApi/Client.php
Jira: CT-876
KBC: https://github.com/keboola/connection/pull/4212
> CT-876 json create table alias

- src/Keboola/StorageApi/Client.php
- tests/Backend/Mixed/SharingTest.php
Jira: CT-885
Connection: https://github.com/keboola/connection/pull/3984
> CT-885 migrate Buckets to JSON

- phpstan-baseline.neon
- src/Keboola/StorageApi/Workspaces.php
- tests/Backend/FileWorkspace/WorkspacesUnloadTest.php
- tests/Backend/Workspaces/BranchComponentsWorkspacesTest.php
> CT-884 migrate Workspaces to JSON

- phpstan-baseline.neon
- src/Keboola/StorageApi/Client.php
- tests/Backend/Mixed/SharingTest.php
- tests/Backend/MixedSnowflakeBigquery/SharingTest.php
Jira: CT-875 CT-874
KBC: https://github.com/keboola/connection/pull/4226
> CT-875 bucket sharing use JSON

- tests/Backend/Workspaces/Backend/BigQueryClientHandler.php
Jira: CT-XXX
KBC: XXX
Logovanie reties som nenasiel asi pretoze su to paratesty, zvysil by som ten limit  a uvidime.
> maxRetries for BQ up to 10

- phpstan-baseline.neon
- src/Keboola/StorageApi/Client.php
Jira: CT-865
KBC: https://github.com/keboola/connection/pull/4231
> CT-865 post export async json

- tests/Backend/CommonPart1/CreateTableTest.php
- tests/Backend/Workspaces/BranchComponentsWorkspacesTest.php
- tests/Backend/Workspaces/ComponentsWorkspacesTest.php
- tests/Backend/Workspaces/WorkspacesTest.php
> use sync api calls only for snflk

- tests/Backend/CommonPart1/AlterTableTest.php
- tests/Backend/CommonPart1/CreateTableTest.php
- tests/Backend/CommonPart1/ImportExportCommonTest.php
- tests/Backend/CommonPart1/TableExporterTest.php
- tests/Backend/FileWorkspace/WorkspacesTest.php
- tests/StorageApiTestCase.php
> add names to some data providers + reformat them

- tests/Backend/Workspaces/LegacyWorkspacesLoadTest.php
- tests/Utils/EventTesterUtils.php
Jira: CT-886
KBC: -
- increase retry
- initEvents in one tests
last tag https://dev.azure.com/keboola-dev/Connection%20build/_build/results?buildId=31483&view=logs&j=58d3b137-80a0-57e6-9b18-09008e4f22a7&t=56cf3ec5-6d7f-542b-4963-18ae2e0366d6 
> CT-886 more retrys should help build

- phpstan-baseline.neon
- src/Keboola/StorageApi/Client.php
- tests/Backend/Mixed/SharingTest.php
- tests/Backend/Mixed/SharingTestWithTypedTables.php
- tests/Backend/Mixed/StorageApiSharingTestCase.php
- tests/Common/MetadataTest.php
Jira: CT-852
KBC: https://github.com/keboola/connection/pull/4233
> CT-852 update test for native types

- apiary.apib
Jira: CT-546
KBC: XXX
---
Updated sections:
- Tokens
- Buckets
- Tables (except `import-async` - will be done after merge https://github.com/keboola/connection/pull/4237)
---
> CT-546 api docs with json - part 1

- tests/Backend/CommonPart1/ImportExportCommonTest.php
> CT-877 use json for async table import

- src/Keboola/StorageApi/S3Uploader.php
> fix double sprintf

- apiary.apib
Jira: CT-546
KBC: XXX
---
Updated sections:
- workspaces
- events
- metadata
- files
- triggers
- webalize
- dev branches
- components and configurations
- tables/import-async
---
> CT-546 api docs with json - part 2

- apiary.apib
- src/Keboola/StorageApi/Client.php
- tests/Common/EventsTest.php
> Ct 931 create event - use json attributes

- apiary.apib
- tests/Backend/Mixed/SharingTest.php
- tests/Backend/Snowflake/CloneIntoWorkspaceTest.php
Jira: CT-946
KBC: https://github.com/keboola/connection/pull/4287
> PLG CT-946 clone drop timestamp

- tests/Backend/Mixed/SharingTest.php
Jira: CT-412
KBC: https://github.com/keboola/connection/pull/4299
> test sync linked tables display name

- tests/ClientTestCase.php
> uncomment retry

- apiary.apib
- tests/Common/ComponentsTest.php
Jira: CT-342
KBC: https://github.com/keboola/connection/pull/4274
> CT-342 create config from version fails

- phpstan-baseline.neon
- tests/Backend/CommonPart1/TableExporterTest.php
- tests/StorageApiTestCase.php
Jira: CT-XXX
KBC: XXX
---
Upresnuje puvod caste chyby v testech:
Mozna by pomohl `retry`❓ 
---
> fix listJobsByRunId returns array

- phpunit.xml.dist
- tests/Backend/Bigquery/BigqueryTableExporterTest.php
- tests/Backend/Bigquery/TableExporterTest.php
> Ct 943 move bq to own dir

- apiary.apib
- phpstan-baseline.neon
- src/Keboola/StorageApi/Client.php
- tests/Backend/CommonPart1/BucketsTest.php
- tests/Backend/CommonPart2/SnapshottingTest.php
- tests/Common/TablesListingTest.php
- tests/Common/TokensTest.php
Jira: CT-549
KBC: https://github.com/keboola/connection/pull/4260
> CT-549 delete tables attributes

- apiary.apib
- tests/Backend/CommonPart1/CreateTableTest.php
- tests/Backend/Synapse/CreateTableTest.php
- tests/Backend/Synapse/TableDefinitionOperationsTest.php
Jira: CT-550
KBC: https://github.com/keboola/connection/pull/4267
> CT-550 delete deprecated indexedColumns

- phpstan-baseline.neon
- src/Keboola/StorageApi/Client.php
- src/Keboola/StorageApi/Workspaces.php
- tests/Backend/CommonPart1/CreateTableTest.php
- tests/Backend/CommonPart2/MetricsTest.php
- tests/Backend/Redshift/OptimizeTest.php
- tests/Backend/Snowflake/TableExportTest.php
- tests/Backend/Snowflake/TimestampTest.php
- tests/Backend/Workspaces/BigqueryWorkspacesUnloadTest.php
- tests/Backend/Workspaces/ExasolWorkspacesUnloadTest.php
- tests/Backend/Workspaces/SynapseWorkspacesUnloadTest.php
- tests/Backend/Workspaces/TeradataWorkspacesUnloadTest.php
- tests/Backend/Workspaces/WorkspacesUnloadTest.php
- tests/Common/MetadataTest.php
Jira: CT-914
KBC: XXX
---
---
Nasiel som len pouzitie apiPost, v zadani je spomenute aj `apiDelete` ale ziadne `apiDeleteJson` nemame len `apiDeleteParams` a `apiDeleteParamsJson` co je uz vsade upravene. V dalsom ticekte by sme mali asi tieto metody zmazat a vydat major verziu co ?
> apiPost => apiPostJson

- tests/Backend/Snowflake/CloneIntoWorkspaceTest.php
- tests/Backend/Snowflake/TypedTableInWorkspaceTest.php
Reverts keboola/storage-api-php-client#1033
> Revert "CT-950 unload ws timestamp"

- tests/Backend/CommonPart1/DataPreviewLimitsTest.php
Jira: CT-984
KBC: https://github.com/keboola/connection/pull/4326
> CT-984 test missing values in data-preview

- apiary.apib
- tests/Backend/Exasol/TableDefinitionOperationsTest.php
- tests/Backend/Synapse/TableDefinitionOperationsTest.php
Jira: CT-985
KBC: https://github.com/keboola/connection/pull/4328
> test add column basetype on Exasol and Synapse

- apiary.apib
- tests/Backend/Bigquery/TableDefinitionOperationsTest.php
- tests/Backend/Exasol/TableDefinitionOperationsTest.php
- tests/Backend/Snowflake/TableDefinitionOperationsTest.php
- tests/Backend/Synapse/TableDefinitionOperationsTest.php
Jira: CT-971
KBC:https://github.com/keboola/connection/pull/4333
> CT-971 return definition

- tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Jira: CT-667
KBC: https://github.com/keboola/connection/pull/4336
> Init test type exceptions handling

- tests/Backend/Exasol/TableDefinitionOperationsTest.php
Jira: CT-1005
KBC: https://github.com/keboola/connection/pull/4381
> CT-1005 Add Exa test for invalid data filtering

- tests/Backend/Synapse/TableDefinitionOperationsTest.php
Jira: CT-1035
KBC: https://github.com/keboola/connection/pull/4391 
--- 
testovano par usecasu, ne vsechny, ale melo by to chcipnout v connection stejne at uz ten sysnpase vrati cokoliv
> Add Synapse test for invalid data filtering

- apiary.apib
- tests/Common/EventsAttachmentTest.php
Jira: CT-200
KBC: https://github.com/keboola/connection/pull/4389
> CT-200 test attachments content

- tests/Backend/Bigquery/TableDefinitionOperationsTest.php
Jira: CT-1006
KBC:https://github.com/keboola/connection/pull/4402
> test exotic datatypes BQ

- composer.json
- tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Jira: CT-1006
KBC: https://github.com/keboola/connection/pull/4404
> Test exotic types snflk

- tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Jira: CT-1009
KBC: https://github.com/keboola/connection/pull/4403
> CT-1009 add testCreateTableDefaults

- tests/Backend/Snowflake/TableDefinitionOperationsTest.php
- tests/Backend/Snowflake/TypedTableInWorkspaceTest.php
Jira: CT-1055 CT-1044
KBC: https://github.com/keboola/connection/pull/4415
> CT-1055 CT-1044 Update IE lib snflk exceptions

- apiary.apib
- tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
Jira: CT-1086
KBC: https://github.com/keboola/connection/pull/4416
Prakticky fixuje padaji tag kdy to nechtelo projit skrze smazane workspacy (reprezentujici schemata pro externi buckety)
> CT-1086 test dropping

- tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
Jira: CT-911
KBC: https://github.com/keboola/connection/pull/4410
> CT-911 test view registration

- apiary.apib
- tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Jira: CT-1003
KBC: https://github.com/keboola/connection/pull/4413
> CT-1003 snflk exotic types filtering

- apiary.apib
- src/Keboola/StorageApi/Client.php
- tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
Jira: CT-991
KBC: https://github.com/keboola/connection/pull/4406
> CT-991 generate queries for grants

- tests/Backend/Snowflake/TableDefinitionOperationsTest.php
> CT-1031 test data preview filters for snowflake

- tests/Backend/Synapse/ImportTypedTableTest.php
Jira: CT-XXX
KBC: XXX
viz. #team_connection_signed_off_deploys
> fix Synapse assert

- tests/Backend/Workspaces/ReadOnlyUserTest.php
- tests/Common/ComponentsTest.php
- tests/Common/ConfigurationMetadataTest.php
- tests/Common/TriggersTest.php
- tests/File/CommonFileTest.php
Jira: SOX-28
KBC: https://github.com/keboola/connection/pull/4424
> SOX-28 Fix error messages related to access to resources

- apiary.apib
Jira: -
KBC: -
je to GET a ma to byt v URL
> Make guide endpoint GET

- apiary.apib
- phpstan-baseline.neon
- tests/Backend/WorkspaceConnectionTrait.php
- tests/Backend/Workspaces/Backend/SnowflakeWorkspaceBackendDBAL.php
- tests/Backend/Workspaces/Backend/WorkspaceBackendFactory.php
- tests/Backend/Workspaces/WorkspacesLoadTestReadOnly.php
- tests/Backend/Workspaces/WorkspacesSnowflakeTest.php
Jira: SOX-18
KBC: https://github.com/keboola/connection/pull/4443
> SOX-18 SNFLK view load

- apiary.apib
- src/Keboola/StorageApi/Client.php
- tests/Common/MergeRequestsTest.php
Jira: SOX-13
KBC: https://github.com/keboola/connection/pull/4445 
> SOX-13 create MR

- apiary.apib
- tests/Common/BranchComponentTest.php
- tests/Common/ComponentsTest.php
Jira: SOX-8
KBC: https://github.com/keboola/connection/pull/4427
> Test version unique identifikator

- tests/Common/DevBranchesTest.php
Jira: SOX-40
KBC: https://github.com/keboola/connection/pull/4447
> SOX-40 Test branch behavior for non-admin token

- apiary.apib
- src/Keboola/StorageApi/Client.php
- tests/Common/MergeRequestsTest.php
Jira: SOX-13
KBC: https://github.com/keboola/connection/pull/4452
> SOX-13 MR detail

- tests/Common/BranchComponentTest.php
- tests/Common/ComponentsTest.php
Jira: CT-XXX
KBC: https://github.com/keboola/connection/pull/4463
> Revert slow and sometimes broken query to get version

- apiary.apib
- src/Keboola/StorageApi/Client.php
- tests/Backend/SOX/MergeRequestsTest.php
- tests/ClientTestCase.php
Jira: SOX-14
KBC: https://github.com/keboola/connection/pull/4437
init tests
> SOX-14 init tests for wf

- tests/Common/BranchComponentTest.php
Jira: CT-XXX
KBC: XXX
https://keboolaglobal.slack.com/archives/C055RTFCJ6M/p1687440724352129?thread_ts=1687440581.385719&cid=C055RTFCJ6M
> comment out vuid

- apiary.apib
- src/Keboola/StorageApi/Client.php
- tests/Backend/SOX/MergeRequestsTest.php
Jira: SOX-13
KBC: https://github.com/keboola/connection/pull/4475
> SOX-13 list MRs

- tests/Common/BranchComponentTest.php
- tests/Common/ComponentsTest.php
Jira: SOX-118
KBC:https://github.com/keboola/connection/pull/4473
> enable testing versionIdentifier

- apiary.apib
- src/Keboola/StorageApi/Client.php
- tests/Backend/SOX/MergeRequestsTest.php
Jira: SOX-124
KBC: https://github.com/keboola/connection/pull/4476
> SOX-124 update texts

- apiary.apib
- src/Keboola/StorageApi/Client.php
- tests/Backend/SOX/MergeRequestsTest.php
- tests/Common/BranchComponentTest.php
- tests/Common/ClientProviderTest.php
- tests/Common/ComponentsTest.php
- tests/Common/ConfigurationMetadataTest.php
- tests/Common/SearchComponentsConfigurationsTest.php
- tests/StorageApiTestCase.php
Jira: SOX-2
KBC: https://github.com/keboola/connection/pull/4472
> Sox 2 merge endpoint

- phpstan-baseline.neon
> fix baseline

- phpunit.xml.dist
- tests/Backend/SOX/SOXTokensTest.php
Jira: SOX-153
KBC: https://github.com/keboola/connection/pull/4484
> SOX-153 tokens hide

- phpstan-baseline.neon
- tests/Backend/SOX/MergeRequestsTest.php
Jira: SOX-11
KBC: https://github.com/keboola/connection/pull/4481
> Sox 2merge job part 3

- phpunit.xml.dist
- src/Keboola/StorageApi/DevBranches.php
- tests/Backend/SOX/MergeRequestsTest.php
- tests/StorageApiTestCase.php
> SOX fix mr tests

- apiary.apib
- phpunit.xml.dist
- src/Keboola/StorageApi/Client.php
- tests/Backend/SOX/MergeRequestsTest.php
Jira: SOX-117 SOX-123
KBC: https://github.com/keboola/connection/pull/4485
> SOX-117 SOX-123 reject->request-changes, branch locking

- tests/Backend/SOX/MergeRequestsTest.php
Jira: SOX-131
KBC:  https://github.com/keboola/connection/pull/4488
> test branch is deleted after merge

- tests/Backend/SOX/MergeRequestsTest.php
Reverts keboola/storage-api-php-client#1111
> Revert "test branch is deleted after merge"

- phpstan-baseline.neon
- tests/Backend/SOX/MergeRequestsTest.php
Jira: SOX-164
KBC: https://github.com/keboola/connection/pull/4486
> Start test metadata

- apiary.apib
- src/Keboola/StorageApi/Client.php
- tests/Backend/SOX/MergeRequestsTest.php
Jira: SOX-166
KBC: https://github.com/keboola/connection/pull/4489
> SOX-166 rename workflow endpoints

- apiary.apib
- tests/Backend/Workspaces/WorkspacesLoadTest.php
- tests/Backend/Workspaces/WorkspacesSnowflakeTest.php
Jira: SOX-165
KBC: https://github.com/keboola/connection/pull/4490 
> SOX-165 add branch id to ws load

- tests/Backend/SOX/MergeRequestsTest.php
> Jirka fix sox suite

- apiary.apib
- src/Keboola/StorageApi/Client.php
- tests/Backend/SOX/PullTableTest.php
Jira: SOX-21
KBC: https://github.com/keboola/connection/pull/4464
> SOX-21 table pull

- apiary.apib
> fix pull docs

- tests/Backend/SOX/BranchStorageTest.php
- tests/Backend/SOX/MergeRequestsTest.php
Jira: SOX-201
KBC: https://github.com/keboola/connection/pull/4495
> SOX-201 Branch table jobs

- tests/Backend/SOX/BranchStorageTest.php
- tests/Backend/SOX/MergeRequestsTest.php
- tests/Backend/SOX/PullTableTest.php
- tests/StorageApiTestCase.php
Jira: CT-XXX
KBC: XXX
Jedna drobnost pouzivam to na viacerych miestach
> Move getBranchesForCurrentTestCase to base test case

- tests/Backend/SOX/ExportTableTest.php
Jira: SOX-20
KBC: https://github.com/keboola/connection/pull/4491
> test branch file export

- apiary.apib
- src/Keboola/StorageApi/BranchAwareClient.php
- src/Keboola/StorageApi/Client.php
- src/Keboola/StorageApi/TableExporter.php
- tests/Backend/SOX/ExportTableTest.php
Jira: SOX-20
KBC: https://github.com/keboola/connection/pull/4491
> Sox 20 table export in branch backoff

- tests/Backend/SOX/MergeRequestsTest.php
- tests/Backend/SOX/PullTableTest.php
> fix sox suite

- tests/Backend/SOX/MergeRequestsTest.php
> fix two more branch delete usecases

- tests/Backend/SOX/BranchStorageTest.php
Jira: SOX-200
KBC: https://github.com/keboola/connection/pull/4498
> SOX-200 test listing in branch storage

- tests/Common/TokensTest.php
Jira: SOX-213
KBC: https://github.com/keboola/connection/pull/4499
> SOX-213 add canCreateJobs test

- tests/Backend/SOX/BranchStorageTest.php
- tests/Backend/SOX/ExportTableTest.php
- tests/Backend/SOX/SOXCommonTest.php
> Sox 208 improve tests

- tests/Backend/SOX/MergeRequestsTest.php
Jira: SOX-17
KBC: https://github.com/keboola/connection/pull/4496
---
nasypal jsem to jen do 1 testu, ktery dela vsechny operace. takze snad cajk
> SOX-17 add events to MR test

- tests/Backend/SOX/MergeRequestsTest.php
Jira: SOX-17
KBC: https://github.com/keboola/connection/pull/4504
> SOX-17 part2: add create mr event test

- tests/Backend/SOX/MergeRequestsTest.php
- tests/Common/DevBranchesTest.php
Jira: CT-XXX
KBC: https://github.com/keboola/connection/pull/4506
> fix expected error messages

- tests/Backend/SOX/MergeRequestsTest.php
Jira: CT-XXX
KBC: https://github.com/keboola/connection/pull/4509
> Test self-approval

- apiary.apib
- tests/Backend/SOX/MergeRequestsTest.php
Jira: SOX-121
KBC: https://github.com/keboola/connection/pull/4508
**There is BC break in experimental MR feature, that changes "content" from "json string" to "object"**
> SOX-121 Create list of changed things when MR put to review

- tests/Backend/SOX/BranchStorageTest.php
Jira: SOX-194
KBC: https://github.com/keboola/connection/pull/4505
> SOX-194 BranchStorageTest test events fired

- phpstan-baseline.neon
- phpunit.xml.dist
- src/Keboola/StorageApi/Client.php
- tests/Backend/CommonPart1/BucketsTest.php
- tests/ClientProvider/ClientProvider.php
- tests/ClientProvider/TestSetupHelper.php
- tests/Common/BranchEventsTest.php
- tests/Common/MetadataTest.php
- tests/Common/SearchTablesTest.php
- tests/Common/TablesListingTest.php
- tests/StorageApiTestCase.php
> SOX-66 buckets branched storage

- tests/Backend/SOX/TriggersTest.php
Jira: SOX-294
KBC: https://github.com/keboola/connection/pull/4515
> SOX-294 test CRUD triggers in SOX

- tests/Backend/CommonPart1/BranchStorageTest.php
Jira: SOX-163
KBC: https://github.com/keboola/connection/pull/4510
> SOX-163 test testCanCreateBucket in dev branch

- tests/Backend/SOX/MergeRequestsTest.php
Jira: SOX-288
KBC: https://github.com/keboola/connection/pull/4518
> SOX-288 mr cancel

- apiary.apib
- src/Keboola/StorageApi/Client.php
- tests/Backend/SOX/MergeRequestsTest.php
Jira: SOX-289
KBC: https://github.com/keboola/connection/pull/4523
> SOX-289 drop cancelMergeRequest

- tests/Backend/SOX/TriggersTest.php
> SOX-84 test testCreateTriggerInBranch

- tests/Common/TableEventsTest.php
Jira: SOX-321
KBC: https://github.com/keboola/connection/pull/4534/files
> SOX-321 add TableEventsTest

- tests/Backend/SOX/BranchFileStorageTest.php
Jira: SOX-126
KBC: https://github.com/keboola/connection/pull/4533
> test delete files in branch after branch deleted

- tests/Backend/SOX/MergeRequestsTest.php
Jira: SOX-290
KBC: https://github.com/keboola/connection/pull/4529
> SOX-290 assert new merge conflict errors

- phpunit.xml.dist
- tests/Backend/SOX/BranchFileStorageTest.php
- tests/Backend/SOX/BranchStorageTest.php
- tests/Backend/SOX/ExportTableTest.php
- tests/Backend/SOX/MergeRequestsTest.php
- tests/Backend/SOX/PullTableTest.php
- tests/Backend/SOX/SOXBranchesTest.php
- tests/Backend/SOX/TriggersTest.php
- tests/StorageApiTestCase.php
> SOX-86 e2e branches

- phpstan-baseline.neon
- phpunit.xml.dist
- tests/File/AwsFileTest.php
- tests/File/CommonFilePermissionsTest.php
- tests/File/CommonFileTest.php
- tests/StorageApiTestCase.php
Jira: SOX-24
KBC: https://github.com/keboola/connection/pull/4528
> Sox 24 test files branch aware

- phpstan-baseline.neon
- src/Keboola/StorageApi/Client.php
- tests/Backend/SOX/BranchStorageTest.php
Jira: SOX-271
KBC: https://github.com/keboola/connection/pull/4532
> SOX-271 (4) Test snapshot endpoint

- tests/Backend/Snowflake/TypedTableInWorkspaceTest.php
Jira: CT-1108
KBC: https://github.com/keboola/connection/pull/4543
> do not expect exception about type mismatch CT-1108

- src/Keboola/StorageApi/Workspaces.php
Jira: SOX-315
KBC: https://github.com/keboola/connection/pull/4542
> SOX-315 Reset password and return

- tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Jira: CT-1111
KBC: https://github.com/keboola/connection/pull/4544
> CT-1111 Test length of timestamp column

- tests/Backend/SOX/BranchStorageTest.php
> test cross crud buckets part 1

- src/Keboola/StorageApi/Components.php
- src/Keboola/StorageApi/Workspaces.php
> SOX-316 Add WS reset password to component WS also

- tests/Backend/SOX/SOXTokensTest.php
- tests/Common/TokensTest.php
Jira: SOX-352
KBC: https://github.com/keboola/connection/pull/4555
> SOX-352 refresh

- tests/Backend/SOX/SOXTokensTest.php
Jira: SOX-353
KBC: https://github.com/keboola/connection/pull/4562
> SOX-353 vytvareni tokenu

- tests/Backend/SOX/SOXTokensTest.php
Reverts keboola/storage-api-php-client#1163
> Revert "SOX-353 vytvareni tokenu"

- phpstan-baseline.neon
- phpunit.xml.dist
- tests/Backend/CommonPart1/BranchStorageTest.php
- tests/Backend/SOX/BranchFileStorageTest.php
- tests/Backend/SOX/ExportTableTest.php
- tests/Backend/SOX/SOXWorkspaceTest.php
- tests/Backend/SOX/SOXWorkspaceTestCase.php
- tests/Backend/Synapse/ImportTypedTableTest.php
- tests/Backend/Workspaces/Backend/BigqueryWorkspaceBackend.php
- tests/Backend/Workspaces/Backend/ExasolWorkspaceBackend.php
- tests/Backend/Workspaces/Backend/RedshiftWorkspaceBackend.php
- tests/Backend/Workspaces/Backend/SnowflakeWorkspaceBackend.php
- tests/Backend/Workspaces/Backend/SnowflakeWorkspaceBackendDBAL.php
- tests/Backend/Workspaces/Backend/SynapseWorkspaceBackend.php
- tests/Backend/Workspaces/Backend/TeradataWorkspaceBackend.php
- tests/Backend/Workspaces/Backend/WorkspaceBackend.php
- tests/Backend/Workspaces/Backend/WorkspaceBackendFactory.php
- tests/Backend/Workspaces/BigqueryWorkspacesUnloadTest.php
- tests/ClientProvider/TestSetupHelper.php
- tests/Common/MetadataTest.php
- tests/File/GcsFileTest.php
Jira: BIG-148
KBC: https://github.com/keboola/connection/pull/4564
> BIG-148 BQ SOX tests

- src/Keboola/StorageApi/GCSUploader.php
- src/Keboola/StorageApi/S3Uploader.php
- tests/Backend/CommonPart1/BranchStorageTest.php
> BQ is supported in branch storage

- tests/Backend/SOX/PullTableTest.php
> fix BQ pull table test

- tests/Backend/SOX/SOXWorkspaceTest.php
- tests/Backend/Workspaces/Backend/BigqueryWorkspaceBackend.php
Jira: BIG-157
KBC: https://github.com/keboola/connection/pull/4577
> BIG-157 update BQ test to test preserve flag when using view load

- tests/Backend/FileWorkspace/WorkspacesTest.php
- tests/Backend/Workspaces/BigqueryWorkspacesUnloadTest.php
- tests/Backend/Workspaces/ComponentsWorkspacesTest.php
- tests/Backend/Workspaces/WorkspacesTest.php
Jira: SOX-316
KBC:  https://github.com/keboola/connection/pull/4556
> SOX-316 test password is not present in response

- tests/Backend/FileWorkspace/ComponentsWorkspacesTest.php
- tests/Common/MetadataTest.php
Jira: CT-XXX
KBC: XXX
https://keboolaglobal.slack.com/archives/C0553EM2RGX/p1693294475427379
> Fix phpstan

- tests/Backend/SOX/SOXTokensTest.php
Jira: SOX-355
KBC: https://github.com/keboola/connection/pull/4587
> SOX-355 same and different canCreateJobs test

- tests/Backend/SOX/SOXTokensTest.php
Jira: SOX-354
KBC: https://github.com/keboola/connection/pull/4588
> SOX-354 Check canCreateJobs can't do stuff in branch

- tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Jira: CT-1093
KBC: https://github.com/keboola/connection/pull/4601
> CT-1093 Test adding column with expression

- tests/Backend/SOX/MergeRequestsTest.php
Jira: SOX-346
KBC: https://github.com/keboola/connection/pull/4608
> SOX-346 test scenario with deleted configuration

- tests/Backend/Snowflake/ImportTypedTableTest.php
- tests/StorageApiTestCase.php
Jira: CT-1118
KBC: https://github.com/keboola/connection/pull/4611
> CT-1118 failing test nullable column

- tests/Backend/SOX/ExportTableTest.php
Jira: SOX-211 
KBC: https://github.com/keboola/connection/pull/4610
> SOX-211 Test cannot export from dev to prod

- tests/Backend/Snowflake/ImportTypedTableTest.php
- tests/StorageApiTestCase.php
Reverts keboola/storage-api-php-client#1161
> Revert "CT-1118 failing test nullable column"

- tests/Backend/SOX/SOXTokensTest.php
Jira: SOX-31
KBC: https://github.com/keboola/connection/pull/4430
> SOX-31 test that manage token id is logged in the event

- Dockerfile
- apiary.apib
- composer.json
- docker-compose.yml
- phpstan.neon
- phpunit.xml.dist
- tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
- tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
- tests/bootstrap.php
Jira: BIG-126
KBC: https://github.com/keboola/connection/pull/4594
> Big 126 external buckets

- tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Jira: CT-1115
KBC: https://github.com/keboola/connection/pull/4623
> CT-1115 add testAddNullableColumn

- tests/Backend/Snowflake/TableDefinitionOperationsTest.php
> CT-1115 fix incorrect message assertion

- apiary.apib
- src/Keboola/StorageApi/Client.php
- tests/Backend/CommonPart1/DeleteRowsTest.php
> Ct 830 add parameter allow truncate if filter is empty

- apiary.apib
- src/Keboola/StorageApi/Client.php
- tests/Backend/CommonPart1/DeleteRowsTest.php
Reverts keboola/storage-api-php-client#1188
> Revert "Ct 830 add parameter allow truncate if filter is empty"

- tests/Backend/SOX/SOXWorkspaceTest.php
Jira: BIG-165
KBC:https://github.com/keboola/connection/pull/4637
> BIG-165 fix loading multiple tables when BQ IM using view

- apiary.apib
- src/Keboola/StorageApi/Client.php
- tests/Backend/CommonPart1/DeleteRowsTest.php
Reverts keboola/storage-api-php-client#1192
> Revert "Revert "Ct 830 add parameter allow truncate if filter is empty""

- tests/Backend/CommonPart2/SlicedImportsTest.php
- tests/Backend/CommonPart2/SlicedImportsWithSlicedUploadsTest.php
- tests/Backend/Redshift/CommonTest.php
- tests/Backend/Snowflake/TimestampTest.php
> add ['allowTruncate' => true] to tests

- tests/Backend/MixedSnowflakeBigquery/SharingTest.php
Jira: CT-1134
KBC: https://github.com/keboola/connection/pull/4635
> testCreateTableInBucketWithDifferentBackendAsProjectDefault

- tests/Backend/MixedSnowflakeBigquery/SharingTest.php
Reverts keboola/storage-api-php-client#1189
> Revert "testCreateTableInBucketWithDifferentBackendAsProjectDefault"

- apiary.apib
- tests/Backend/Bigquery/TableDefinitionOperationsPartitioningTest.php
- tests/Backend/Bigquery/TableDefinitionOperationsTest.php
- tests/Backend/CommonPart1/TimeTravelTest.php
- tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
- tests/Backend/SOX/PullTableTest.php
Jira: BIG-173
KBC: https://github.com/keboola/connection/pull/4652
> BIG-173 add test for BQ partitioning

- tests/File/AwsFileTest.php
- tests/File/AzureFileTest.php
- tests/File/GcsFileTest.php
Jira: GCP-360
KBC: https://github.com/keboola/connection/pull/4658
AWS a Azure prechadzaju, GCS padne na mastru a na branchi nespadne
> Roman gcs gcp 360

- tests/Backend/SOX/SOXTokensTest.php
Jira: SOX-422
KBC: https://github.com/keboola/connection/pull/4659
> SOX-422 test that can create jobs can read configurations

- phpunit.xml.dist
- tests/Backend/ExternalBuckets/BaseExternalBuckets.php
- tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
- tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
- tests/Backend/ExternalBuckets/TeradataRegisterBucketTest.php
- tests/Backend/Workspaces/Backend/BigqueryWorkspaceBackend.php
> SOX-397 SOX external buckets tests

- tests/Backend/SOX/SOXTokensTest.php
Jira: SOX-422
KBC: https://github.com/keboola/connection/pull/4683
> SOX-422 tokens with canCreateJobs can list components

- apiary.apib
> Fix typos (Bigquery->BigQuery)

- apiary.apib
- tests/Backend/Bigquery/TableDefinitionOperationsTest.php
- tests/Backend/Snowflake/TableDefinitionOperationsTest.php
- tests/Backend/Synapse/CreateTableTest.php
Jira: CT-1174
KBC: https://github.com/keboola/connection/pull/4684
> CT-1174 Fix tests around PK

- tests/ClientTestCase.php
> set logger in tests only when not set

- tests/Backend/MixedSnowflakeBigquery/SharingTest.php
Jira: BIG-213
KBC: https://github.com/keboola/connection/pull/4697
---
Dodělal sem test pro mixed.
+ sem si pustil v SOXu test abych ověřil že to funguje aj pro nelinkované buckety
SOXWorkspaceTest::testTableLoadAsView
> BIG-213 test view load for linked bucket in BQ

- apiary.apib
- tests/Backend/Bigquery/WorkspacesLoadTest.php
- tests/Backend/Workspaces/Backend/BigqueryWorkspaceBackend.php
- tests/Backend/Workspaces/WorkspacesSnowflakeTest.php
Jira: CT-1176 BIG-176
KBC: https://github.com/keboola/connection/pull/4701
> CT-1176 BIG-176 add SNFLK test for useView and alias

- tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
Jira: BIG-197
KBC: https://github.com/keboola/connection/pull/4708
> Test if try register ex bucket with non exist listing throw user err

- tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
Jira: BIG-195
KBC: https://github.com/keboola/connection/pull/4702
> BIG-195 add testRequirePartitionFilter for external buckets in BQ

- src/Keboola/StorageApi/GCSUploader.php
Jira: BIG-450
KBC: https://github.com/keboola/connection/pull/4703
> set timeout gcs uploader

- tests/Backend/Bigquery/TableDefinitionOperationsTest.php
Jira: BIG-193
KBC:  https://github.com/keboola/connection/pull/4710
> BIG-193 test loading nulls

- phpunit.xml.dist
> fix deleted  test file TablesDefinitionCommonTest.php

- tests/Backend/CommonPart1/AlterTableTest.php
> CT-1185 drop testTooManyColumnsOrRowSizeFailed

- apiary.apib
- tests/Backend/Bigquery/WorkspacesLoadTest.php
- tests/Backend/MixedSnowflakeBigquery/SharingTest.php
- tests/Backend/Workspaces/Backend/BigqueryWorkspaceBackend.php
- tests/Backend/Workspaces/WorkspacesSnowflakeTest.php
Reverts keboola/storage-api-php-client#1217
connection: https://github.com/keboola/connection/pull/4712
> Revert "Revert "CT-1176 BIG-176 add SNFLK test for useView and alias""

- phpunit.xml.dist
- tests/Backend/SOX/ShareTest.php
> Roman force unlink tests

- composer.json
> allow "psr/log": "^1.1|^2.0|^3.0",

- phpunit.xml.dist
- tests/Backend/SOX/ShareTest.php
Jira: SOX-456
KBC: https://github.com/keboola/connection/pull/4716
> SOX-456 Allow PM to link bucket in SOX

- tests/Backend/SOX/ShareTest.php
Jira: SOX-456
KBC: https://github.com/keboola/connection/pull/4726
> test is allowed call share in sox branch

- tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
Jira: BIG-216
KBC: https://github.com/keboola/connection/pull/4732
> BIG-216 test External table in external bucket in BQ

- tests/Backend/Bigquery/TableDefinitionOperationsTest.php
Jira: BIG-207
KBC: https://github.com/keboola/connection/pull/4722
https://github.com/keboola/storage-backend/pull/120
> [BIG-207] BQ import user exception wrong timestamp format

- composer.json
- phpstan.neon
- tests/Backend/CommonPart1/AlterTableTest.php
- tests/Backend/CommonPart1/BranchStorageTest.php
- tests/Backend/CommonPart1/ImportExportCommonTest.php
- tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
- tests/Backend/ExternalBuckets/TeradataRegisterBucketTest.php
- tests/Backend/FileWorkspace/WorkspacesLoadTest.php
- tests/Backend/FileWorkspace/WorkspacesTest.php
- tests/Backend/Mixed/LegacyWorkspacesTest.php
- tests/Backend/Mixed/Workspaces/BaseWorkSpacesTestCase.php
- tests/Backend/MixedSnowflakeSynapse/SharingTest.php
- tests/Backend/Redshift/ImportExportCommonTest.php
- tests/Backend/SOX/BranchStorageTest.php
- tests/Backend/SOX/MergeRequestsTest.php
- tests/Backend/SOX/SOXTokensTest.php
- tests/Backend/SOX/SOXWorkspaceTest.php
- tests/Backend/SOX/TriggersTest.php
- tests/Backend/Synapse/CreateTableTest.php
- tests/Backend/Workspaces/SnowflakeDynamicBackendsTest.php
- tests/Backend/Workspaces/WorkspacesLoadTestReadOnly.php
- tests/Common/ComponentsTest.php
- tests/Common/SearchTablesTest.php
- tests/File/CommonFileTest.php
> CT-1190 Add tomasfejfar/phpstan-phpunit

- tests/Backend/Bigquery/TableDefinitionOperationsTest.php
Jira: BIG-199
Tests: https://github.com/keboola/storage-api-php-client/pull/1242
Driver: https://github.com/keboola/php-storage-driver-bigquery/pull/103
KBC: https://github.com/keboola/connection/pull/4775
> BIG-199 test unsupported formats in filter

- tests/Backend/Workspaces/ParallelWorkspacesTestCase.php
> Drop token if it cannot be reused

- tests/Backend/Bigquery/TableDefinitionOperationsTest.php
Jira: BIG-208
KBC:  https://github.com/keboola/connection/pull/4770
> test few default values for datatypes, more is tested in driver

- tests/Backend/Bigquery/TableDefinitionOperationsTest.php
> [BIG-200] [HOLD][BQ] Valide illogical comparsion end in a correct error

- tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
Jira: https://keboola.atlassian.net/browse/CT-1202 (branch is has wrong name)
KBC: https://github.com/keboola/connection/pull/4783
> CT-1202 Test guide

- tests/Backend/Mixed/LegacyWorkspacesTest.php
> Fix failing test - cross backend export fixes the null issue

- tests/Backend/Workspaces/WorkspacesLoadTest.php
https://keboolaglobal.slack.com/archives/C055RTFCJ6M/p1705431867964849?thread_ts=1705431372.985339&cid=C055RTFCJ6M
Jira: CT-XXX
KBC: XXX
> fix snflk expectation new prop from SNFLK

- tests/Backend/Bigquery/TableDefinitionOperationsTest.php
Jira: BIG-227
KBC: https://github.com/keboola/connection/pull/4790
> test column mismatch is user err

- src/Keboola/StorageApi/TableExporter.php
> CT-1239 the whole path should be escaped including the suffix

- tests/Backend/CommonPart1/BranchStorageTest.php
Jira: CT-703
KBC: https://github.com/keboola/connection/pull/4795
> CT-703 Paralel jobs storage - no change, just Doctrine to create job

- tests/Backend/CommonPart1/BranchStorageTest.php
https://keboolaglobal.slack.com/archives/C055RTFCJ6M/p1706039629818739?thread_ts=1706038413.368089&cid=C055RTFCJ6M
> fix test expectations

- tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
> fix exchange deletion

- apiary.apib
- src/Keboola/StorageApi/Client.php
- tests/Backend/SOX/BranchFileStorageTest.php
- tests/File/GcsFileTest.php
Jira: BIG-226
KBC: https://github.com/keboola/connection/pull/4815
Text som este upravil, obrazky su len ilustracne ze to funguje :)
> Add refresh for file

- apiary.apib
- tests/Backend/Workspaces/WorkspacesTest.php
Jira:  [GMT-136](https://keboola.atlassian.net/browse/GMT-136)
KBC:  https://github.com/keboola/connection/pull/4820
[GMT-136]: https://keboola.atlassian.net/browse/GMT-136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GMT-136 region in ws

- tests/Backend/MixedSnowflakeBigquery/SharingTest.php
Jira: CT-1249
KBC: https://github.com/keboola/connection/pull/4825
> CT-1249 add BQ mixed test testLinkBucketExport

- src/Keboola/StorageApi/ABSUploader.php
- src/Keboola/StorageApi/GCSUploader.php
- src/Keboola/StorageApi/S3Uploader.php
> add @internal to uploader clases

- apiary.apib
- phpstan-baseline.neon
- src/Keboola/StorageApi/Client.php
- src/Keboola/StorageApi/Options/BucketDetailOptions.php
- tests/Backend/CommonPart1/BucketsTest.php
Jira: CT-1229
KBC: https://github.com/keboola/connection/pull/4844
> CT-1229 buckets include params

- apiary.apib
> CT-1228 Events list make more clear how it works

- tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
Jira: CT-1168
KBC:  https://github.com/keboola/connection/pull/4847
> CT-1168 test managing triggers on tables in external buckets

- tests/Backend/Workspaces/BigqueryWorkspacesUnloadTest.php
- tests/Backend/Workspaces/WorkspacesUnloadTest.php
Jira:  CT-1264
KBC:  https://github.com/keboola/connection/pull/4845/files
> CT-1264 Add tests for BQ

- tests/Backend/Synapse/ImportTypedTableTest.php
- tests/Backend/Workspaces/WorkspacesUnloadTest.php
Jira: CT-1264
KBC: XXX
based on https://dev.azure.com/keboola-dev/Connection%20build/_build/results?buildId=42879&view=logs&j=42c25245-7aac-5311-9828-3a2e77242474&t=e857334a-047b-5017-5fcb-d6de9c1b09c7
> Fix tests after CT-1264

- tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
- tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
- tests/Backend/FileWorkspace/WorkspacesTest.php
Jira: BIG-222
KBC: XXX
---
este k BIG-222 nebol som si isty ci ide zmazat ex bucket ktoremu odmazem prava na backend tak som rovno pridal do testov
> BIG-222 test if allowing delete ex bucket with deleted schema on backend

- src/Keboola/StorageApi/GCSUploader.php
Jira: N/A
KBC: N/A
https://keboolaglobal.slack.com/archives/C0553EM2RGX/p1708940316262319?thread_ts=1708936728.231809&cid=C0553EM2RGX
> Hotifx: Remove double sprintf

- tests/Backend/FileWorkspace/WorkspacesTest.php
- tests/Backend/Workspaces/WorkspacesTest.php
Jira: CT-1282
KBC: https://github.com/keboola/connection/pull/4863
> CT-1282 Check that workspaces does not have create streamlit privilege

- apiary.apib
- tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Jira: CT-1218
KBC: https://github.com/keboola/connection/pull/4868
Nevim, jestli je správně tomu dát major, ale je to BC break v apiary :D
> CT-1218 test orderBy with typed table

- tests/Backend/Bigquery/TableDefinitionOperationsTest.php
Jira: BIG-238
KBC: https://github.com/keboola/connection/pull/4871
> [BIG-238] Handle interval datatype in REST API BQ

- tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
- tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
Jira: CT-1100
KBC: https://github.com/keboola/connection/pull/4876
> CT-1100 external bucket table duplicate tables

- tests/Backend/ExternalBuckets/BaseExternalBuckets.php
- tests/Backend/SOX/PullTableTest.php
- tests/Utils/MetadataUtils.php
Jira: CT-1237
KBC: https://github.com/keboola/connection/pull/4872
> Ct 1237 table pull should create metadata

- tests/Backend/SOX/BranchStorageTest.php
> Fix test after adding metadata table pull to branch

- tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Jira: CT-1301
KBC: https://github.com/keboola/connection/pull/4886
> CT-1301 testCreateTableBasetypes for snowflake

- apiary.apib
- tests/Backend/Bigquery/TableDefinitionOperationsTest.php
Jira: [CT-1270](https://keboola.atlassian.net/browse/CT-1270)
Connection PR: https://github.com/keboola/connection/pull/4883/files
SAPI PR:  https://github.com/keboola/storage-api-php-client/pull/1283
storage backend command: https://github.com/keboola/storage-backend/pull/132
storage backend table utils: https://github.com/keboola/storage-backend/pull/129
BQ driver: https://github.com/keboola/php-storage-driver-bigquery/pull/117
[CT-1270]: https://keboola.atlassian.net/browse/CT-1270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix tests for PUT endpoint

- tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
- tests/Backend/SOX/SOXWorkspaceTestCase.php
- tests/Backend/Workspaces/WorkspacesLoadTestReadOnly.php
- tests/Backend/Workspaces/WorkspacesSnowflakeTest.php
Jira: CT-974
KBC: https://github.com/keboola/connection/pull/4900 - len pre potreby testov nebudem mergovat
---
Tag presiel tu https://dev.azure.com/keboola-dev/Connection%20build/_build/results?buildId=43668&view=results
> remove check on `input-mapping-read-only-storage` feature in tests

- tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
- snowflake
Jira: CT-1315
KBC:  https://github.com/keboola/connection/pull/4903
> alteredColumnThrowsUserExAndAfterRefreshWillWork

- apiary.apib
- composer.json
- src/Keboola/StorageApi/Client.php
- tests/Backend/CommonPart1/DeleteTableTest.php
- tests/Backend/CommonPart2/SimpleAliasTest.php
Jira: CT-1305 
KBC:  https://github.com/keboola/connection/pull/4899
> CT-1305 async drop table

- tests/Backend/CommonPart1/DeleteRowsTest.php
- tests/Backend/CommonPart2/SimpleAliasTest.php
Jira: CT-1259
KBC: https://github.com/keboola/connection/pull/4906
> CT-1259 delete table rows request validation

- tests/Backend/Synapse/CreateTableTest.php
Jira: CT-XXX
KBC: XXX
tim ze som mergoval https://keboola.atlassian.net/browse/CT-1332 tak uz pk niesu povinne a ten test to testoval
> remove tes table should not be created

- apiary.apib
- tests/Common/TokensTest.php
Jira: CT-1316
KBC: [XXX](https://github.com/keboola/connection/pull/4910)
> CT-1316 add backends field to project response

- tests/Backend/Workspaces/WorkspacesTest.php
> CT-996 Make sure that all backends set correct readOnlyStorageAccess value

- apiary.apib
- src/Keboola/StorageApi/Client.php
- tests/Backend/CommonPart1/ImportExportCommonTest.php
Reverts keboola/storage-api-php-client#1296
> Revert "CT-1118 Add and test import with importAsNull"

- tests/Backend/Mixed/SharingTest.php
Jira: CT-1309
KBC: https://github.com/keboola/connection/pull/4924
> CT-1309 sync linked bucket metatada

- tests/Common/TableDropTest.php
Jira: CT-1343
KBC: https://github.com/keboola/connection/pull/4926
> CT-1343 add TableDropTest

- .github/workflows/branch.yml
- .github/workflows/master.yml
- .github/workflows/tag.yml
- README.md
> CT-1356 docker compose

- apiary.apib
- phpstan-baseline.neon
- src/Keboola/StorageApi/Client.php
- tests/File/AwsFileTest.php
- tests/File/AzureFileTest.php
- tests/File/CommonFileTest.php
- tests/File/GcsFileTest.php
Jira: CT-745
KBC: https://github.com/keboola/connection/pull/4932
> CT-745 file delete async

- apiary.apib
- phpstan-baseline.neon
- src/Keboola/StorageApi/Client.php
- tests/File/AwsFileTest.php
- tests/File/AzureFileTest.php
- tests/File/CommonFileTest.php
- tests/File/GcsFileTest.php
Jira: CT-746
KBC: https://github.com/keboola/connection/pull/4925
> CT-746 file prepare async

- apiary.apib
- phpstan-baseline.neon
- src/Keboola/StorageApi/Client.php
- tests/File/AwsFileTest.php
- tests/File/AzureFileTest.php
- tests/File/CommonFileTest.php
- tests/File/GcsFileTest.php
Jira: CT-1363
KBC: https://github.com/keboola/connection/pull/4944
> CT-1363 remove file prepare async

- tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
Jira: BIG-244
KBC:  https://github.com/keboola/connection/pull/4933
BQ driver: https://github.com/keboola/php-storage-driver-bigquery/pull/129
> now is able to register external bucket

- apiary.apib
- src/Keboola/StorageApi/Client.php
- tests/Backend/CommonPart1/ImportExportCommonTest.php
Jira: CT-1118
KBC: https://github.com/keboola/connection/pull/4952
> CT-1118 testImportTreatValuesAsNull

- tests/Backend/Workspaces/WorkspacesSynapseTest.php
> Skip synapse workspace load

- tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
Jira:  BIG-246
KBC:  https://github.com/keboola/connection/pull/4971
SAPI: https://github.com/keboola/storage-api-php-client/pull/1318
table utils: https://github.com/keboola/storage-backend/pull/143
> BIG-246 test tableType for bigquery-external-table

- tests/Common/DevBranchesTest.php
> CT-1265 fix assert allow order change

- apiary.apib
Jira: CT-XXX
KBC: XXX
---
kdesi jsem se o tom bavil s Tomisem, ze to nemame nikde v api docs
> Note that PK columns cannot be nullable

- tests/Backend/Bigquery/ImportTreatValuesAsNullTest.php
- tests/Backend/CommonPart1/ImportExportCommonTest.php
- tests/Backend/Snowflake/ImportTreatValuesAsNullTest.php
- tests/_data/languages-empty-string.csv
Jira: [CT-1361](https://keboola.atlassian.net/browse/CT-1361)
KBC: [5005](https://github.com/keboola/connection/pull/5005)
[CT-1361]: https://keboola.atlassian.net/browse/CT-1361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CT-1361 default value for null conversion in bq

- src/Keboola/StorageApi/Client.php
- src/Keboola/StorageApi/Options/GlobalSearchOptions.php
Jira: [CT-1374](https://keboola.atlassian.net/browse/CT-1374)
KBC: https://github.com/keboola/connection/pull/5007
[CT-1374]: https://keboola.atlassian.net/browse/CT-1374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CT-1374-create-global-search-client-method

- apiary.apib
- phpstan-baseline.neon
- src/Keboola/StorageApi/Client.php
- tests/Common/IndexTest.php
Jira: [CT-1407](https://keboola.atlassian.net/browse/CT-1407)
KBC: [5021](https://github.com/keboola/connection/pull/5021)
[CT-1407]: https://keboola.atlassian.net/browse/CT-1407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CT-1407 endpoint webalize column name

- tests/Backend/Snowflake/TypedTableInWorkspaceTest.php
Jira: CT-1409
KBC: https://github.com/keboola/connection/pull/5029
> add testCopyLoadOfTypedTable

- tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
Jira: CT-1425
KBC: https://github.com/keboola/connection/pull/5034
---
⚠️ kdyz to pustis bez upravene connection, tak se ti odjebe celej projekt. bacha na to
blby akorat je, ze neumim udelat test, ktery by ten revoke zavolal, protoze mame EB v testech resene pres workspace. na to bychom potrebovali doresit https://keboola.atlassian.net/browse/CT-1240 .
> CT-1425 test drpoing external buckets

- apiary.apib
- composer.json
- src/Keboola/StorageApi/Client.php
- tests/Backend/CommonPart1/BranchStorageTest.php
- tests/Backend/CommonPart1/ImportExportCommonTest.php
- tests/Backend/Mixed/LegacyWorkspacesTest.php
- tests/Backend/MixedSnowflakeSynapse/SharingTest.php
- tests/Backend/SOX/BranchStorageTest.php
- tests/Backend/SOX/SOXTokensTest.php
- tests/Backend/SOX/SOXWorkspaceTest.php
- tests/_data/languages-with-headers-reordered.csv
Jira: [CT-1340](https://keboola.atlassian.net/browse/CT-1340)
KBC: [5000](https://github.com/keboola/connection/pull/5000)
[CT-1340]: https://keboola.atlassian.net/browse/CT-1340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> New import option ignoredLinesCount

- apiary.apib
- tests/Common/IndexTest.php
Jira: PST-1343
KBC: https://github.com/keboola/connection/pull/5003
> PST-1343 processorConfiguration,dataTypesConfiguration

- apiary.apib
- tests/Common/IndexTest.php
Reverts keboola/storage-api-php-client#1326
> Revert "PST-1343 processorConfiguration,dataTypesConfiguration"

- tests/Backend/SOX/MergeRequestsTest.php
Jira: CT-XXX
KBC:  https://github.com/keboola/connection/pull/5049
> test row deleted in devBranch shoudl be deleted in default after merge

- apiary.apib
- phpstan-baseline.neon
- src/Keboola/StorageApi/Client.php
- tests/Common/IndexTest.php
Jira: [CT-1429](https://keboola.atlassian.net/browse/CT-1429)
KBC: [5041](https://github.com/keboola/connection/pull/5041)
[CT-1429]: https://keboola.atlassian.net/browse/CT-1429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CT-1429 Request to webalize columns accepts an array as input

- tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
Jira: CT-1425
KBC:  https://github.com/keboola/connection/pull/5057
> CT-1425 test revoke

- tests/Backend/CommonPart1/DeleteRowsTest.php
> allow testcase

- tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
Jira:  CT-1447
KBC:  https://github.com/keboola/connection/pull/5069
> CT-1447 test new grants

- tests/Backend/Bigquery/TableDefinitionOperationsTest.php
Jira: BIG-250
KBC: https://github.com/keboola/connection/pull/5090
> BIG-250 update BQ testPrimaryKeyOperationsOnTypedTable

- tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
Jira: CT-1449
KBC: https://github.com/keboola/connection/pull/5079
> CT-1449 add test to check if external bucket can be dropped without existing WS

- docker-compose.yml
- phpunit.xml.dist
- tests/Backend/ExternalBuckets/SnowflakeBYODBTest.php
Jira: CT-1446
KBC:  https://github.com/keboola/connection/pull/5077
> CT-1446 test eb on byodb

- apiary.apib
- phpunit.xml.dist
- src/Keboola/StorageApi/Client.php
- tests/Backend/ExternalBuckets/SnowflakeBucketsRefreshTablesInformationTest.php
Jira: [CT-1440](https://keboola.atlassian.net/browse/CT-1440)
KBC: https://github.com/keboola/connection/pull/5098
[CT-1440]: https://keboola.atlassian.net/browse/CT-1440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CT-1440 add endpoint to client and apiary

- src/Keboola/StorageApi/Client.php
- tests/Backend/ExternalBuckets/SnowflakeBYODBTest.php
- tests/Backend/ExternalBuckets/SnowflakeBucketsRefreshTablesInformationTest.php
- tests/StorageApiTestCase.php
- tests/Utils/ConnectionUtils.php
Jira: [CT-1439](https://keboola.atlassian.net/browse/CT-1439)
KBC: https://github.com/keboola/connection/pull/5104
[CT-1439]: https://keboola.atlassian.net/browse/CT-1439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CT-1439 refresh tables information test

- src/Keboola/StorageApi/Client.php
- tests/Backend/ExternalBuckets/SnowflakeBucketsRefreshTablesInformationTest.php
> FIX client method for refresh-tables-information in bucket

- apiary.apib
- phpstan-baseline.neon
- phpstan.neon
- src/Keboola/StorageApi/Client.php
> FIX refresh-tables-information in bucket documentation

- phpstan-baseline.neon
- src/Keboola/StorageApi/Client.php
- tests/Backend/CommonPart1/BranchStorageTest.php
- tests/Backend/CommonPart2/MetricsTest.php
- tests/Backend/ExternalBuckets/SnowflakeBucketsRefreshTablesInformationTest.php
- tests/Common/QueueJobsTest.php
- tests/Utils/EventTesterUtils.php
Jira: CT-XXX
KBC: https://github.com/keboola/connection/pull/5114
> FIX refresh tables in bucket test

- src/Keboola/StorageApi/Options/GlobalSearchOptions.php
Jira: CT-1486
KBC: https://github.com/keboola/connection/pull/5115
> CT-1486 chnage type to types and arr

- apiary.apib
- phpunit.xml.dist
- tests/Backend/Snowflake/TypedTableWorkspacesLoadTest.php
Jira: CT-1434
KBC: XXX
--
- Ověřil sem že fungujů 
- where filtery
- seconds filtery
- přejmenování sloupců
- Ověřil sem že když filtr vyhodí chybu skončí to jako user exception 
- V connection sa ignoruje user definice typů v IM a bere sa definice z tabulky
- V connection sa ignore convertEmptyValuesToNull
> CT-1434 add TypedTableWorkspacesLoadTest

- apiary.apib
Jira: CT-XXX
KBC:  https://keboolaglobal.slack.com/archives/C055J16AXEE/p1718801274860409
> remove `/`

- tests/Common/TokensTest.php
> FIX token owner assertions

- tests/Common/TokensTest.php
Jira: CT-XXX
KBC: XXX
na zaklade https://keboolaglobal.slack.com/archives/C055RTFCJ6M/p1719223442824849
> Drop bucket at the begining of the test

- src/Keboola/StorageApi/Options/GlobalSearchOptions.php
Jira: CT-1368 
KBC:  https://github.com/keboola/connection/pull/5122#discussion_r1642965394
> CT-1368 - add branch paramets

- tests/Backend/Mixed/SharingTest.php
- tests/Common/BranchComponentTest.php
- tests/Common/ComponentsTest.php
Jira: CT-XXX
KBC: XXX
---
Rovno som fixol nejake veci nad tvojim PR, ostane veci mi pridu cajk, tak to prosim prejde a priapdne mergni dam ti pak finalne palecek
> try improve testGlobalSearchOnSharedBuckets

- tests/Backend/Mixed/SharingTest.php
- tests/Backend/Mixed/StorageApiSharingTestCase.php
- tests/Common/BranchComponentTest.php
- tests/Common/ComponentsTest.php
> ct 1445 gs tests roman improve

- tests/Backend/Bigquery/ImportTreatValuesAsNullTest.php
- tests/Backend/Bigquery/WorkspacesLoadTest.php
- tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
- tests/Backend/Workspaces/BigqueryWorkspacesUnloadTest.php
- tests/Backend/Workspaces/WorkspacesTest.php
Jira: BIG-259
KBC: XXX
--- 
pridal som cleanup ws v niektorych bq testoch, casom sa to nastrada a zacnu padat testy. 
Ked som to naposledy tagol tak sa uz pocet WS v GCP projekte nezvysil
https://dev.azure.com/keboola-dev/Connection%20build/_build/results?buildId=47939&view=results
> Add ws cleanup for bq tests

- tests/Backend/Snowflake/ImportTypedTableTest.php
> fix expected result of incremental import of typed table

- tests/Common/TokensTest.php
> FIX tokens tests respect token visibility

- tests/Common/TokensTest.php
> FIX token visibility check

- tests/Backend/Snowflake/ImportTypedTableTest.php
- tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Jira: CT-1642
KBC: https://github.com/keboola/connection/pull/5181
--
fix asserts for failing tests https://dev.azure.com/keboola-dev/Connection%20build/_build/results?buildId=48663&view=logs&j=2e32e92a-b774-5b2a-1ae4-fd294511f88b&t=8c529b05-b550-5bd7-b181-84b2b1023689
https://keboolaglobal.slack.com/archives/C055RTFCJ6M/p1721899797809949
> CT-1642 fix asserts for file load on typed table in SNFLK

- apiary.apib
- tests/Backend/Bigquery/TableDefinitionOperationsTest.php
- tests/Backend/Mixed/SharingTestWithTypedTables.php
- tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Jira: CT-1554
KBC: https://github.com/keboola/connection/pull/5188
> CT-1554 table definition propagation for alias and linked table

- src/Keboola/StorageApi/Workspaces.php
- tests/Backend/Workspaces/WorkspacesTest.php
> KAB-179 queueCreateWorkspace

- apiary.apib
- phpstan-baseline.neon
- src/Keboola/StorageApi/Client.php
- tests/Common/IndexTest.php
Jira: [CT-1670](https://keboola.atlassian.net/browse/CT-1670)
KBC: https://github.com/keboola/connection/pull/5184
Changes:
- tests for new endpoint validate/column-names
[CT-1670]: https://keboola.atlassian.net/browse/CT-1670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CT-1670 - test validate column names endpoint

- apiary.apib
- tests/Backend/Bigquery/TableDefinitionOperationsTest.php
Jira: CT-1673
KBC:  https://github.com/keboola/connection/pull/5191
> CT-1673 test BQ column cannot be set as required

- src/Keboola/StorageApi/Client.php
- src/Keboola/StorageApi/Workspaces.php
- tests/Backend/Workspaces/WorkspacesTest.php
> KAB-179 queue drop workspace

- composer.json
- tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Jira: [CT-1526](https://keboola.atlassian.net/browse/CT-1526)
KBC: https://github.com/keboola/connection/pull/5195
[CT-1526]: https://keboola.atlassian.net/browse/CT-1526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CT-1526 add snowflake vector datatype

- tests/Backend/CommonPart1/TimeTravelTest.php
Jira: CT-XXX
KBC:  https://github.com/keboola/connection/pull/5206
> enable testCreateTypedTableFromTimestamp for snowflake

- phpstan.neon
- phpunit.xml.dist
- src/Keboola/StorageApi/Client.php
- tests/Backend/ExternalBuckets/SnowflakeBYODBTest.php
- tests/Backend/ExternalBuckets/SnowflakeExternalBucketShareTest.php
Jira: [CT-1557](https://keboola.atlassian.net/browse/CT-1557)
KBC: https://github.com/keboola/connection/pull/5196
[CT-1557]: https://keboola.atlassian.net/browse/CT-1557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CT-1557 - Snowflake external schema share tests

- tests/Backend/ExternalBuckets/SnowflakeExternalBucketShareTest.php
- tests/Backend/Mixed/SharingTest.php
Jira: CT-1559
KBC:  https://github.com/keboola/connection/pull/5209
> Rb ct 1559 snflk ext refresh test

- tests/Backend/ExternalBuckets/SnowflakeExternalBucketShareTest.php
- tests/Backend/Mixed/SharingTest.php
- tests/Utils/EventTesterUtils.php
Jira: [CT-1559](https://keboola.atlassian.net/browse/CT-1559)
KBC: https://github.com/keboola/connection/pull/5205
[CT-1559]: https://keboola.atlassian.net/browse/CT-1559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CT-1559 snowflake refresh bucket tests

- phpstan-baseline.neon
- tests/Backend/ExternalBuckets/SnowflakeBucketsRefreshTablesInformationTest.php
> CT-1559 fix failing testRefreshTablesInformation

- apiary.apib
- src/Keboola/StorageApi/Downloader/AbsUrlParser.php
- tests/Downloader/AbsUrlParserTest.php
Jira: CT-1712
KBC: XXX
Na zaklade https://keboola.atlassian.net/browse/SUPPORT-7506 https://keboolaglobal.slack.com/archives/C0553EM2RGX/p1725279406452859
Zacal mi padat stan tak som tam este poladil jednu triedu
> operator is optional an support only two options

- tests/Backend/ExternalBuckets/SnowflakeBYODBTest.php
Jira: CT-1240
KBC: -
---
just add dropBucket step in the flow to check that bucket drop really works in BYODB env
> CT-1240 test bucket drop

- apiary.apib
- tests/Common/JobsListTest.php
Jira: [CT-1707](https://keboola.atlassian.net/browse/CT-1707)
KBC: https://github.com/keboola/connection/pull/5237
[CT-1707]: https://keboola.atlassian.net/browse/CT-1707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CT-1707 - /storage/jobs endpoint served from new StorageTable - tests

- apiary.apib
> FIX apiary doc

- tests/Backend/CommonPart2/SnapshottingTest.php
> remove debug

- tests/File/CommonFileTest.php
Jira: CT-1728
KBC:  https://github.com/keboola/connection/pull/5256
> test remove tag with `/` in name

- apiary.apib
- src/Keboola/StorageApi/Client.php
- tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
Jira: CT-1561
KBC: https://github.com/keboola/connection/pull/5274
> CT-1561 add option isSnowflakeSharedDatabase to register guide

- apiary.apib
- composer.json
- docker-compose.yml
- phpunit.xml.dist
- tests/Backend/NetworkPolicies/NetworkPoliciesTestCase.php
- tests/Backend/NetworkPolicies/SnowflakeNetworkPoliciesTest.php
- tests/Utils/ConnectionUtils.php
- tests/Utils/IpUtils.php
Jira: [CT-1721](https://keboola.atlassian.net/browse/CT-1721)
KBC: https://github.com/keboola/connection/pull/5247
[CT-1721]: https://keboola.atlassian.net/browse/CT-1721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CT-1721 add network policies tests

- tests/Backend/SOX/ShareTest.php
- tests/Utils/SharingUtils.php
> fix sox share test

- phpunit.xml.dist
- tests/Backend/CommonPart2/SnapshottingTest.php
- tests/Backend/ExternalBuckets/BaseExternalBuckets.php
- tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
- tests/Backend/ExternalBuckets/SnowflakeExternalBucketShareTest.php
- tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
- tests/Backend/SOX/SOXBranchesTest.php
Jira: CT-1752
KBC:  https://github.com/keboola/connection/pull/5257 https://github.com/keboola/connection/pull/5277
> CT-1752 test guide in sox

- apiary.apib
> CT-1791 add readOnlyStorageAccess to docs

- .github/PULL_REQUEST_TEMPLATE.md
- src/Keboola/StorageApi/BranchAwareClient.php
- tests-unit/Client/BranchAwareClientTest.php
Jira: CT-1771
KBC: https://github.com/keboola/connection/pull/5305
> CT-1771 BranchAwareClient supports calling not branched endpoints

- tests/Backend/SOX/TriggersTest.php
> remove testCreateTriggerInDefaultBranchWithTableInBranch

- apiary.apib
- docker-compose.yml
- phpunit.xml.dist
- src/Keboola/StorageApi/Client.php
- tests/Backend/ExternalBuckets/SnowflakeRegisterExternalBucketInSecureDataShareTest.php
Jira: [CT-1563](https://keboola.atlassian.net/browse/CT-1563)
KBC: https://github.com/keboola/connection/pull/5300
[CT-1563]: https://keboola.atlassian.net/browse/CT-1563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CT-1536 - Secure Data Share - first test

- tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Jira: CT-1685
KBC: https://github.com/keboola/connection/pull/5311
> CT-1685 test that fulltextSearch will not fail on exotic datatypes

- apiary.apib
- tests/Backend/Bigquery/TableDefinitionOperationsTest.php
Jira: CT-1805
Connection: https://github.com/keboola/connection/pull/5313
Tests:  https://github.com/keboola/storage-api-php-client/pull/1409
BQ driver : https://github.com/keboola/php-storage-driver-bigquery/pull/149
> CT-1805 add test for adding nullable/required columns

- tests/Backend/Bigquery/TableDefinitionOperationsTest.php
- tests/Backend/Snowflake/TableDefinitionOperationsTest.php
Jira: CT-1820
KBC: https://github.com/keboola/connection/pull/5325
> CT-1820 SNFLK basetype INTEGER fix

- apiary.apib
Jira: CT-XXX
KBC: XXX
just fix bool -> boolean which blocked apiary to be refreshed
> Fix boolean

- tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
- tests/Backend/SOX/PullTableTest.php
- tests/Backend/Workspaces/MetadataFromSnowflakeWorkspaceTest.php
Jira: CT-1820
KBC: - just tests
--- 
fix testu po zmene NUMBER(38,0) = INTEGER
> CT-1820 fix tests

- tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
Jira: CT-1818
KBC: https://github.com/keboola/connection/pull/5326
> CT-1818 fix case compare for columns

- tests/Backend/ExternalBuckets/SnowflakeRegisterExternalBucketInSecureDataShareTest.php
Jira: [CT-1566](https://keboola.atlassian.net/browse/CT-1566)
KBC: XXX
[CT-1566]: https://keboola.atlassian.net/browse/CT-1566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CT-1566 - test SDS bucket drop & events

- tests/Backend/ExternalBuckets/SnowflakeRegisterExternalBucketInSecureDataShareTest.php
Jira: [CT-1564](https://keboola.atlassian.net/browse/CT-1564)
KBC: XXX
[CT-1564]: https://keboola.atlassian.net/browse/CT-1564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CT-1564 - bucket in SDS should have isSnowflakeSharedDatabase

- apiary.apib
- tests/Backend/ExternalBuckets/SnowflakeBucketsRefreshTablesInformationTest.php
- tests/StorageApiTestCase.php
Jira: CT-1854
KBC:  https://github.com/keboola/connection/pull/5351
> CT-1854 test refresh metadata on alias

- tests/Backend/CommonPart1/BucketsTest.php
> FIX bucket owner in SOX test

- tests/Backend/NetworkPolicies/NetworkPoliciesTestCase.php
- tests/Backend/NetworkPolicies/SnowflakeNetworkPoliciesTest.php
Jira: CT-1874
KBC:  https://github.com/keboola/connection/pull/5368
> CT-1874 assign NP to project on beginning

- tests/File/AwsFileTest.php
Part of: https://keboola.atlassian.net/browse/ST-2479
KBC: XXX
- Backend - https://github.com/keboola/infrastructure/pull/2124
> AWS - Do not test public files

- tests/Backend/Workspaces/Backend/BigqueryWorkspaceBackend.php
> CT-1894 add retry on BQ isTableExists

- tests/Backend/ExternalBuckets/SnowflakeExternalBucketShareTest.php
Jira: CT-1894
KBC: XXX
Upravil sem dva testy, zatím ne refresh který taky padá.
> CT-1894 improve BYODB tests

- tests/Backend/CommonPart2/SnapshottingTest.php
- tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
- tests/Backend/SOX/MergeRequestsTest.php
- tests/Backend/Workspaces/Backend/BigqueryWorkspaceBackend.php
Jira: CT-1894
KBC: XXX
--
- New retries
- dump envents
- better GS query
> CT-1894 More fixes

- tests/Backend/Bigquery/ImportTreatValuesAsNullTest.php
- tests/Backend/Snowflake/ImportTreatValuesAsNullTest.php
- tests/StorageApiTestCase.php
- tests/_data/languages-empty-string.csv
Jira: CT-1896
KBC: XXX
--
- Oprava testů a přidání cases, takto to opravdu funguje
> CT-1896 test correctly TreatValuesAsNull on BQ

- tests/Backend/Bigquery/TableDefinitionOperationsTest.php
Jira: CT-1895
KBC: https://github.com/keboola/connection/pull/5397
> CT-1895 bq preview null

- composer.json
Potřebuju přidat podporu symfony 7 abych to mohl updatovat ve wrapperu a dále
> deps: allow symfony 7

- apiary.apib
- phpstan-baseline.neon
- src/Keboola/StorageApi/Workspaces.php
- tests/Backend/Snowflake/WorkspacesLoginTypesTest.php
- tests/Backend/WorkspaceCredentialsAssertTrait.php
- tests/Backend/Workspaces/ComponentsWorkspacesTest.php
- tests/Backend/Workspaces/ParallelWorkspacesTestCase.php
- tests/Backend/Workspaces/WorkspacesTest.php
Jira: CT-1920
KBC: https://github.com/keboola/connection/pull/5434
Prakticky je to no-release protože sa reálně v klientovi nic nemění, ale upravil sem typehinty tak dávám minor
Workspace platformUsageType and loginType attributes tests
> CT-1920 new Workspace props 

- apiary.apib
- tests/Backend/CommonPart1/DeleteRowsTest.php
Jira: CT-1951
KBC:  https://github.com/keboola/connection/pull/5441
> CT-1951 test of new params valuesBy*

- tests/Backend/CommonPart1/DeleteRowsTest.php
Jira: CT-1952
KBC:  https://github.com/keboola/connection/pull/5447
---
adding two methods to test valid/invalid deleting by table in WS
> CT-1952 test delete rows by workspace

- tests/Backend/CommonPart1/DeleteRowsTest.php
https://keboolaglobal.slack.com/archives/C055RTFCJ6M/p1738181493195129?thread_ts=1738181046.961349&cid=C055RTFCJ6M
> stabilize delete rows tests

- src/Keboola/StorageApi/Workspaces.php
- tests/Backend/Snowflake/WorkspacesLoginNameTest.php
- tests/Backend/Snowflake/WorkspacesLoginTypesTest.php
- tests/Backend/Workspaces/ParallelWorkspacesTestCase.php
Jira: CT-1921
KBC: --
Dávám minor přidal sem typehinty do klienta
- Test that login_name is set for new snowflake workspaces
> CT-1921 Workspace login name

- apiary.apib
- tests/Backend/Workspaces/WorkspacesTest.php
Jira: CT-1926
KBC: https://github.com/keboola/connection/pull/5449
- new parameter ssoLoginAvailable in docs and test
> CT-1926 SSO parameter for workspace detail

- tests/Backend/CommonPart1/DeleteRowsTest.php
Jira: CT-1952
KBC:  https://github.com/keboola/connection/pull/5463
> CT-1952 test invalid WS

- apiary.apib
- phpstan-baseline.neon
- src/Keboola/StorageApi/Client.php
- src/Keboola/StorageApi/Options/BucketUpdateOptions.php
- tests/Backend/CommonPart1/BucketsTest.php
- tests/Backend/Mixed/SharingTest.php
- tests/Common/GlobalSearchTest.php
Jira: [DMD-53](https://keboola.atlassian.net/browse/DMD-53)
KBC: https://github.com/keboola/connection/pull/5453
[DMD-53]: https://keboola.atlassian.net/browse/DMD-53?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DMD-53 Bucket color test

- tests/Backend/CommonPart1/BucketsTest.php
Jira: [DMD-53](https://keboola.atlassian.net/browse/DMD-53)
KBC: https://github.com/keboola/connection/pull/5453
[DMD-53]: https://keboola.atlassian.net/browse/DMD-53?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DMD-53 fix expected exception message in text

- apiary.apib
- tests/Backend/CommonPart1/BucketsTest.php
- tests/Backend/Mixed/SharingTest.php
Jira: [DMD-69](https://keboola.atlassian.net/browse/DMD-69)
KBC: https://github.com/keboola/connection/pull/5477
[DMD-69]: https://keboola.atlassian.net/browse/DMD-69?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DMD-69 - bucket owner email test

- apiary.apib
- tests/Backend/Mixed/SharingTest.php
Jira: [DMD-77](https://keboola.atlassian.net/browse/DMD-77)
KBC: https://github.com/keboola/connection/pull/5486
[DMD-77]: https://keboola.atlassian.net/browse/DMD-77?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DMD-77 test shared bucket list fields color and owner

- tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
- tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
- tests/Backend/SOX/ShareTest.php
Jira: [CT-1594](https://keboola.atlassian.net/browse/CT-1594)
KBC: https://github.com/keboola/connection/pull/5476
[CT-1594]: https://keboola.atlassian.net/browse/CT-1594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CT-1594 - adjust error message

- apiary.apib
- src/Keboola/StorageApi/Client.php
- src/Keboola/StorageApi/TableExporter.php
- tests/Backend/CommonPart1/ExportParamsTest.php
Jira: CT-2000
KBC: https://github.com/keboola/connection/pull/5496
> CT-2000 new export option includeInternalTimestamp

- tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
- tests/Backend/ExternalBuckets/SnowflakeRegisterBucketTest.php
Jira: [DMD-67](https://keboola.atlassian.net/browse/DMD-67)
KBC: https://github.com/keboola/connection/pull/5513
[DMD-67]: https://keboola.atlassian.net/browse/DMD-67?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DMD-67 - update tests for external buckets in import mapping

- apiary.apib
- src/Keboola/StorageApi/WorkspaceLoginType.php
- src/Keboola/StorageApi/Workspaces.php
- tests/Backend/Snowflake/WorkspacesLoginTypesTest.php
- tests/Backend/Workspaces/WorkspacesTest.php
Jira: CT-1979
KBC: https://github.com/keboola/connection/pull/5521
- new testWorkspaceWithSsoLoginType
- new option for create workspace login type `snowflake-person-sso`
> CT-1979 person sso login type for workspace

- phpstan-baseline.neon
- tests/Backend/Mixed/SharingTest.php
- tests/Backend/Mixed/StorageApiSharingTestCase.php
- tests/Backend/MixedSnowflakeBigquery/SharingTest.php
Jira: CT-XXX
KBC:  https://github.com/keboola/connection/pull/5564
> Roman fix share bucket

- apiary.apib
- phpstan-baseline.neon
- tests/Backend/CommonPart1/TimeTravelTest.php
- tests/Backend/Mixed/SharingTest.php
- tests/Backend/Mixed/StorageApiSharingTestCase.php
- tests/Backend/MixedSnowflakeBigquery/SharingTest.php
- tests/Backend/MixedSnowflakeExasol/SharingTest.php
- tests/Backend/MixedSnowflakeSynapse/SharingTest.php
- tests/Backend/Snowflake/CloneIntoWorkspaceTest.php
- tests/Backend/Snowflake/CopyIntoWorkspaceTest.php
- tests/Backend/Workspaces/SnowflakeDynamicBackendsTest.php
Jira: DMD-64
KBC:  https://github.com/keboola/connection/pull/5562
> DMD-64 remove depricated share method

- phpstan-baseline.neon
- src/Keboola/StorageApi/Options/BucketUpdateOptions.php
- src/Keboola/StorageApi/Options/Components/Configuration.php
- src/Keboola/StorageApi/Options/Components/ConfigurationMetadata.php
- src/Keboola/StorageApi/Options/Components/ConfigurationRow.php
- src/Keboola/StorageApi/Options/Components/ConfigurationRowState.php
- src/Keboola/StorageApi/Options/Components/ConfigurationState.php
- src/Keboola/StorageApi/Options/Components/ListComponentConfigurationsOptions.php
- src/Keboola/StorageApi/Options/Components/ListComponentsOptions.php
- src/Keboola/StorageApi/Options/Components/ListConfigurationMetadataOptions.php
- src/Keboola/StorageApi/Options/Components/ListConfigurationRowVersionsOptions.php
- src/Keboola/StorageApi/Options/Components/ListConfigurationRowsOptions.php
- src/Keboola/StorageApi/Options/Components/ListConfigurationVersionsOptions.php
- src/Keboola/StorageApi/Options/Components/ListConfigurationWorkspacesOptions.php
- src/Keboola/StorageApi/Options/Components/SearchComponentConfigurationsOptions.php
- src/Keboola/StorageApi/Options/FileUploadOptions.php
- src/Keboola/StorageApi/Options/FileUploadTransferOptions.php
- src/Keboola/StorageApi/Options/GetFileOptions.php
- src/Keboola/StorageApi/Options/IndexOptions.php
- src/Keboola/StorageApi/Options/ListFilesOptions.php
- src/Keboola/StorageApi/Options/Metadata/TableMetadataUpdateOptions.php
- src/Keboola/StorageApi/Options/SearchTablesOptions.php
- src/Keboola/StorageApi/Options/StatsOptions.php
- src/Keboola/StorageApi/Options/TokenAbstractOptions.php
- src/Keboola/StorageApi/Options/TokenCreateOptions.php
Vzdalene related k https://keboola.atlassian.net/browse/PST-883
Jak postupne updatujem PHPStan a nasazujem strict rules, zaciname narazet na nedostatecne natypovany veci. Tady jsem (za pomoci Copilota) pridal par typu, ktery si myslim by mely byt safe z pohledu BC.
> Pepa types

- src/Keboola/StorageApi/Components.php
> create config workspace wont reset password

- tests/Backend/Workspaces/WorkspacesSnowflakeTest.php
> Fix expected file sizes tests

- tests/Backend/Workspaces/WorkspacesSnowflakeTest.php
> fix jobs array pointer

- tests/Common/EventsTest.php
- tests/Common/TableEventsTest.php
- tests/Utils/EventTesterUtils.php
Jira: CT-1415
KBC: https://github.com/keboola/connection/pull/5592
> CT-1415 test that UUID is present in all events

- apiary.apib
- tests/Common/EventsTest.php
Jira: CT-1415
KBC: XXX
- api doc for uuid
- update test get event by uuid
> CT-1415 test that event cen be retrieve by uuid

- src/Keboola/StorageApi/Client.php
- tests/Backend/Snowflake/TableDefinitionOperationsTest.php
- tests/Backend/Workspaces/WorkspacesUnloadTest.php
- tests/StorageApiTestCase.php
- tests/Utils/GlobalSearchTesterUtils.php
Jira: CT-XXX
KBC: XXX
doufám že toto fixne ty dva testy co nám teď padajů. Lokálně to projde.
> fix unstable global search assertions

- tests/Utils/GlobalSearchTesterUtils.php
Jira: CT-XXX
KBC: XXX
- fix array needs to reindex
> fix array reindex after filter

- apiary.apib
- tests/Common/BranchEventsTest.php
- tests/Common/EventsTest.php
- tests/Common/TableEventsTest.php
- tests/Utils/EventTesterUtils.php
Jira: CT-2065
KBC: https://github.com/keboola/connection/pull/5611
> CT-2065 allow use UUID only

- tests/Common/BranchBucketsTest.php
- tests/Utils/GlobalSearchTesterUtils.php
https://keboolaglobal.slack.com/archives/C055RTFCJ6M/p1742815106748399
> update GS test asserts

- apiary.apib
- tests/Backend/CommonPart1/DeleteRowsTest.php
Jira: CT-1955
KBC:  https://github.com/keboola/connection/pull/5630
> Enable tests for BQ

- src/Keboola/StorageApi/Client.php
- tests/Backend/Mixed/SharingTest.php
Jira: DMD-64
KBC: https://github.com/keboola/connection/pull/5666
> remove deprecated tests

- apiary.apib
- composer.json
- src/Keboola/StorageApi/WorkspaceLoginType.php
- src/Keboola/StorageApi/Workspaces.php
- tests/Backend/Snowflake/WorkspacesLoginTypesTest.php
- tests/Backend/WorkspaceConnectionTrait.php
- tests/Utils/CertificateSigningRequest.php
- tests/Utils/PemKeyCertificateGenerator.php
- tests/Utils/PemKeyCertificatePair.php
Jira: PAT-178
KBC: https://github.com/keboola/connection/pull/5676
> PAT-178 ws keypair

- tests/Backend/ExternalBuckets/SnowflakeRegisterExternalBucketInSecureDataShareTest.php
Jira: DMD-92
KBC: https://github.com/keboola/connection/pull/5685
> DMD-92 Throw meaningful exception when view is out of sync

- tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
- tests/Backend/Workspaces/SnowflakeDynamicBackendsTest.php
Jira: PAT-178
KBC: https://github.com/keboola/connection/pull/5680
> PAT-178 ws keypair refactor

- apiary.apib
- src/Keboola/StorageApi/Workspaces.php
- src/Keboola/StorageApi/Workspaces/PublicKeyName.php
- src/Keboola/StorageApi/Workspaces/SetPublicKeyRequest.php
- tests/Backend/Snowflake/WorkspacesLoginTypesTest.php
Jira: PAT-248
KBC: https://github.com/keboola/connection/pull/5714
- new method Workspaces::setPublicKey
> PAT-248 Set workspace public key

- Dockerfile
> Remove forgotten dependencies in docker image build

- tests/File/CommonFileTest.php
Jira: PAT-140
KBC: https://github.com/keboola/connection/pull/5389
> PAT-140 Agnostic file filters test

- src/Keboola/StorageApi/Client.php
- tests/Backend/CommonPart1/ProfileTableTest.php
- tests/StorageApiTestCase.php
Jira: DMD-96
KBC: keboola/connection#5665
- New endpoint for data profiling with test checking only static data. Will be refactored with storage backend drive implementation of data profiling.
> DMD-96 Data profiling: Endpoints

- tests/Backend/Snowflake/WorkspacesLoginTypesTest.php
Jira: PAT-301
KBC: https://github.com/keboola/connection/pull/5735
> PAT-301 test invalid public key

- tests/Backend/Workspaces/WorkspacesTest.php
> fix event assertion

- tests/Common/ComponentsTest.php
Jira: PAT-295
KBC: https://github.com/keboola/connection/pull/5736
> PAT-295 expect new rows to have string id

- apiary.apib
- tests/Backend/Bigquery/WorkspacesQueryTest.php
- tests/Backend/Workspaces/Backend/BigqueryWorkspaceBackend.php
Jira: DMD-163
KBC:  https://github.com/keboola/connection/pull/5922
> DMD-163 tests for query endpoint

- tests/Backend/Snowflake/TypedTableInWorkspaceTest.php
Jira: [DMD-120](https://keboola.atlassian.net/browse/DMD-120) / [DMD-175](https://keboola.atlassian.net/browse/DMD-175)
KBC: https://github.com/keboola/connection/pull/5726
[DMD-120]: https://keboola.atlassian.net/browse/DMD-120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DMD-175]: https://keboola.atlassian.net/browse/DMD-175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DMD-175 DMD-120 add testUnloadFromWSToTypedTableCTAS case for feature ctas-om

- apiary.apib
- tests/Backend/Bigquery/ProfileTableTest.php
- tests/Backend/Snowflake/ProfileTableTest.php
Jira:  DMD-101
KBC:  https://github.com/keboola/connection/pull/5995
> DMD-101 test snfk profiling

- tests/Backend/Workspaces/WorkspacesLoadTest.php
Jira: CT-XXX
KBC: https://github.com/keboola/connection/pull/6015
> add test cases for empty where filter

- tests/Backend/Snowflake/WorkspacesReaderTest.php
Update: DMD-195 - Reader WS reset public key
Jira: https://keboola.atlassian.net/browse/DMD-195
KBC: XXX
> Update: DMD-195 - Reader WS reset public key

- tests/Backend/MixedSnowflakeBigquery/SharingTest.php
Jira: CT-2185
KBC: https://github.com/keboola/connection/pull/6031
> CT-2185 test bq export filters

- tests/Backend/Snowflake/WorkspacesQueryTest.php
INC-24637
https://github.com/keboola/connection/pull/6037
> INC-24637 more tests for query endpoint

- phpunit.xml.dist
- tests/Backend/ExternalBuckets/ScheduledTasksTest.php
Jira: CT-197
KBC: −
---
Fix: Test was in suite without "external bucket" feature. Moved to suite with feature enabled.
> test(scheduled tasks): Move scheduled task test to correct suite

- phpunit.xml.dist
- tests/Backend/ReaderWorkspaces/WorkspacesReaderTest.php
- tests/Backend/Snowflake/WorkspacesReaderTest.php
Jira: (https://keboola.atlassian.net/browse/DMD-166)
KBC:  https://github.com/keboola/connection/pull/6028
> Update: DMD-166 - Remove readers WS test

- tests/Backend/Workspaces/SnowflakeDynamicBackendsTest.php
Jira: CT-XXX
KBC: [XXX](https://github.com/keboola/connection/pull/6078)
> Test load to table with dynamic backend

- phpstan-baseline.neon
- tests/Backend/FileWorkspace/ComponentsWorkspacesTest.php
- tests/Backend/FileWorkspace/FileWorkspaceTestCase.php
- tests/Backend/FileWorkspace/WorkspacesLoadTest.php
- tests/Backend/FileWorkspace/WorkspacesTest.php
- tests/Backend/FileWorkspace/WorkspacesUnloadTest.php
- tests/Backend/Mixed/LegacyWorkspacesTest.php
- tests/Backend/Mixed/Workspaces/BaseWorkSpacesTestCase.php
- tests/Backend/Mixed/WorkspacesRenameTest.php
- tests/Backend/ReaderWorkspaces/WorkspacesReaderTest.php
- tests/Backend/Snowflake/CopyIntoWorkspaceTest.php
- tests/Backend/Workspaces/BranchComponentsWorkspacesTest.php
- tests/Backend/Workspaces/ComponentsWorkspacesTest.php
- tests/Backend/Workspaces/DeleteWorkspacesTrait.php
- tests/Backend/Workspaces/WorkspacesTestCase.php
> DMD-168 fixes

- apiary.apib
- src/Keboola/StorageApi/Client.php
- src/Keboola/StorageApi/Options/TableImport/DeduplicationStrategy.php
- tests/Backend/Snowflake/TypedTableInWorkspaceTest.php
Jira: DMD-177
KBC: keboola/connection#6068
> DMD-177 Deduplication parameter in import

- tests/Backend/CommonPart2/SlicedImportsTest.php
- tests/Backend/Workspaces/LegacyWorkspacesSnowflakeTest.php
- tests/Backend/Workspaces/WorkspacesSnowflakeTest.php
Jira: -
KBC: -
i was tired from `This test did not perform any assertions` so if the test does not assert anything (just not failing is good enough), say it explicitly
> Explicitly state missing assertions

- phpstan-baseline.neon
- tests/Backend/FileWorkspace/ComponentsWorkspacesTest.php
- tests/Backend/FileWorkspace/FileWorkspaceTestCase.php
- tests/Backend/FileWorkspace/WorkspacesLoadTest.php
- tests/Backend/FileWorkspace/WorkspacesTest.php
- tests/Backend/FileWorkspace/WorkspacesUnloadTest.php
- tests/Backend/Mixed/LegacyWorkspacesTest.php
- tests/Backend/Mixed/Workspaces/BaseWorkSpacesTestCase.php
- tests/Backend/Mixed/WorkspacesRenameTest.php
- tests/Backend/ReaderWorkspaces/WorkspacesReaderTest.php
- tests/Backend/Snowflake/CopyIntoWorkspaceTest.php
- tests/Backend/Workspaces/BranchComponentsWorkspacesTest.php
- tests/Backend/Workspaces/ComponentsWorkspacesTest.php
- tests/Backend/Workspaces/DeleteWorkspacesTrait.php
- tests/Backend/Workspaces/WorkspacesTestCase.php
Jira: https://keboola.atlassian.net/browse/DMD-168
KBC:https://github.com/keboola/connection/pull/6067
v podstate iba testujeme EPs kt. by mali byt zakazane pre reader workspaces
> Update: DMD-168: Deny/Block some operations for reader workspaces

- apiary.apib
https://keboolaglobal.slack.com/archives/C0553EM2RGX/p1754485848111839
Jira: CT-XXX
KBC: XXX
> fix backends supports

- tests/StorageApiTestCase.php
> fix drop forgotten debug statement

- tests/Backend/ExternalBuckets/ScheduledTasksTest.php
> test(scheduled task): Replace long waiting time with retries

- apiary.apib
- phpstan-baseline.neon
- src/Keboola/StorageApi/Components.php
- tests/Common/ComponentsTest.php
Reverts keboola/storage-api-php-client#1558
Connection PR: https://github.com/keboola/connection/pull/6164
revert a pridavam test vsetkych stlpcov pre komponent detail
> Revert "Revert "Roman/pat 663 new component detail endpoint""

- tests/Backend/Snowflake/WorkspacesQueryTest.php
https://keboolaglobal.slack.com/archives/C055RTFCJ6M/p1757493289297329?thread_ts=1757493071.977169&cid=C055RTFCJ6M
Jira: CT-XXX
KBC: XXX
> fix test there is a extra dot

- apiary.apib
- phpstan-baseline.neon
- tests/Backend/ExternalBuckets/BigqueryRegisterBucketTest.php
- tests/Backend/Snowflake/CloneIntoWorkspaceTest.php
- tests/Backend/Workspaces/LegacyWorkspacesLoadTest.php
- tests/Backend/Workspaces/WorkspacesLoadTest.php
Jira: DMD-378
KBC: https://github.com/keboola/connection/pull/6206
> DMD-378 Load support clone
